package handlers

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/gin-gonic/gin"

	"velox/go-master/internal/upload/drive"
)

// GetGroups godoc
// @Summary Get stock groups
// @Description Get predefined stock clip groups
// @Tags drive
// @Produce json
// @Success 200 {object} map[string]interface{}
// @Router /drive/groups [get]
func (h *DriveHandler) GetGroups(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"ok":     true,
		"groups": drive.StockDriveGroups,
	})
}

// UploadClipSimple godoc
// @Summary Simple clip upload
// @Description Simple text upload to Drive
// @Tags drive
// @Accept json
// @Produce json
// @Param request body drive.UploadClipSimpleRequest true "Simple upload request"
// @Success 200 {object} map[string]interface{}
// @Router /drive/upload-clip-simple [post]
func (h *DriveHandler) UploadClipSimple(c *gin.Context) {
	client, err := h.getClient(c)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"ok": false, "error": err.Error()})
		return
	}

	var req drive.UploadClipSimpleRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": err.Error()})
		return
	}

	topic := req.Topic
	if topic == "" {
		topic = "general"
	}

	group := drive.DetectGroupFromTopic(topic)
	groupName := drive.StockDriveGroups[group]

	// Create folder structure
	groupFolderID, err := client.GetOrCreateFolder(c.Request.Context(), groupName, "root")
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"ok": false, "error": "Failed to create group folder"})
		return
	}

	topicFolderID, err := client.GetOrCreateFolder(c.Request.Context(), topic, groupFolderID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"ok": false, "error": "Failed to create topic folder"})
		return
	}

	content := fmt.Sprintf(`# Clip: %s

Timestamp: %s

%s

---
Generated by Studio App
`, topic, req.Timestamp, req.Text)

	ts := strings.NewReplacer(":", "", ".", "").Replace(req.Timestamp)
	filename := fmt.Sprintf("clip_%s.txt", ts)

	tempPath := filepath.Join(os.TempDir(), filename)
	if err := os.WriteFile(tempPath, []byte(content), 0644); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"ok": false, "error": err.Error()})
		return
	}

	fileID, err := client.UploadFile(c.Request.Context(), tempPath, topicFolderID, filename)
	os.Remove(tempPath)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"ok": false, "error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"ok":      true,
		"file_id": fileID,
		"url":     drive.GetDriveLink(fileID),
		"group":   groupName,
		"topic":   topic,
	})
}
