// Package overlays — chronon.go compiles the semantic OverlayPlan into the
// concrete chronon.render-plan.v1 document the RenderingGen queue worker
// writes to plan.json and hands to chronon3d_cli.
//
// PipelineGen owns WHAT appears and WHEN (the OverlayPlan); Chronon owns the
// pixels. This compiler is the only bridge between the two: it turns
// template-level instructions (the canonical semantic entities) into concrete
// layers with presets, fits, positions and integer frame ranges, and projects
// the plan's asset refs into content-addressed queue assets (hash + logical
// path).
//
// Every semantic entity terminates in one of the four canonical primitives
// (PrimitiveText / PrimitiveImage / PrimitiveVideo / PrimitiveShape), which
// map onto the concrete Chronon layer types as follows:
//
//	Text  → "text"   (preset-driven text layer, layer.text)
//	Image → "image"  (content-addressed image, layer.asset)
//	Video → "video"  (content-addressed video, layer.source)
//	Shape → "color"  (full-canvas rect, layer.color)
//
// The nine canonical entities are IMPORTANT_PHRASE, IMPORTANT_WORD,
// IMAGE_OVERLAY, PERSON, NUMBER, QUOTE, LOCATION, PRODUCT and LOGO; the
// Video and Shape primitives are exercised by the VIDEO_BACKGROUND and
// SHAPE templates.
package overlays

import (
	"encoding/json"
	"fmt"
	"math"
	"strings"
)

const (
	// ChrononSchema and ChrononVersion identify the chronon.render-plan.v1
	// document emitted by this compiler (see Chronon3d/schemas/
	// chronon.render-plan.v1.schema.json).
	ChrononSchema  = "chronon.render-plan"
	ChrononVersion = 1
)

const (
	// CanonicalTextFontPath is the workspace-relative path of the canonical
	// font asset. It is NO LONGER written onto text layers: Chronon's
	// VisualPresetRegistry owns the font (font_asset) and resolves it via
	// StyleResolver. PipelineGen only carries the bytes as a queue asset so
	// the worker can materialize the path the preset references.
	CanonicalTextFontPath = "assets/fonts/DejaVuSans.ttf"
	// GoldenFontHash is the SHA-256 of the vendored deterministic font
	// fixture (RenderingGen/testdata/golden/DejaVuSans.ttf, generated by
	// RenderingGen/infra/e2e/gen-golden-assets.py). Changing it breaks the
	// cross-repo golden invariant on purpose.
	GoldenFontHash = "690243adfefe0ce154b547db6205794bd30ac4277275179517a90994f4980648"
	// GoldenPresetFontHash is the font bundled by Chronon's VisualPresetRegistry.
	// Text layers may still carry an explicit font_asset (GoldenFontHash); the
	// preset font is an additional runtime dependency that must be staged too.
	GoldenPresetFontHash    = "983676516167748b74de6f4771fb384c664fd913acb8b471122ecacf5da5ea6c"
	CanonicalPresetFontPath = "assets/fonts/Poppins-Bold.ttf"
)

// Primitive is the canonical primitive every semantic entity terminates in.
// PipelineGen classifies each entity as one of the four canonical primitives;
// the compiler translates the primitive into the concrete Chronon layer type
// (see the package docblock for the mapping).
type Primitive string

const (
	// PrimitiveText is a preset-driven text layer.
	PrimitiveText Primitive = "text"
	// PrimitiveImage is a content-addressed image layer.
	PrimitiveImage Primitive = "image"
	// PrimitiveVideo is a content-addressed video layer.
	PrimitiveVideo Primitive = "video"
	// PrimitiveShape is a full-canvas solid-color rect layer.
	PrimitiveShape Primitive = "shape"
)

// ChrononFontAsset is the chronon.render-plan.v1 `font_asset` block that
// pins a text layer's font bytes by logical path and family/weight. The
// production chronon3d_cli resolves the asset by hash from the queue job's
// assets list at materialization time; the family/weight are advisory,
// letting the StyleResolver swap to a preset's own font when one is
// defined but never silently dropping to an empty font name.
//
// Family:  DejaVu Sans (the vendored font in CanonicalTextFontPath)
// Weight:  700 (Bold; honest default when the preset doesn't pin its own)
// Asset:   CanonicalTextFontPath
type ChrononFontAsset struct {
	Asset  string `json:"asset"`
	Family string `json:"family"`
	Weight int    `json:"weight"`
}

// primitiveToLayerType maps the canonical Primitive (text/image/video/shape)
// to the chronon.render-plan.v1 `type` enum (text/image/video/color). This
// lets the compiler emit a non-empty `type` on every layer (the production
// validator requires it regardless of preset).
func primitiveToLayerType(p Primitive) string {
	switch p {
	case PrimitiveText:
		return "text"
	case PrimitiveImage:
		return "image"
	case PrimitiveVideo:
		return "video"
	case PrimitiveShape:
		return "color"
	default:
		return string(p)
	}
}

// TemplateSpec maps a semantic template to the concrete Chronon layer shape
// it compiles to. OverlayItem.Params may override fit/position/box/color
// values; the defaults below are the canonical golden shapes.
type TemplateSpec struct {
	LayerType string
	Fit       string
	BoxWidth  int
	BoxHeight int
	Position  []float64
	// Primitive is the canonical primitive (Text/Image/Video/Shape) this
	// template terminates in. Every template MUST declare one; the compiler
	// fails closed on an empty value.
	Primitive Primitive
	// FullCanvas stretches the layer to the full canvas for the whole clip
	// (backgrounds). The compiler honors it instead of the item window.
	FullCanvas bool
	// Color is the default RGBA fill for the Shape primitive (layer.color).
	Color []float64
	// BlendMode is the default compositing blend for effect layers (the
	// LIGHT_LEAK template defaults to "screen"). Empty means the renderer's
	// default blend.
	BlendMode string
	// Opacity is the default layer opacity in [0,1]. Zero means "no override"
	// (the renderer's default); a per-item opacity param always wins.
	Opacity float64
	// Loop controls a source whose duration is shorter than the layer window:
	// true loops the source, false (default) terminates the layer at the
	// source's end. There is never an implicit temporal stretch.
	Loop bool
}

// ChrononLayerAnimation mirrors the chronon.render-plan.v1 layer animation
// block: the motion preset applied to the layer (e.g. "fade_in", "slide_up",
// "scale_in") plus the optional explicit window. The compiler projects only
// the preset from item Params (["animation"]["preset"]); start/duration
// frames may be carried for explicit windows.
type ChrononLayerAnimation struct {
	Preset         string `json:"preset"`
	StartFrame     int64  `json:"start_frame,omitempty"`
	DurationFrames int64  `json:"duration_frames,omitempty"`
	// Unit is the text-run selector scope ("word" | "glyph" | "line") the
	// per-unit animation applies at. Absent → Chronon's preset default.
	Unit string `json:"unit,omitempty"`
	// Enter/Exit are the per-unit ramp windows. Absent → Chronon's preset
	// defaults (8 / 6 frames).
	Enter *ChrononAnimWindow `json:"enter,omitempty"`
	Exit  *ChrononAnimWindow `json:"exit,omitempty"`
}

// ChrononAnimWindow is an enter/exit ramp window of a layer animation:
// how many frames the per-unit enter/exit ramp lasts (duration_frames).
type ChrononAnimWindow struct {
	DurationFrames int64 `json:"duration_frames"`
}

// ChrononCanvas mirrors the chronon.render-plan.v1 canvas block. Frame rate
// is the canonical rational pair fps_num/fps_den.
type ChrononCanvas struct {
	Width          int   `json:"width"`
	Height         int   `json:"height"`
	FPSNum         int   `json:"fps_num"`
	FPSDen         int   `json:"fps_den"`
	DurationFrames int64 `json:"duration_frames"`
}

// ChrononLayer mirrors the chronon.render-plan.v1 layer block. Field order
// follows the canonical golden document so JSON output stays stable.
type ChrononLayer struct {
	ID string `json:"id"`
	// Type is the layer primitive. It is omitted for preset-driven layers
	// (Chronon derives it from the preset's supported_layer — ADR-029) and
	// present only for preset-less primitives.
	Type  string `json:"type,omitempty"`
	Asset string `json:"asset,omitempty"`
	// FontAsset is the content-addressed text-layer font, projected on
	// every text layer so the worker's materializer resolves the bytes the
	// icon font engine falls back to. Without it, multiple production paths
	// (text_run fallback, native_av encoder warm shell) silently drop
	// glyphs because the resolver sees an empty `font` name.
	FontAsset *ChrononFontAsset `json:"font_asset,omitempty"`
	// Source is the video-source logical path for the Video primitive:
	// Chronon "video" layers reference `source`, not `asset`.
	Source string `json:"source,omitempty"`
	// Color is the RGBA fill of the Shape primitive: Chronon "color" layers
	// render a full-canvas rect.
	Color []float64 `json:"color,omitempty"`
	Text  string    `json:"text,omitempty"`
	// Font and FontSize are legacy transport fields kept only for a stable
	// JSON shape. They are NO LONGER emitted: Chronon's VisualPresetRegistry
	// owns the canonical font asset (font_asset) and size via StyleResolver;
	// PipelineGen only carries the font bytes as a queue asset (see
	// CanonicalTextFontPath / GoldenFontHash).
	Font           string    `json:"font,omitempty"`
	FontSize       float64   `json:"font_size,omitempty"`
	Preset         string    `json:"preset,omitempty"`
	BoxWidth       int       `json:"box_width,omitempty"`
	BoxHeight      int       `json:"box_height,omitempty"`
	Fit            string    `json:"fit,omitempty"`
	Position       []float64 `json:"position,omitempty"`
	StartFrame     int64     `json:"start_frame"`
	DurationFrames int64     `json:"duration_frames"`
	// Animation is the motion preset applied to this layer (e.g. fade_in,
	// slide_up, scale_in). Projected from item Params["animation"]; a layer
	// without an animation param carries none.
	Animation *ChrononLayerAnimation `json:"animation,omitempty"`
	// Style is the direct Chronon LayerStylePlan override. Chronon owns the
	// authoritative style schema; this boundary preserves it as JSON.
	Style map[string]any `json:"style,omitempty"`
	// BlendMode is the compositing blend applied to the layer (e.g. the
	// LIGHT_LEAK template's "screen" / "add"). Empty means renderer default.
	BlendMode string `json:"blend_mode,omitempty"`
	// Opacity is the layer opacity in [0,1]; 0 means "no override" (renderer
	// default). Non-zero values are carried verbatim.
	Opacity float64 `json:"opacity,omitempty"`
	// Loop controls a source shorter than the layer window: true loops,
	// false (default) terminates at the source's end (never a stretch).
	Loop bool `json:"loop,omitempty"`
}

// ChrononOutput mirrors the chronon.render-plan.v1 output block. The worker
// renders to this path inside the job workspace (output/result.mp4). The
// Format/Codec/PixelFormat fields are derived from the plan's media contract
// (never hardcoded per layer); the cross-repo golden (no contract) pins
// mp4/h264 with no pixel format.
type ChrononOutput struct {
	Path        string `json:"path"`
	Format      string `json:"format,omitempty"`
	Codec       string `json:"codec,omitempty"`
	PixelFormat string `json:"pixel_format,omitempty"`
}

// ChrononPlan is the full chronon.render-plan.v1 document.
type ChrononPlan struct {
	Schema  string         `json:"schema"`
	Version int            `json:"version"`
	JobID   string         `json:"job_id"`
	Canvas  ChrononCanvas  `json:"canvas"`
	Layers  []ChrononLayer `json:"layers"`
	Output  ChrononOutput  `json:"output"`
}

// ChrononAsset is the content-addressed queue asset reference the worker
// materializes by hash into the workspace at LogicalPath.
type ChrononAsset struct {
	Hash        string `json:"hash"`
	LogicalPath string `json:"logical_path"`
}

// ChrononCompileResult is the compiled document plus the assets the queue
// job must carry so materialization resolves every layer reference.
type ChrononCompileResult struct {
	Plan   ChrononPlan
	Assets []ChrononAsset
}

// chrononOutputFor derives the chronon.render-plan.v1 output block from the
// plan's media contract. An empty contract keeps the legacy mp4/h264 default
// pinned by the cross-repo golden (no alpha, no pixel format); a resolved
// contract drives container/codec/pixel format so the renderer never guesses
// a codec per layer. An unknown contract id fails closed.
func chrononOutputFor(plan OverlayPlan) (ChrononOutput, error) {
	if strings.TrimSpace(plan.MediaContract) == "" {
		return ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"}, nil
	}
	contract, err := ResolveMediaContract(plan.MediaContract)
	if err != nil {
		return ChrononOutput{}, err
	}
	return ChrononOutput{
		Path:        "result." + contract.Container,
		Format:      contract.Container,
		Codec:       contract.Codec,
		PixelFormat: contract.PixelFormat,
	}, nil
}

// CompileChrononPlan compiles a validated semantic OverlayPlan into the
// concrete chronon.render-plan.v1 document and its queue asset references.
//
// Canvas, frame ranges and layer geometry are derived deterministically:
//
//	start_frame   = round(StartMs * fps / 1000)
//	duration      = frameAt(EndMs) - frameAt(StartMs)
//	duration_frames = frameAt(max EndMs over all items)
//
// Template mapping is table-driven (templateRegistry); per-item Params may
// override fit/position/box_width/box_height/preset. Layers preserve the
// OverlayPlan item order (background first, overlays on top).
func CompileChrononPlan(plan OverlayPlan) (ChrononCompileResult, error) {
	if err := plan.Validate(); err != nil {
		return ChrononCompileResult{}, err
	}
	renderer := strings.TrimSpace(plan.RendererVersion)
	if renderer != "" && renderer != "chronon" {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: renderer %q cannot compile to chronon.render-plan.v1", renderer)
	}
	if plan.Width <= 0 || plan.Height <= 0 || plan.FPSNum <= 0 || plan.FPSDen <= 0 {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: width, height and frame rate must be positive for chronon compilation")
	}
	if len(plan.Items) == 0 {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: cannot compile an empty item list to chronon")
	}

	fps := float64(plan.FPSNum) / float64(plan.FPSDen)
	frameAtUS := func(us int64) int64 {
		return int64(math.Round(float64(us) * fps / 1_000_000.0))
	}
	itemEndUS := func(item OverlayItem) int64 {
		if item.DurationUS > 0 {
			return item.StartUS + item.DurationUS
		}
		return item.EndMs * 1000
	}

	var maxEndUS int64
	for _, item := range plan.Items {
		if end := itemEndUS(item); end > maxEndUS {
			maxEndUS = end
		}
	}
	if maxEndUS <= 0 {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: no item has a positive end time")
	}

	layers := make([]ChrononLayer, 0, len(plan.Items)+1)
	seenAssets := make(map[string]string)
	var assets []ChrononAsset
	needsFont := false
	var layoutCandidates []imageLayoutCandidate

	// Process background layer.
	if bgLayer, bgAssets := compileBackgroundLayer(plan, maxEndUS, frameAtUS); bgLayer.ID != "" {
		layers = append(layers, bgLayer)
		for _, a := range bgAssets {
			seenAssets[a.Hash] = a.LogicalPath
		}
		assets = append(assets, bgAssets...)
	}

	// Process item layers.
	for index, item := range plan.Items {
		layer, itemAssets, itemNeedsFont, layoutCandidate, err := compileItemLayer(
			item, index, plan, maxEndUS, frameAtUS, seenAssets,
		)
		if err != nil {
			return ChrononCompileResult{}, err
		}
		if itemNeedsFont {
			needsFont = true
		}
		if layoutCandidate != nil {
			layoutCandidates = append(layoutCandidates, *layoutCandidate)
		}
		for _, a := range itemAssets {
			seenAssets[a.Hash] = a.LogicalPath
		}
		assets = append(assets, itemAssets...)
		layers = append(layers, layer)
	}

	layoutImages(layers, plan.Width, plan.Height, layoutCandidates)

	if needsFont {
		if _, dup := seenAssets[GoldenFontHash]; !dup {
			seenAssets[GoldenFontHash] = CanonicalTextFontPath
			assets = append(assets, ChrononAsset{Hash: GoldenFontHash, LogicalPath: CanonicalTextFontPath})
		}
	}

	output, err := chrononOutputFor(plan)
	if err != nil {
		return ChrononCompileResult{}, err
	}
	return ChrononCompileResult{
		Plan: ChrononPlan{
			Schema:  ChrononSchema,
			Version: ChrononVersion,
			JobID:   plan.PlanID,
			Canvas: ChrononCanvas{
				Width:          plan.Width,
				Height:         plan.Height,
				FPSNum:         plan.FPSNum,
				FPSDen:         plan.FPSDen,
				DurationFrames: frameAtUS(maxEndUS),
			},
			Layers: layers,
			Output: output,
		},
		Assets: assets,
	}, nil
}

// Marshal returns the compiled plan as stable JSON.
func (c ChrononCompileResult) Marshal() ([]byte, error) {
	b, err := json.Marshal(c.Plan)
	if err != nil {
		return nil, fmt.Errorf("chronon compile: marshal plan: %w", err)
	}
	return b, nil
}
