// Package overlays — chronon.go compiles the semantic OverlayPlan into the
// concrete chronon.render-plan.v1 document the RenderingGen queue worker
// writes to plan.json and hands to chronon3d_cli.
//
// PipelineGen owns WHAT appears and WHEN (the OverlayPlan); Chronon owns the
// pixels. This compiler is the only bridge between the two: it turns
// template-level instructions (the canonical semantic entities) into concrete
// layers with presets, fits, positions and integer frame ranges, and projects
// the plan's asset refs into content-addressed queue assets (hash + logical
// path).
//
// Every semantic entity terminates in one of the four canonical primitives
// (PrimitiveText / PrimitiveImage / PrimitiveVideo / PrimitiveShape), which
// map onto the concrete Chronon layer types as follows:
//
//	Text  → "text"   (preset-driven text layer, layer.text)
//	Image → "image"  (content-addressed image, layer.asset)
//	Video → "video"  (content-addressed video, layer.source)
//	Shape → "color"  (full-canvas rect, layer.color)
//
// The nine canonical entities are IMPORTANT_PHRASE, IMPORTANT_WORD,
// IMAGE_OVERLAY, PERSON, NUMBER, QUOTE, LOCATION, PRODUCT and LOGO; the
// Video and Shape primitives are exercised by the VIDEO_BACKGROUND and
// SHAPE templates.
package overlays

import (
	"encoding/json"
	"fmt"
	"math"
	"path"
	"strings"
)

const (
	// ChrononSchema and ChrononVersion identify the chronon.render-plan.v1
	// document emitted by this compiler (see Chronon3d/schemas/
	// chronon.render-plan.v1.schema.json).
	ChrononSchema  = "chronon.render-plan"
	ChrononVersion = 1
)

const (
	// CanonicalTextFontPath is the workspace-relative path of the canonical
	// font asset. It is NO LONGER written onto text layers: Chronon's
	// VisualPresetRegistry owns the font (font_asset) and resolves it via
	// StyleResolver. PipelineGen only carries the bytes as a queue asset so
	// the worker can materialize the path the preset references.
	CanonicalTextFontPath = "assets/fonts/DejaVuSans.ttf"
	// GoldenFontHash is the SHA-256 of the vendored deterministic font
	// fixture (RenderingGen/testdata/golden/DejaVuSans.ttf, generated by
	// RenderingGen/infra/e2e/gen-golden-assets.py). Changing it breaks the
	// cross-repo golden invariant on purpose.
	GoldenFontHash = "690243adfefe0ce154b547db6205794bd30ac4277275179517a90994f4980648"
)

// Primitive is the canonical primitive every semantic entity terminates in.
// PipelineGen classifies each entity as one of the four canonical primitives;
// the compiler translates the primitive into the concrete Chronon layer type
// (see the package docblock for the mapping).
type Primitive string

const (
	// PrimitiveText is a preset-driven text layer.
	PrimitiveText Primitive = "text"
	// PrimitiveImage is a content-addressed image layer.
	PrimitiveImage Primitive = "image"
	// PrimitiveVideo is a content-addressed video layer.
	PrimitiveVideo Primitive = "video"
	// PrimitiveShape is a full-canvas solid-color rect layer.
	PrimitiveShape Primitive = "shape"
)

// TemplateSpec maps a semantic template to the concrete Chronon layer shape
// it compiles to. OverlayItem.Params may override fit/position/box/color
// values; the defaults below are the canonical golden shapes.
type TemplateSpec struct {
	LayerType string
	Fit       string
	BoxWidth  int
	BoxHeight int
	Position  []float64
	// Primitive is the canonical primitive (Text/Image/Video/Shape) this
	// template terminates in. Every template MUST declare one; the compiler
	// fails closed on an empty value.
	Primitive Primitive
	// FullCanvas stretches the layer to the full canvas for the whole clip
	// (backgrounds). The compiler honors it instead of the item window.
	FullCanvas bool
	// Color is the default RGBA fill for the Shape primitive (layer.color).
	Color []float64
	// BlendMode is the default compositing blend for effect layers (the
	// LIGHT_LEAK template defaults to "screen"). Empty means the renderer's
	// default blend.
	BlendMode string
	// Opacity is the default layer opacity in [0,1]. Zero means "no override"
	// (the renderer's default); a per-item opacity param always wins.
	Opacity float64
	// Loop controls a source whose duration is shorter than the layer window:
	// true loops the source, false (default) terminates the layer at the
	// source's end. There is never an implicit temporal stretch.
	Loop bool
}

// ChrononLayerAnimation mirrors the chronon.render-plan.v1 layer animation
// block: the motion preset applied to the layer (e.g. "fade_in", "slide_up",
// "scale_in") plus the optional explicit window. The compiler projects only
// the preset from item Params (["animation"]["preset"]); start/duration
// frames may be carried for explicit windows.
type ChrononLayerAnimation struct {
	Preset         string `json:"preset"`
	StartFrame     int64  `json:"start_frame,omitempty"`
	DurationFrames int64  `json:"duration_frames,omitempty"`
	// Unit is the text-run selector scope ("word" | "glyph" | "line") the
	// per-unit animation applies at. Absent → Chronon's preset default.
	Unit string `json:"unit,omitempty"`
	// Enter/Exit are the per-unit ramp windows. Absent → Chronon's preset
	// defaults (8 / 6 frames).
	Enter *ChrononAnimWindow `json:"enter,omitempty"`
	Exit  *ChrononAnimWindow `json:"exit,omitempty"`
}

// ChrononAnimWindow is an enter/exit ramp window of a layer animation:
// how many frames the per-unit enter/exit ramp lasts (duration_frames).
type ChrononAnimWindow struct {
	DurationFrames int64 `json:"duration_frames"`
}

// ChrononCanvas mirrors the chronon.render-plan.v1 canvas block.
type ChrononCanvas struct {
	Width          int   `json:"width"`
	Height         int   `json:"height"`
	FPS            int   `json:"fps"`
	DurationFrames int64 `json:"duration_frames"`
}

// ChrononLayer mirrors the chronon.render-plan.v1 layer block. Field order
// follows the canonical golden document so JSON output stays stable.
type ChrononLayer struct {
	ID    string `json:"id"`
	Type  string `json:"type"`
	Asset string `json:"asset,omitempty"`
	// Source is the video-source logical path for the Video primitive:
	// Chronon "video" layers reference `source`, not `asset`.
	Source string `json:"source,omitempty"`
	// Color is the RGBA fill of the Shape primitive: Chronon "color" layers
	// render a full-canvas rect.
	Color []float64 `json:"color,omitempty"`
	Text  string    `json:"text,omitempty"`
	// Font and FontSize are legacy transport fields kept only for a stable
	// JSON shape. They are NO LONGER emitted: Chronon's VisualPresetRegistry
	// owns the canonical font asset (font_asset) and size via StyleResolver;
	// PipelineGen only carries the font bytes as a queue asset (see
	// CanonicalTextFontPath / GoldenFontHash).
	Font     string  `json:"font,omitempty"`
	FontSize float64 `json:"font_size,omitempty"`
	Preset         string    `json:"preset,omitempty"`
	BoxWidth       int       `json:"box_width,omitempty"`
	BoxHeight      int       `json:"box_height,omitempty"`
	Fit            string    `json:"fit,omitempty"`
	Position       []float64 `json:"position,omitempty"`
	StartFrame     int64     `json:"start_frame"`
	DurationFrames int64     `json:"duration_frames"`
	// Animation is the motion preset applied to this layer (e.g. fade_in,
	// slide_up, scale_in). Projected from item Params["animation"]; a layer
	// without an animation param carries none.
	Animation *ChrononLayerAnimation `json:"animation,omitempty"`
	// BlendMode is the compositing blend applied to the layer (e.g. the
	// LIGHT_LEAK template's "screen" / "add"). Empty means renderer default.
	BlendMode string `json:"blend_mode,omitempty"`
	// Opacity is the layer opacity in [0,1]; 0 means "no override" (renderer
	// default). Non-zero values are carried verbatim.
	Opacity float64 `json:"opacity,omitempty"`
	// Loop controls a source shorter than the layer window: true loops,
	// false (default) terminates at the source's end (never a stretch).
	Loop bool `json:"loop,omitempty"`
}

// ChrononOutput mirrors the chronon.render-plan.v1 output block. The worker
// renders to this path inside the job workspace (output/result.mp4). The
// Format/Codec/PixelFormat fields are derived from the plan's media contract
// (never hardcoded per layer); the cross-repo golden (no contract) pins
// mp4/h264 with no pixel format.
type ChrononOutput struct {
	Path        string `json:"path"`
	Format      string `json:"format,omitempty"`
	Codec       string `json:"codec,omitempty"`
	PixelFormat string `json:"pixel_format,omitempty"`
}

// ChrononPlan is the full chronon.render-plan.v1 document.
type ChrononPlan struct {
	Schema  string         `json:"schema"`
	Version int            `json:"version"`
	JobID   string         `json:"job_id"`
	Canvas  ChrononCanvas  `json:"canvas"`
	Layers  []ChrononLayer `json:"layers"`
	Output  ChrononOutput  `json:"output"`
}

// ChrononAsset is the content-addressed queue asset reference the worker
// materializes by hash into the workspace at LogicalPath.
type ChrononAsset struct {
	Hash        string `json:"hash"`
	LogicalPath string `json:"logical_path"`
}

// ChrononCompileResult is the compiled document plus the assets the queue
// job must carry so materialization resolves every layer reference.
type ChrononCompileResult struct {
	Plan   ChrononPlan
	Assets []ChrononAsset
}

// chrononOutputFor derives the chronon.render-plan.v1 output block from the
// plan's media contract. An empty contract keeps the legacy mp4/h264 default
// pinned by the cross-repo golden (no alpha, no pixel format); a resolved
// contract drives container/codec/pixel format so the renderer never guesses
// a codec per layer. An unknown contract id fails closed.
func chrononOutputFor(plan OverlayPlan) (ChrononOutput, error) {
	if strings.TrimSpace(plan.MediaContract) == "" {
		return ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"}, nil
	}
	contract, err := ResolveMediaContract(plan.MediaContract)
	if err != nil {
		return ChrononOutput{}, err
	}
	return ChrononOutput{
		Path:        "result." + contract.Container,
		Format:      contract.Container,
		Codec:       contract.Codec,
		PixelFormat: contract.PixelFormat,
	}, nil
}

// CompileChrononPlan compiles a validated semantic OverlayPlan into the
// concrete chronon.render-plan.v1 document and its queue asset references.
//
// Canvas, frame ranges and layer geometry are derived deterministically:
//
//	start_frame   = round(StartMs * fps / 1000)
//	duration      = frameAt(EndMs) - frameAt(StartMs)
//	duration_frames = frameAt(max EndMs over all items)
//
// Template mapping is table-driven (templateRegistry); per-item Params may
// override fit/position/box_width/box_height/preset. Layers preserve the
// OverlayPlan item order (background first, overlays on top).
func CompileChrononPlan(plan OverlayPlan) (ChrononCompileResult, error) {
	if err := plan.Validate(); err != nil {
		return ChrononCompileResult{}, err
	}
	renderer := strings.TrimSpace(plan.RendererVersion)
	if renderer != "" && renderer != "chronon" {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: renderer %q cannot compile to chronon.render-plan.v1", renderer)
	}
	if plan.Width <= 0 || plan.Height <= 0 || plan.FPS <= 0 {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: width, height and fps must be positive for chronon compilation")
	}
	if len(plan.Items) == 0 {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: cannot compile an empty item list to chronon")
	}

	fps := plan.FPS
	frameAtMS := func(ms int64) int64 {
		return int64(math.Round(float64(ms) * float64(fps) / 1000.0))
	}
	frameAtUS := func(us int64) int64 {
		return int64(math.Round(float64(us) * float64(fps) / 1_000_000.0))
	}
	// itemFrameRange returns the item's [start, end) in integer frames from
	// its canonical timing: integer microseconds when present, else the legacy
	// millisecond projection. The compiler never estimates or re-derives
	// timing — Chronon receives exact, PipelineGen-owned frames.
	itemFrameRange := func(item OverlayItem) (int64, int64) {
		if item.DurationUS > 0 {
			return frameAtUS(item.StartUS), frameAtUS(item.StartUS + item.DurationUS)
		}
		return frameAtMS(item.StartMs), frameAtMS(item.EndMs)
	}
	itemEndUS := func(item OverlayItem) int64 {
		if item.DurationUS > 0 {
			return item.StartUS + item.DurationUS
		}
		return item.EndMs * 1000
	}

	var maxEndUS int64
	for _, item := range plan.Items {
		if end := itemEndUS(item); end > maxEndUS {
			maxEndUS = end
		}
	}
	if maxEndUS <= 0 {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: no item has a positive end time")
	}

	layers := make([]ChrononLayer, 0, len(plan.Items))
	seenAssets := make(map[string]string) // sha256 -> logical path
	var assets []ChrononAsset
	needsFont := false
	// Auto-layout candidates: image layers whose semantic position is a
	// string slot (not an explicit numeric position). Resolved after the
	// loop by layoutImages with collision avoidance.
	var layoutCandidates []imageLayoutCandidate
	for index, item := range plan.Items {
		spec, ok := templateRegistry[item.TemplateID]
		if !ok {
			return ChrononCompileResult{}, fmt.Errorf("overlay plan: template %q is not a chronon-compilable template", item.TemplateID)
		}
		// Every semantic entity must terminate in a canonical primitive:
		// a template without one is a vocabulary bug, never a silent render.
		if spec.Primitive == "" {
			return ChrononCompileResult{}, fmt.Errorf("overlay plan: template %q does not terminate in a canonical primitive (text/image/video/shape)", item.TemplateID)
		}
		// Asset-driven primitives (Image / Video) must resolve an asset: a
		// missing ref, or a ref with neither URL nor content hash, is a hard
		// error (missing-image fail-closed), never a blank or garbage layer.
		// A URL-only or hash-only ref is legitimate (the worker materializes
		// it and computes the missing half).
		if spec.Primitive == PrimitiveImage || spec.Primitive == PrimitiveVideo {
			if len(item.AssetRefs) == 0 {
				return ChrononCompileResult{}, fmt.Errorf("overlay plan: item %q (%s) requires an asset", item.ID, spec.Primitive)
			}
			if strings.TrimSpace(item.AssetRefs[0].URL) == "" && strings.TrimSpace(item.AssetRefs[0].SHA256) == "" {
				return ChrononCompileResult{}, fmt.Errorf("overlay plan: item %q (%s) requires a resolvable asset (url or content hash)", item.ID, spec.Primitive)
			}
		}
		startFrame, endFrame := itemFrameRange(item)
		// The preset is the ONE editorial decision PipelineGen owns: resolved
	// through the SemanticOverlayResolver (semantic_role → Chronon preset),
	// never from a hard-coded geometry map. Preset-less primitives
	// (backgrounds, shapes, effects) resolve to an empty preset.
	preset, _ := DefaultSemanticOverlayResolver.PresetFor(item.TemplateID)
	if spec.Primitive == PrimitiveText && preset == "" {
		return ChrononCompileResult{}, fmt.Errorf("overlay plan: text template %q has no semantic_role → preset mapping", item.TemplateID)
	}
	layer := ChrononLayer{
			ID:             item.ID,
			Type:           spec.LayerType,
			Preset:         preset,
			Fit:            spec.Fit,
			BoxWidth:       spec.BoxWidth,
			BoxHeight:      spec.BoxHeight,
			Position:       spec.Position,
			StartFrame:     startFrame,
			DurationFrames: endFrame - startFrame,
			BlendMode:      spec.BlendMode,
			Opacity:        spec.Opacity,
			Loop:           spec.Loop,
		}
		if layer.DurationFrames <= 0 {
			return ChrononCompileResult{}, fmt.Errorf("overlay plan: item %q compiles to a non-positive frame range", item.ID)
		}
		if strings.TrimSpace(item.Text) != "" {
			layer.Text = item.Text
		}
		// Text layers carry no font / font_size: Chronon's VisualPresetRegistry
		// owns the canonical font asset (font_asset) and size via StyleResolver.
		// PipelineGen only flags that the plan needs a text font so the queue
		// carries the materialization dependency below (one entry per plan).
		if spec.Primitive == PrimitiveText {
			needsFont = true
		}
		// A FullCanvas template (BACKGROUND / VIDEO_BACKGROUND) spans the
		// full canvas for the whole clip.
		if spec.FullCanvas {
			layer.BoxWidth = plan.Width
			layer.BoxHeight = plan.Height
			layer.StartFrame = 0
			layer.DurationFrames = frameAtUS(maxEndUS)
		}
		// Per-item params override template defaults (fit/position/box).
		if v, ok := paramString(item.Params, "fit"); ok {
			layer.Fit = v
		}
		if v, ok := paramPosition(item.Params, "position"); ok {
			layer.Position = v
		}
		if v, ok := paramInt(item.Params, "box_width"); ok {
			layer.BoxWidth = v
		}
		if v, ok := paramInt(item.Params, "box_height"); ok {
			layer.BoxHeight = v
		}
		if v, ok := paramString(item.Params, "preset"); ok {
			layer.Preset = v
		}
		if v, ok := paramString(item.Params, "blend_mode"); ok {
			layer.BlendMode = v
		}
		if v, ok := paramFloatOpt(item.Params, "opacity"); ok {
			layer.Opacity = v
		}
		if v, ok := paramBool(item.Params, "loop"); ok {
			layer.Loop = v
		}
		// Semantic slot intent (string position) on an image layer: defer to
		// the collision-avoiding layout pass (layoutImages). Explicit numeric
		// positions win; template defaults stay untouched (legacy fixtures
		// compile identically). Captured after box overrides so the slot is
		// sized by the final box.
		if pos, ok := paramString(item.Params, "position"); ok && spec.Primitive == PrimitiveImage && !spec.FullCanvas {
			layer.Position = nil
			layoutCandidates = append(layoutCandidates, imageLayoutCandidate{
				layerIndex: index,
				slot:       semanticSlotFor(pos),
				boxW:       layer.BoxWidth,
				boxH:       layer.BoxHeight,
				priority:   paramFloat(item.Params, "priority"),
				startFrame: layer.StartFrame,
				endFrame:   layer.StartFrame + layer.DurationFrames,
			})
		}
		// Per-item animation override: Params["animation"]["preset"] names
		// the motion preset Chronon applies to the layer.
		if anim, ok := paramAnimation(item.Params, "animation"); ok {
			layer.Animation = anim
		}
		// The Shape primitive fills the layer with its RGBA color; Params
		// may override the template default.
		if spec.Primitive == PrimitiveShape {
			if c, ok := paramColor(item.Params, "color"); ok {
				layer.Color = c
			} else {
				layer.Color = spec.Color
			}
		}
		// Project the item's first asset into the layer reference and the
		// queue asset list (content-addressed by SHA-256). The Video
		// primitive references `source`; every other primitive uses `asset`.
		if len(item.AssetRefs) > 0 {
			ref := item.AssetRefs[0]
			logical := logicalAssetPath(ref.URL)
			if spec.Primitive == PrimitiveVideo {
				layer.Source = logical
			} else {
				layer.Asset = logical
			}
			if ref.SHA256 != "" {
				if _, dup := seenAssets[ref.SHA256]; !dup {
					seenAssets[ref.SHA256] = logical
					assets = append(assets, ChrononAsset{Hash: ref.SHA256, LogicalPath: logical})
				}
			}
		}
		layers = append(layers, layer)
	}
	// Resolve semantic image slots with collision avoidance. Deterministic:
	// priority desc, then plan order; explicit numeric positions untouched.
	layoutImages(layers, plan.Width, plan.Height, layoutCandidates)

	// Any plan with text layers carries the canonical font as a queue asset
	// (content-addressed, deduped against item assets) so the worker can
	// materialize the bytes Chronon's preset font_asset resolves. Plans with
	// no text layers (e.g. a bare VIDEO_BACKGROUND) do not carry it.
	if needsFont {
		if _, dup := seenAssets[GoldenFontHash]; !dup {
			seenAssets[GoldenFontHash] = CanonicalTextFontPath
			assets = append(assets, ChrononAsset{Hash: GoldenFontHash, LogicalPath: CanonicalTextFontPath})
		}
	}

	output, err := chrononOutputFor(plan)
	if err != nil {
		return ChrononCompileResult{}, err
	}
	return ChrononCompileResult{
		Plan: ChrononPlan{
			Schema:  ChrononSchema,
			Version: ChrononVersion,
			JobID:   plan.PlanID,
			Canvas: ChrononCanvas{
				Width:          plan.Width,
				Height:         plan.Height,
				FPS:            fps,
				DurationFrames: frameAtUS(maxEndUS),
			},
			Layers: layers,
			Output: output,
		},
		Assets: assets,
	}, nil
}

// Marshal returns the compiled plan as stable JSON.
func (c ChrononCompileResult) Marshal() ([]byte, error) {
	b, err := json.Marshal(c.Plan)
	if err != nil {
		return nil, fmt.Errorf("chronon compile: marshal plan: %w", err)
	}
	return b, nil
}

// logicalAssetPath derives the workspace-relative logical path for an asset
// URL. Assets land under the workspace assets root (the worker materializes
// them there and the plan references resolve relative to it).
func logicalAssetPath(url string) string {
	base := path.Base(strings.TrimSpace(url))
	if base == "." || base == "/" || base == "" {
		return "assets/asset"
	}
	return "assets/" + base
}
