// Package overlays — golden_content.go pins the Golden Content Suite: the
// reference workloads that certify Chronon renders CONTENT correctly (what
// appears and when), not just that an MP4 comes out. Each scenario is a
// semantic OverlayPlan twin of a RenderingGen golden job, exactly like
// GoldenOverlayPlanV1/V2: compiling it must reproduce the deterministic
// chronon.render-plan.v1 document the RenderingGen worker executes.
//
// Suite (5s @ 30fps = 150 frames on 1280x720, unless noted):
//
//	Content01  Important Phrases  background.jpg + 2 IMPORTANT_PHRASE
//	Content02  Important Words    background.jpg + 4 kinetic IMPORTANT_WORD
//	Content03  Images             background.jpg + 3 IMAGE_OVERLAY
//	Content05  Mixed Content      phrase + keyword + image + light leak
//
// GOLDEN 04 (Light Leak) is certified in light_leak_test.go: the LIGHT_LEAK
// template + blend_mode/opacity/loop layer fields compile deterministically.
// Its RenderingGen golden fixture (golden-content-04-light-leak-job-v1.json)
// uses the light-leak asset hashes generated by
// RenderingGen/infra/e2e/gen-golden-content04-assets.py (see
// GoldenLightLeak01Hash / GoldenLightLeak02Hash).
//
// Deferred scenario (own milestone):
//
//	GOLDEN 06  Full Script Scene  script → content selection → OverlayPlan →
//	                             RenderingGen → MP4 → SHA256 → DB → Drive;
//	                             the PipelineGen-side chain already exists
//	                             (scripts.CompileOverlayPlan →
//	                             QueueRenderEnqueuer.EnqueueChrononPlan) and
//	                             is certified in the scripts package.
//
// The asset hashes are the deterministic fixtures already pinned by golden.go
// and golden_v2.go (generated by RenderingGen/infra/e2e/gen-golden-assets.py /
// gen-golden-v2-assets.py). Reusing them keeps the content suite byte-aligned
// with the existing cross-repo golden invariants.
package overlays

// ── Content01 — Important Phrases ─────────────────────────────────────────
//
// background.jpg + two important phrases. Font and size are Chronon-owned
// (VisualPresetRegistry → StyleResolver): PipelineGen emits no font/font_size
// regardless of headline length.

// GoldenOverlayPlanContent01Phrases is the semantic instruction set for the
// Important Phrases content scenario.
func GoldenOverlayPlanContent01Phrases() OverlayPlan {
	return OverlayPlan{
		SchemaVersion:   SchemaVersionPlan,
		PlanID:          "golden-content-01-phrases",
		VideoID:         "video-golden-content-01-phrases",
		ProjectID:       "golden-content",
		Width:           1280,
		Height:          720,
		FPS:             30,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "background",
				TemplateID: "BACKGROUND",
				StartMs:    0,
				EndMs:      5000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "background",
					URL:       "assets/background.jpg",
					SHA256:    GoldenBackgroundHash,
					MediaType: "image/jpeg",
				}},
			},
			{
				ID:         "important_phrase_1",
				TemplateID: "IMPORTANT_PHRASE",
				StartMs:    800,  // frame 24 @ 30fps
				EndMs:      2400, // frame 72 @ 30fps
				Text:       "A MAJOR CHANGE",
			},
			{
				ID:         "important_phrase_2",
				TemplateID: "IMPORTANT_PHRASE",
				StartMs:    3000, // frame 90 @ 30fps
				EndMs:      4800, // frame 144 @ 30fps
				Text:       "THIS CHANGES EVERYTHING",
			},
		},
	}
}

// GoldenChrononPlanContent01Phrases is the exact chronon.render-plan.v1
// document Content01 must compile to.
var GoldenChrononPlanContent01Phrases = ChrononPlan{
	Schema:  ChrononSchema,
	Version: ChrononVersion,
	JobID:   "golden-content-01-phrases",
	Canvas: ChrononCanvas{
		Width:          1280,
		Height:         720,
		FPS:            30,
		DurationFrames: 150,
	},
	Layers: []ChrononLayer{
		{
			ID:             "background",
			Type:           "image",
			Asset:          "assets/background.jpg",
			BoxWidth:       1280,
			BoxHeight:      720,
			Fit:            "cover",
			StartFrame:     0,
			DurationFrames: 150,
		},
		{
			ID:             "important_phrase_1",
			Text:           "A MAJOR CHANGE",
			Preset:         "caption_card",
			StartFrame:     24,
			DurationFrames: 48,
		},
		{
			ID:             "important_phrase_2",
			Text:           "THIS CHANGES EVERYTHING",
			Preset:         "caption_card",
			StartFrame:     90,
			DurationFrames: 54,
		},
	},
	Output: ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"},
}

// GoldenChrononAssetsContent01Phrases are the content-addressed queue assets
// Content01 carries (background + the canonical font for the text layers).
var GoldenChrononAssetsContent01Phrases = []ChrononAsset{
	{Hash: GoldenBackgroundHash, LogicalPath: "assets/background.jpg"},
	{Hash: GoldenFontHash, LogicalPath: "assets/fonts/DejaVuSans.ttf"},
}

// ── Content02 — Important Words ───────────────────────────────────────────
//
// background.jpg + four kinetic words, each carrying its canonical motion
// preset. Every word renders at the active_word_pop preset's default size.

// GoldenOverlayPlanContent02Words is the semantic instruction set for the
// Important Words content scenario.
func GoldenOverlayPlanContent02Words() OverlayPlan {
	return OverlayPlan{
		SchemaVersion:   SchemaVersionPlan,
		PlanID:          "golden-content-02-words",
		VideoID:         "video-golden-content-02-words",
		ProjectID:       "golden-content",
		Width:           1280,
		Height:          720,
		FPS:             30,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "background",
				TemplateID: "BACKGROUND",
				StartMs:    0,
				EndMs:      5000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "background",
					URL:       "assets/background.jpg",
					SHA256:    GoldenBackgroundHash,
					MediaType: "image/jpeg",
				}},
			},
			{
				ID:         "important_word_1",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    500, // frame 15 @ 30fps
				EndMs:      1500,
				Text:       "ELON MUSK",
				Params:     map[string]any{"animation": map[string]any{"preset": "scale_drop"}},
			},
			{
				ID:         "important_word_2",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    1500, // frame 45 @ 30fps
				EndMs:      2500,
				Text:       "TESLA",
				Params:     map[string]any{"animation": map[string]any{"preset": "fade_in"}},
			},
			{
				ID:         "important_word_3",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    2500, // frame 75 @ 30fps
				EndMs:      3500,
				Text:       "$10 BILLION",
				Params:     map[string]any{"animation": map[string]any{"preset": "fade_shift_vertical"}},
			},
			{
				ID:         "important_word_4",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    3500, // frame 105 @ 30fps
				EndMs:      4500,
				Text:       "OPENAI",
				Params:     map[string]any{"animation": map[string]any{"preset": "scale_drop"}},
			},
		},
	}
}

// GoldenChrononPlanContent02Words is the exact chronon.render-plan.v1
// document Content02 must compile to, animations included.
var GoldenChrononPlanContent02Words = ChrononPlan{
	Schema:  ChrononSchema,
	Version: ChrononVersion,
	JobID:   "golden-content-02-words",
	Canvas: ChrononCanvas{
		Width:          1280,
		Height:         720,
		FPS:            30,
		DurationFrames: 150,
	},
	Layers: []ChrononLayer{
		{
			ID:             "background",
			Type:           "image",
			Asset:          "assets/background.jpg",
			BoxWidth:       1280,
			BoxHeight:      720,
			Fit:            "cover",
			StartFrame:     0,
			DurationFrames: 150,
		},
		{
			ID:             "important_word_1",
			Text:           "ELON MUSK",
			Preset:         "active_word_pop",
			StartFrame:     15,
			DurationFrames: 30,
			Animation:      &ChrononLayerAnimation{Preset: "scale_drop"},
		},
		{
			ID:             "important_word_2",
			Text:           "TESLA",
			Preset:         "active_word_pop",
			StartFrame:     45,
			DurationFrames: 30,
			Animation:      &ChrononLayerAnimation{Preset: "fade_in"},
		},
		{
			ID:             "important_word_3",
			Text:           "$10 BILLION",
			Preset:         "active_word_pop",
			StartFrame:     75,
			DurationFrames: 30,
			Animation:      &ChrononLayerAnimation{Preset: "fade_shift_vertical"},
		},
		{
			ID:             "important_word_4",
			Text:           "OPENAI",
			Preset:         "active_word_pop",
			StartFrame:     105,
			DurationFrames: 30,
			Animation:      &ChrononLayerAnimation{Preset: "scale_drop"},
		},
	},
	Output: ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"},
}

// GoldenChrononAssetsContent02Words are the content-addressed queue assets
// Content02 carries (background + the canonical font for the text layers).
var GoldenChrononAssetsContent02Words = []ChrononAsset{
	{Hash: GoldenBackgroundHash, LogicalPath: "assets/background.jpg"},
	{Hash: GoldenFontHash, LogicalPath: "assets/fonts/DejaVuSans.ttf"},
}

// ── Content03 — Images ────────────────────────────────────────────────────
//
// background.jpg + three contained image overlays with explicit numeric
// positions. Explicit positions are user intent and bypass the auto-layout
// pass, so the document pins the exact geometry.

// GoldenOverlayPlanContent03Images is the semantic instruction set for the
// Images content scenario.
func GoldenOverlayPlanContent03Images() OverlayPlan {
	return OverlayPlan{
		SchemaVersion:   SchemaVersionPlan,
		PlanID:          "golden-content-03-images",
		VideoID:         "video-golden-content-03-images",
		ProjectID:       "golden-content",
		Width:           1280,
		Height:          720,
		FPS:             30,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "background",
				TemplateID: "BACKGROUND",
				StartMs:    0,
				EndMs:      5000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "background",
					URL:       "assets/background.jpg",
					SHA256:    GoldenBackgroundHash,
					MediaType: "image/jpeg",
				}},
			},
			{
				ID:         "image_overlay_1",
				TemplateID: "IMAGE_OVERLAY",
				StartMs:    800,  // frame 24 @ 30fps
				EndMs:      3200, // frame 96 @ 30fps
				Params: map[string]any{
					"position":   []any{380, 0},
					"box_width":  300,
					"box_height": 300,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "globe",
					URL:       "assets/overlay_globe.png",
					SHA256:    GoldenGlobeHash,
					MediaType: "image/png",
				}},
			},
			{
				ID:         "image_overlay_2",
				TemplateID: "IMAGE_OVERLAY",
				StartMs:    2000, // frame 60 @ 30fps
				EndMs:      4400, // frame 132 @ 30fps
				Params: map[string]any{
					"position":   []any{840, 380},
					"box_width":  300,
					"box_height": 300,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "chart",
					URL:       "assets/overlay_chart.png",
					SHA256:    GoldenChartHash,
					MediaType: "image/png",
				}},
			},
			{
				ID:         "image_overlay_3",
				TemplateID: "IMAGE_OVERLAY",
				StartMs:    3400, // frame 102 @ 30fps
				EndMs:      5000, // frame 150 @ 30fps
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "apple",
					URL:       "assets/apple.png",
					SHA256:    GoldenAppleHash,
					MediaType: "image/png",
				}},
			},
		},
	}
}

// GoldenChrononPlanContent03Images is the exact chronon.render-plan.v1
// document Content03 must compile to. image_overlay_3 keeps the canonical
// IMAGE_OVERLAY geometry (260×260 contain at [380,0]); the first two carry
// explicit 300×300 boxes.
var GoldenChrononPlanContent03Images = ChrononPlan{
	Schema:  ChrononSchema,
	Version: ChrononVersion,
	JobID:   "golden-content-03-images",
	Canvas: ChrononCanvas{
		Width:          1280,
		Height:         720,
		FPS:            30,
		DurationFrames: 150,
	},
	Layers: []ChrononLayer{
		{
			ID:             "background",
			Type:           "image",
			Asset:          "assets/background.jpg",
			BoxWidth:       1280,
			BoxHeight:      720,
			Fit:            "cover",
			StartFrame:     0,
			DurationFrames: 150,
		},
		{
			ID:             "image_overlay_1",
			Asset:          "assets/overlay_globe.png",
			Preset:         "image_focus_in",
			BoxWidth:       300,
			BoxHeight:      300,
			Position:       []float64{380, 0},
			StartFrame:     24,
			DurationFrames: 72,
		},
		{
			ID:             "image_overlay_2",
			Asset:          "assets/overlay_chart.png",
			Preset:         "image_focus_in",
			BoxWidth:       300,
			BoxHeight:      300,
			Position:       []float64{840, 380},
			StartFrame:     60,
			DurationFrames: 72,
		},
		{
			ID:             "image_overlay_3",
			Asset:          "assets/apple.png",
			Preset:         "image_focus_in",
			StartFrame:     102,
			DurationFrames: 48,
		},
	},
	Output: ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"},
}

// GoldenChrononAssetsContent03Images are the content-addressed queue assets
// Content03 carries. There are no text layers, so the canonical font is NOT
// projected: the plan renders images only.
var GoldenChrononAssetsContent03Images = []ChrononAsset{
	{Hash: GoldenBackgroundHash, LogicalPath: "assets/background.jpg"},
	{Hash: GoldenGlobeHash, LogicalPath: "assets/overlay_globe.png"},
	{Hash: GoldenChartHash, LogicalPath: "assets/overlay_chart.png"},
	{Hash: GoldenAppleHash, LogicalPath: "assets/apple.png"},
}

// ── Content05 — Mixed Content ─────────────────────────────────────────────
//
// background.jpg + one phrase + one keyword + one image + one light leak.
// The item order IS the z-index (bottom → top), so the full mixed hierarchy
// is defined and deterministic — never map/array-order dependent:
//
//	background       z=0   (BACKGROUND, full canvas)
//	image_overlay    z=20  (IMAGE_OVERLAY, contained right)
//	light_leak       z=40  (LIGHT_LEAK, screen blend over the background)
//	important_word   z=80  (IMPORTANT_WORD, kinetic)
//	important_phrase z=100 (IMPORTANT_PHRASE, headline on top)

// GoldenOverlayPlanContent05Mixed is the semantic instruction set for the
// Mixed Content scenario (phrase + keyword + image + light leak).
func GoldenOverlayPlanContent05Mixed() OverlayPlan {
	return OverlayPlan{
		SchemaVersion:   SchemaVersionPlan,
		PlanID:          "golden-content-05-mixed",
		VideoID:         "video-golden-content-05-mixed",
		ProjectID:       "golden-content",
		Width:           1280,
		Height:          720,
		FPS:             30,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "background",
				TemplateID: "BACKGROUND",
				StartMs:    0,
				EndMs:      5000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "background",
					URL:       "assets/background.jpg",
					SHA256:    GoldenBackgroundHash,
					MediaType: "image/jpeg",
				}},
			},
			{
				ID:         "image_overlay",
				TemplateID: "IMAGE_OVERLAY",
				StartMs:    2200, // frame 66 @ 30fps
				EndMs:      4200, // frame 126 @ 30fps
				Params: map[string]any{
					"position":   []any{840, 380},
					"box_width":  300,
					"box_height": 300,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "globe",
					URL:       "assets/overlay_globe.png",
					SHA256:    GoldenGlobeHash,
					MediaType: "image/png",
				}},
			},
			{
				ID:         "light_leak",
				TemplateID: "LIGHT_LEAK",
				StartMs:    800,  // frame 24 @ 30fps
				EndMs:      2600, // frame 78 @ 30fps
				Params: map[string]any{
					"blend_mode": "screen",
					"opacity":    0.5,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "leak-1",
					URL:       "assets/light_leak_01.mp4",
					SHA256:    GoldenLightLeak01Hash,
					MediaType: "video/mp4",
				}},
			},
			{
				ID:         "important_word",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    1000, // frame 30 @ 30fps
				EndMs:      2000, // frame 60 @ 30fps
				Text:       "-20%",
			},
			{
				ID:         "important_phrase",
				TemplateID: "IMPORTANT_PHRASE",
				StartMs:    800,  // frame 24 @ 30fps
				EndMs:      2800, // frame 84 @ 30fps
				Text:       "A MASSIVE DROP",
			},
		},
	}
}

// GoldenChrononPlanContent05Mixed is the exact chronon.render-plan.v1
// document Content05 must compile to (z-index = layer order, bottom → top).
var GoldenChrononPlanContent05Mixed = ChrononPlan{
	Schema:  ChrononSchema,
	Version: ChrononVersion,
	JobID:   "golden-content-05-mixed",
	Canvas: ChrononCanvas{
		Width:          1280,
		Height:         720,
		FPS:            30,
		DurationFrames: 150,
	},
	Layers: []ChrononLayer{
		{
			ID:             "background",
			Type:           "image",
			Asset:          "assets/background.jpg",
			BoxWidth:       1280,
			BoxHeight:      720,
			Fit:            "cover",
			StartFrame:     0,
			DurationFrames: 150,
		},
		{
			ID:             "image_overlay",
			Asset:          "assets/overlay_globe.png",
			Preset:         "image_focus_in",
			BoxWidth:       300,
			BoxHeight:      300,
			Position:       []float64{840, 380},
			StartFrame:     66,
			DurationFrames: 60,
		},
		{
			ID:             "light_leak",
			Type:           "video",
			Source:         "assets/light_leak_01.mp4",
			Fit:            "cover",
			StartFrame:     24,
			DurationFrames: 54,
			BlendMode:      "screen",
			Opacity:        0.5,
		},
		{
			ID:             "important_word",
			Text:           "-20%",
			Preset:         "active_word_pop",
			StartFrame:     30,
			DurationFrames: 30,
		},
		{
			ID:             "important_phrase",
			Text:           "A MASSIVE DROP",
			Preset:         "caption_card",
			StartFrame:     24,
			DurationFrames: 60,
		},
	},
	Output: ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"},
}

// GoldenChrononAssetsContent05Mixed are the content-addressed queue assets
// Content05 carries (background + globe image + light-leak clip + the
// canonical font for the two text layers).
var GoldenChrononAssetsContent05Mixed = []ChrononAsset{
	{Hash: GoldenBackgroundHash, LogicalPath: "assets/background.jpg"},
	{Hash: GoldenGlobeHash, LogicalPath: "assets/overlay_globe.png"},
	{Hash: GoldenLightLeak01Hash, LogicalPath: "assets/light_leak_01.mp4"},
	{Hash: GoldenFontHash, LogicalPath: "assets/fonts/DejaVuSans.ttf"},
}
