// Package overlays — golden.go pins the cross-repo golden workload:
// PipelineGen's semantic instructions (GoldenOverlayPlanV1) must compile to
// exactly the chronon.render-plan.v1 document RenderingGen executes as
// GoldenOverlayJobV1 (RenderingGen/testdata/golden/golden-overlay-job-v1.json
// + renderinggen/internal/chronon/golden.go).
//
// The workload (5s @ 30fps = 150 frames on 1280x720):
//
//	background         background.jpg   cover, full canvas      f0-149
//	IMPORTANT_PHRASE   "QUESTO CAMBIA TUTTO" clean_slide_up       f20-60
//	IMPORTANT_WORD     "APPLE"           phrase_word_reveal       f65-95
//	IMAGE_OVERLAY      apple.png         contain, right          f90-135
//
// The two asset hashes are the deterministic fixtures generated by
// RenderingGen/infra/e2e/gen-golden-assets.py. Changing them breaks the
// cross-repo golden invariant on purpose: the fixture and the semantic plan
// must always agree.
package overlays

const (
	// GoldenBackgroundHash and GoldenAppleHash are the SHA-256 of the
	// deterministic fixtures under RenderingGen/testdata/golden/.
	GoldenBackgroundHash = "52209ee36928dba960583179922a54acf045d52d44c3128c517425d4baaa4f78"
	GoldenAppleHash      = "ed873745e76173b66999c63546770d9f1426a2189515149176c67637e99a62d6"
)

// GoldenOverlayPlanV1 is the canonical semantic instruction set for the
// golden workload. It is the PipelineGen-side twin of RenderingGen's
// GoldenOverlayJobV1: compiling it must reproduce the exact
// chronon.render-plan.v1 document the RenderingGen golden carries.
func GoldenOverlayPlanV1() OverlayPlan {
	return OverlayPlan{
		SchemaVersion: SchemaVersionPlan,
		PlanID:        "golden-overlay-v1",
		VideoID:       "video-golden-overlay-v1",
		ProjectID:     "golden",
		Width:         1280,
		Height:        720,
		FPSNum:        30, FPSDen: 1,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "background",
				TemplateID: "BACKGROUND",
				StartMs:    0,
				EndMs:      5000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "background",
					URL:       "assets/background.jpg",
					SHA256:    GoldenBackgroundHash,
					MediaType: "image/jpeg",
				}},
			},
			{
				ID:         "important_phrase",
				TemplateID: "IMPORTANT_PHRASE",
				StartMs:    667,  // frame 20 @ 30fps (20/30*1000 = 666.67)
				EndMs:      2033, // frame 61 @ 30fps (61/30*1000 = 2033.33)
				Text:       "QUESTO CAMBIA TUTTO",
			},
			{
				ID:         "important_word",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    2167, // frame 65 @ 30fps (65/30*1000 = 2166.67)
				EndMs:      3200, // frame 96 @ 30fps (96/30*1000 = 3200.00)
				Text:       "APPLE",
			},
			{
				ID:         "image_overlay",
				TemplateID: "IMAGE_OVERLAY",
				StartMs:    3000, // frame 90 @ 30fps
				EndMs:      4533, // frame 136 @ 30fps (136/30*1000 = 4533.33)
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "apple",
					URL:       "assets/apple.png",
					SHA256:    GoldenAppleHash,
					MediaType: "image/png",
				}},
			},
		},
	}
}

// GoldenChrononPlanV1 is the exact chronon.render-plan.v1 document the golden
// semantic plan must compile to. It mirrors RenderingGen's
// GoldenOverlayJobV1 render_plan field byte-for-byte, including field order,
// so the cross-repo golden invariant is a literal document comparison.
var GoldenChrononPlanV1 = ChrononPlan{
	Schema:  ChrononSchema,
	Version: ChrononVersion,
	JobID:   "golden-overlay-v1",
	Canvas: ChrononCanvas{
		Width:  1280,
		Height: 720,
		FPSNum: 30, FPSDen: 1,
		DurationFrames: 150,
	},
	Layers: []ChrononLayer{
		{
			ID:             "background",
			Type:           "image",
			Asset:          "assets/background.jpg",
			BoxWidth:       1280,
			BoxHeight:      720,
			Fit:            "cover",
			StartFrame:     0,
			DurationFrames: 150,
		},
		{
			ID:             "important_phrase",
			Type:           "text",
			FontAsset:      &ChrononFontAsset{Asset: CanonicalTextFontPath, Family: "DejaVu Sans", Weight: 700},
			Text:           "QUESTO CAMBIA TUTTO",
			Preset:         "fast_fade_through",
			StartFrame:     20,
			DurationFrames: 41,
		},
		{
			ID:             "important_word",
			Type:           "text",
			FontAsset:      &ChrononFontAsset{Asset: CanonicalTextFontPath, Family: "DejaVu Sans", Weight: 700},
			Text:           "APPLE",
			Preset:         "fast_fade_through",
			StartFrame:     65,
			DurationFrames: 31,
		},
		{
			ID:             "image_overlay",
			Type:           "image",
			Asset:          "assets/apple.png",
			Preset:         "image_slide_right",
			StartFrame:     90,
			DurationFrames: 46,
		},
	},
	Output: ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"},
}

// GoldenChrononAssetsV1 are the content-addressed queue assets the golden
// plan carries, matching the RenderingGen golden job's assets array (the
// font is required by every text layer).
var GoldenChrononAssetsV1 = []ChrononAsset{
	{Hash: GoldenBackgroundHash, LogicalPath: "assets/background.jpg"},
	{Hash: GoldenAppleHash, LogicalPath: "assets/apple.png"},
	{Hash: GoldenFontHash, LogicalPath: "assets/fonts/DejaVuSans.ttf"},
}

// ── GoldenOverlayJobV2: the universal benchmark workload ────────────────
//
// The permanent benchmark/regression fixture for the whole chain
// (SoftwareBackend / VulkanBackend / CLI / daemon IPC / cold-warm cache /
// CPU / GPU / future Chronon and PipelineGen versions). 8s @ 30fps = 240
// frames on 1280x720, exercising the full semantic vocabulary and every
// canonical primitive:
//
//	VIDEO_BACKGROUND    background.mp4      cover, full canvas   f0-239  (Video)
//	IMPORTANT_PHRASE×2  modern phrase preset + animation          (Text)
//	IMPORTANT_WORD×2    modern word preset   + animation          (Text)
//	IMAGE_OVERLAY×2     contain, popup                            (Image)
//	LOGO                contain, corner                           (Image)
//	+ 4 layer animations (fade_in / scale_in / slide_up / fade_in)
//
// The asset hashes are the deterministic fixtures generated by
// RenderingGen/infra/e2e/gen-golden-v2-assets.py. Changing them breaks the
// cross-repo golden invariant on purpose: fixture, semantic plan and
// RenderingGen golden must always agree.
const (
	// GoldenBackgroundVideoHash is the SHA-256 of the deterministic 8s
	// 1280x720@30 background clip (RenderingGen/testdata/golden/background.mp4).
	GoldenBackgroundVideoHash = "11eeec4e47fb254dc6acc4b72405bf06f2ed7294cffa8b7a95ba76f1e8d9c70c"
	// GoldenGlobeHash is the SHA-256 of overlay_globe.png (IMAGE_OVERLAY 1).
	GoldenGlobeHash = "b7219a0c2f3f0c45f12d3b387332bd2cf0502205a6bb3fa0beca542de6da1939"
	// GoldenChartHash is the SHA-256 of overlay_chart.png (IMAGE_OVERLAY 2).
	GoldenChartHash = "efb77ea94d50f178e970841f641be7f4efc59837d5628fec2f4bdb6e88a9f73a"
	// GoldenLogoHash is the SHA-256 of logo_pulse.png (LOGO).
	GoldenLogoHash = "15d17403acaf45cdeeb9dad6a6c88e3b5f686b3ee1961cc97815b4830d3b981f"
	// GoldenLightLeak01Hash is the SHA-256 of the deterministic 2.0s
	// light_leak_01.mp4 warm-sweep clip (GOLDEN 04 / GOLDEN 05).
	GoldenLightLeak01Hash = "af77ec5de4aa43b0e573b7cc2e5a983f95ffb9388c3fd1ac53838a345a74abc6"
	// GoldenLightLeak02Hash is the SHA-256 of the deterministic 1.2s
	// light_leak_02.mp4 cool-flare clip (GOLDEN 04).
	GoldenLightLeak02Hash = "f1362c42c21e5675bda3fde7094a369455df1153d080887276e5c616f77d4660"
)

// GoldenOverlayPlanV2 is the canonical semantic instruction set for the
// universal benchmark workload — the PipelineGen-side twin of RenderingGen's
// GoldenOverlayJobV2: compiling it must reproduce the exact
// chronon.render-plan.v1 document the RenderingGen golden carries, including
// the layer animations.
func GoldenOverlayPlanV2() OverlayPlan {
	return OverlayPlan{
		SchemaVersion: SchemaVersionPlan,
		PlanID:        "golden-overlay-v2",
		VideoID:       "video-golden-overlay-v2",
		ProjectID:     "golden",
		Width:         1280,
		Height:        720,
		FPSNum:        30, FPSDen: 1,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "background_video",
				TemplateID: "VIDEO_BACKGROUND",
				StartMs:    0,
				EndMs:      8000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "background_video",
					URL:       "assets/background.mp4",
					SHA256:    GoldenBackgroundVideoHash,
					MediaType: "video/mp4",
				}},
			},
			{
				ID:         "important_phrase_1",
				TemplateID: "IMPORTANT_PHRASE",
				StartMs:    800,  // frame 24 @ 30fps
				EndMs:      3600, // frame 108 @ 30fps
				Text:       "IL FUTURO È ADESSO",
				Params:     map[string]any{"animation": map[string]any{"preset": "fade_in"}},
			},
			{
				ID:         "important_word_1",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    800,  // frame 24 @ 30fps
				EndMs:      3600, // frame 108 @ 30fps
				Text:       "VELOCITÀ",
				Params:     map[string]any{"animation": map[string]any{"preset": "scale_drop"}},
			},
			{
				ID:         "image_overlay_1",
				TemplateID: "IMAGE_OVERLAY",
				StartMs:    800,  // frame 24 @ 30fps
				EndMs:      5200, // frame 156 @ 30fps
				Params: map[string]any{
					"position":   []any{380, 0},
					"box_width":  300,
					"box_height": 300,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "globe",
					URL:       "assets/overlay_globe.png",
					SHA256:    GoldenGlobeHash,
					MediaType: "image/png",
				}},
			},
			{
				ID:         "important_phrase_2",
				TemplateID: "IMPORTANT_PHRASE",
				StartMs:    4400, // frame 132 @ 30fps
				EndMs:      7200, // frame 216 @ 30fps
				Text:       "CAMBIARE IL MERCATO",
				Params:     map[string]any{"animation": map[string]any{"preset": "fade_shift_vertical"}},
			},
			{
				ID:         "important_word_2",
				TemplateID: "IMPORTANT_WORD",
				StartMs:    4400, // frame 132 @ 30fps
				EndMs:      7200, // frame 216 @ 30fps
				Text:       "POTENZA",
				Params:     map[string]any{"animation": map[string]any{"preset": "fade_in"}},
			},
			{
				ID:         "image_overlay_2",
				TemplateID: "IMAGE_OVERLAY",
				StartMs:    4000, // frame 120 @ 30fps
				EndMs:      7600, // frame 228 @ 30fps
				Params: map[string]any{
					"position":   []any{840, 380},
					"box_width":  300,
					"box_height": 300,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "chart",
					URL:       "assets/overlay_chart.png",
					SHA256:    GoldenChartHash,
					MediaType: "image/png",
				}},
			},
			{
				ID:         "logo",
				TemplateID: "LOGO",
				StartMs:    0,
				EndMs:      8000,
				Params: map[string]any{
					"position":   []any{1060, 40},
					"box_width":  160,
					"box_height": 160,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "logo",
					URL:       "assets/logo_pulse.png",
					SHA256:    GoldenLogoHash,
					MediaType: "image/png",
				}},
			},
		},
	}
}

// GoldenChrononPlanV2 is the exact chronon.render-plan.v1 document the v2
// golden semantic plan must compile to. It mirrors RenderingGen's
// GoldenOverlayJobV2 render_plan field, including field order, so the
// cross-repo golden invariant is a literal document comparison.
var GoldenChrononPlanV2 = ChrononPlan{
	Schema:  ChrononSchema,
	Version: ChrononVersion,
	JobID:   "golden-overlay-v2",
	Canvas: ChrononCanvas{
		Width:  1280,
		Height: 720,
		FPSNum: 30, FPSDen: 1,
		DurationFrames: 240,
	},
	Layers: []ChrononLayer{
		{
			ID:             "background_video",
			Type:           "video",
			Source:         "assets/background.mp4",
			BoxWidth:       1280,
			BoxHeight:      720,
			Fit:            "cover",
			StartFrame:     0,
			DurationFrames: 240,
		},
		{
			ID:             "important_phrase_1",
			Type:           "text",
			FontAsset:      &ChrononFontAsset{Asset: CanonicalTextFontPath, Family: "DejaVu Sans", Weight: 700},
			Text:           "IL FUTURO È ADESSO",
			Preset:         "phrase_word_reveal",
			StartFrame:     24,
			DurationFrames: 84,
			Animation:      &ChrononLayerAnimation{Preset: "fade_in"},
		},
		{
			ID:             "important_word_1",
			Type:           "text",
			FontAsset:      &ChrononFontAsset{Asset: CanonicalTextFontPath, Family: "DejaVu Sans", Weight: 700},
			Text:           "VELOCITÀ",
			Preset:         "fast_fade_through",
			StartFrame:     24,
			DurationFrames: 84,
			Animation:      &ChrononLayerAnimation{Preset: "scale_drop"},
		},
		{
			ID:             "image_overlay_1",
			Type:           "image",
			Asset:          "assets/overlay_globe.png",
			Preset:         "image_fast_fade",
			BoxWidth:       300,
			BoxHeight:      300,
			Position:       []float64{380, 0},
			StartFrame:     24,
			DurationFrames: 132,
		},
		{
			ID:             "important_phrase_2",
			Type:           "text",
			FontAsset:      &ChrononFontAsset{Asset: CanonicalTextFontPath, Family: "DejaVu Sans", Weight: 700},
			Text:           "CAMBIARE IL MERCATO",
			Preset:         "fast_fade_through",
			StartFrame:     132,
			DurationFrames: 84,
			Animation:      &ChrononLayerAnimation{Preset: "fade_shift_vertical"},
		},
		{
			ID:             "important_word_2",
			Type:           "text",
			FontAsset:      &ChrononFontAsset{Asset: CanonicalTextFontPath, Family: "DejaVu Sans", Weight: 700},
			Text:           "POTENZA",
			Preset:         "phrase_word_reveal",
			StartFrame:     132,
			DurationFrames: 84,
			Animation:      &ChrononLayerAnimation{Preset: "fade_in"},
		},
		{
			ID:             "image_overlay_2",
			Type:           "image",
			Asset:          "assets/overlay_chart.png",
			Preset:         "image_slide_right",
			BoxWidth:       300,
			BoxHeight:      300,
			Position:       []float64{840, 380},
			StartFrame:     120,
			DurationFrames: 108,
		},
		{
			ID:             "logo",
			Type:           "image",
			Asset:          "assets/logo_pulse.png",
			BoxWidth:       160,
			BoxHeight:      160,
			Fit:            "contain",
			Position:       []float64{1060, 40},
			StartFrame:     0,
			DurationFrames: 240,
		},
	},
	Output: ChrononOutput{Path: "result.mp4", Format: "mp4", Codec: "h264"},
}

// GoldenChrononAssetsV2 are the content-addressed queue assets the v2 golden
// plan carries, matching the RenderingGen golden job's assets array.
var GoldenChrononAssetsV2 = []ChrononAsset{
	{Hash: GoldenBackgroundVideoHash, LogicalPath: "assets/background.mp4"},
	{Hash: GoldenGlobeHash, LogicalPath: "assets/overlay_globe.png"},
	{Hash: GoldenChartHash, LogicalPath: "assets/overlay_chart.png"},
	{Hash: GoldenLogoHash, LogicalPath: "assets/logo_pulse.png"},
	{Hash: GoldenFontHash, LogicalPath: "assets/fonts/DejaVuSans.ttf"},
}
