// Package overlays — light_leak_test.go certifies the GOLDEN 04 light-leak
// compile contract: two composited light-leak layers project their blend
// mode, opacity, timing and loop/terminate behavior deterministically onto
// the chronon.render-plan.v1 document. The pixel blend itself is Chronon's
// job; PipelineGen owns the deterministic instruction the worker executes.
package overlays

import (
	"encoding/json"
	"reflect"
	"testing"
)

// lightLeakPlan builds the GOLDEN 04 scenario: background + two light leaks
// with distinct blend/opacity/timing/loop. Both leaks carry the real
// deterministic fixture hashes generated by
// RenderingGen/infra/e2e/gen-golden-content04-assets.py; the compile contract
// depends on the carried (hash, logical_path) pairs and the layer fields.
func lightLeakPlan() OverlayPlan {
	return OverlayPlan{
		SchemaVersion: SchemaVersionPlan,
		PlanID:        "golden-content-04-light-leak",
		VideoID:       "video-golden-content-04-light-leak",
		ProjectID:     "golden-content",
		Width:         1280,
		Height:        720,
		FPSNum:        30, FPSDen: 1,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "background",
				TemplateID: "BACKGROUND",
				StartMs:    0,
				EndMs:      5000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "background",
					URL:       "assets/background.jpg",
					SHA256:    GoldenBackgroundHash,
					MediaType: "image/jpeg",
				}},
			},
			{
				ID:         "light_leak_1",
				TemplateID: "LIGHT_LEAK",
				StartMs:    1200, // frame 36 @ 30fps
				EndMs:      3000, // frame 90 @ 30fps
				Params: map[string]any{
					"blend_mode": "screen",
					"opacity":    0.65,
					"loop":       false,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "leak-1",
					URL:       "assets/light_leak_01.mp4",
					SHA256:    GoldenLightLeak01Hash,
					MediaType: "video/mp4",
				}},
			},
			{
				ID:         "light_leak_2",
				TemplateID: "LIGHT_LEAK",
				StartMs:    3200, // frame 96 @ 30fps
				EndMs:      4400, // frame 132 @ 30fps
				Params: map[string]any{
					"blend_mode": "add",
					"opacity":    0.4,
					"loop":       true,
				},
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "leak-2",
					URL:       "assets/light_leak_02.mp4",
					SHA256:    GoldenLightLeak02Hash,
					MediaType: "video/mp4",
				}},
			},
		},
	}
}

// TestCompileLightLeakBlendOpacityTimingLoop certifies that two light-leak
// layers compile to video layers carrying their exact blend mode, opacity,
// frame timing and loop flag — deterministically and without touching the
// background layer.
func TestCompileLightLeakBlendOpacityTimingLoop(t *testing.T) {
	got, err := CompileChrononPlan(lightLeakPlan())
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Plan.Layers) != 3 {
		t.Fatalf("layers = %d, want background + 2 light leaks", len(got.Plan.Layers))
	}

	leak1 := got.Plan.Layers[1]
	if leak1.Type != "video" || leak1.Source != "assets/light_leak_01.mp4" {
		t.Fatalf("leak1 = type %q source %q, want video assets/light_leak_01.mp4", leak1.Type, leak1.Source)
	}
	if leak1.BlendMode != "screen" || leak1.Opacity != 0.65 || leak1.Loop {
		t.Fatalf("leak1 blend/opacity/loop = %q/%v/%v, want screen/0.65/false", leak1.BlendMode, leak1.Opacity, leak1.Loop)
	}
	if leak1.StartFrame != 36 || leak1.DurationFrames != 54 {
		t.Fatalf("leak1 timing = [%d,%d], want start 36 dur 54", leak1.StartFrame, leak1.DurationFrames)
	}

	leak2 := got.Plan.Layers[2]
	if leak2.Type != "video" || leak2.Source != "assets/light_leak_02.mp4" {
		t.Fatalf("leak2 = type %q source %q, want video assets/light_leak_02.mp4", leak2.Type, leak2.Source)
	}
	if leak2.BlendMode != "add" || leak2.Opacity != 0.4 || !leak2.Loop {
		t.Fatalf("leak2 blend/opacity/loop = %q/%v/%v, want add/0.4/true", leak2.BlendMode, leak2.Opacity, leak2.Loop)
	}
	if leak2.StartFrame != 96 || leak2.DurationFrames != 36 {
		t.Fatalf("leak2 timing = [%d,%d], want start 96 dur 36", leak2.StartFrame, leak2.DurationFrames)
	}
}

// TestCompileLightLeakDeterministic certifies the deterministic contract:
// the same plan compiles to identical layers (blend order, opacity and timing
// included) across repeated compiles — two render jobs of the same input are
// visually identical.
func TestCompileLightLeakDeterministic(t *testing.T) {
	a, err := CompileChrononPlan(lightLeakPlan())
	if err != nil {
		t.Fatal(err)
	}
	b, err := CompileChrononPlan(lightLeakPlan())
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(a.Plan, b.Plan) {
		aj, _ := json.Marshal(a.Plan)
		bj, _ := json.Marshal(b.Plan)
		t.Fatalf("light-leak plan is not deterministic:\n a=%s\n b=%s", aj, bj)
	}
}

// TestCompileLightLeakDefaults certifies the template defaults and the
// loop/terminate contract:
//   - no blend_mode param → the canonical "screen" default;
//   - no opacity param → no override carried (renderer default);
//   - no loop param → false (terminate at the source's end, never a stretch);
//   - explicit loop=true → the layer carries "loop": true.
func TestCompileLightLeakDefaults(t *testing.T) {
	plan := OverlayPlan{
		SchemaVersion: SchemaVersionPlan,
		PlanID:        "light-leak-defaults",
		VideoID:       "video-light-leak-defaults",
		ProjectID:     "golden-content",
		Width:         1280,
		Height:        720,
		FPSNum:        30, FPSDen: 1,
		RendererVersion: "chronon",
		Items: []OverlayItem{
			{
				ID:         "leak_default",
				TemplateID: "LIGHT_LEAK",
				StartMs:    0,
				EndMs:      2000,
				AssetRefs: []OverlayAssetRef{{
					AssetID:   "leak",
					URL:       "assets/light_leak_01.mp4",
					SHA256:    GoldenLightLeak01Hash,
					MediaType: "video/mp4",
				}},
			},
		},
	}
	got, err := CompileChrononPlan(plan)
	if err != nil {
		t.Fatal(err)
	}
	layer := got.Plan.Layers[0]
	if layer.BlendMode != "screen" {
		t.Fatalf("default blend = %q, want screen", layer.BlendMode)
	}
	if layer.Opacity != 0 {
		t.Fatalf("default opacity = %v, want 0 (no override)", layer.Opacity)
	}
	if layer.Loop {
		t.Fatal("default loop = true, want false (terminate)")
	}

	// The default layer's JSON must carry blend_mode but no loop key
	// (loop=false is the terminate default and is omitted).
	raw, err := got.Marshal()
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	layers := doc["layers"].([]any)
	first := layers[0].(map[string]any)
	if first["blend_mode"] != "screen" {
		t.Fatalf("json blend_mode = %v, want screen", first["blend_mode"])
	}
	if _, ok := first["loop"]; ok {
		t.Fatalf("json must omit loop when false (terminate default), got %v", first["loop"])
	}
}
