import fs from 'node:fs';

/**
 * Exports browser cookies to Netscape format for yt-dlp/ffmpeg.
 * @param {object} page - Puppeteer page
 * @param {string} outputPath - Path to save cookies file
 */
export async function exportCookiesForYtDlp(page, outputPath) {
  const cookies = await page.cookies();

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by PipelineGen Artlist scraper',
  ];

  for (const c of cookies) {
    const domain = c.domain || '';
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
    const name = c.name;
    const value = c.value;

    lines.push([domain, includeSubdomains, path, secure, expires, name, value].join('\t'));
  }

  fs.writeFileSync(outputPath, lines.join('\n') + '\n', 'utf8');
  console.error(`[artlist] exported ${cookies.length} cookies to ${outputPath}`);
}
