// Package operations — generation_submission_types.go owns the canonical
// submission contract, service dependencies, and constructor.
package operations

import (
	"encoding/json"
	"sync"
	"time"

	"go.uber.org/zap"

	"github.com/Marcuss-ops/PipelineGen/internal/domain/job"
	domainops "github.com/Marcuss-ops/PipelineGen/internal/domain/operations"
)

// EventTypeScriptGenerateQueued is the canonical outbox event emitted in the
// same atomic transaction as the operation and job rows.
const EventTypeScriptGenerateQueued = "script.generate.queued"

const aggregateTypeScriptGenerate = "script.generate"

// SubmitRequest is the canonical input for a script-generation submission.
type SubmitRequest struct {
	Scope          domainops.Scope
	IdempotencyKey string
	RequestHash    string
	ForceRefresh   bool

	JobType       string
	JobPayload    json.RawMessage
	JobPriority   int
	JobMaxRetries int

	// Optional pre-generated IDs. Empty values are generated by the service.
	OperationID string
	JobID       string
}

// SubmitResult is the canonical output of Submit.
type SubmitResult struct {
	Operation *domainops.Operation
	// Job is the canonical live job state. On a replay it is loaded through
	// JobGetter; on a fresh submission it is the row inserted in the TX.
	Job              *job.Job
	IsIdempotencyHit bool
	IsSupersede      bool
}

// Service owns validation, idempotency decisions, and the atomic
// operation+job+outbox transaction.
type Service struct {
	ops       OperationsRepository
	jobs      JobEnqueuer
	jobGetter JobGetter
	outbox    OutboxEmitter
	txMgr     TxManager
	jobIDGen  func() string
	opIDGen   func() string
	log       *zap.Logger
	submitMu  sync.Mutex
	nowFunc   func() time.Time
}

// NewService constructs the canonical submission service. Every operational
// dependency is required so composition errors fail at startup.
func NewService(
	ops OperationsRepository,
	jobs JobEnqueuer,
	jobGetter JobGetter,
	outbox OutboxEmitter,
	txMgr TxManager,
	log *zap.Logger,
) *Service {
	if ops == nil {
		panic("operations.NewService: OperationsRepository is nil (composition bug)")
	}
	if jobs == nil {
		panic("operations.NewService: JobEnqueuer is nil (composition bug)")
	}
	if jobGetter == nil {
		panic("operations.NewService: JobGetter is nil (composition bug)")
	}
	if outbox == nil {
		panic("operations.NewService: OutboxEmitter is nil (composition bug)")
	}
	if txMgr == nil {
		panic("operations.NewService: TxManager is nil (composition bug)")
	}
	if log == nil {
		log = zap.NewNop()
	}
	return &Service{
		ops:       ops,
		jobs:      jobs,
		jobGetter: jobGetter,
		outbox:    outbox,
		txMgr:     txMgr,
		jobIDGen:  defaultJobIDGen,
		opIDGen:   defaultOperationIDGen,
		log:       log,
		nowFunc:   time.Now,
	}
}
