// ARCH-ALLOWLIST: im-001-multipart-canonical-surface
// Per IMAGES-T04-MULTIPART (Phase 9 cycle 2, 2026-07-04):
// the canonical multipart-form upload surface for clip assets
// lives in internal/api/assets/clips/ingest.go::UploadVideoClip
// (the IngestHandler POST /upload-video route), NOT in this
// package. This package's /upload handler binds JSON (UploadRequest
// with image_url field), not multipart. The two surfaces are
// distinct concerns:
//   - clips/ingest.go::UploadVideoClip  (multipart) -- clip video files
//     via *upload.UseCase + dispatcher + outbox event pipeline.
//   - images/impl.go::Upload           (JSON, image_url) -- legacy
//     image-asset URL ingestion (kept for back-compat with the
//     image-search surface).
//
// godlike/06 SSOT: one canonical owner per fact -- the clip
// multipart path lives at clips/ingest.go; the image URL path lives
// here. Operators MUST NOT migrate clip uploads to /api/images/upload
// (wrong surface; the dispatcher + outbox pipeline is the
// load-bearing infrastructure for clip indexing).
//
// Package images (api/images) — upload_handler.go holds the legacy
// JSON-based image upload handler. This is the RETRIEVED territory
// (URL ingestion, not AI generation). Per the golden rule:
// retrieved = images found, downloaded, or ingested from normal
// sources (NOT generated by AI).
package images

import (
	"net/http"
	"strings"

	"github.com/Marcuss-ops/PipelineGen/internal/capabilities/assets/ingest"
	"github.com/Marcuss-ops/PipelineGen/pkg/apiutil"
	"github.com/gin-gonic/gin"
)

// Upload handles POST /api/images/upload — legacy image-asset URL
// ingestion. Accepts JSON with image_url; delegates to the canonical
// ingest service.
//
// PR-IMG-LEGACY-2 (IMAGES-LEGACY-CLEANUP-2026-07-06 wave, 2026-07-06,
// EXPAND phase, deadline 2026-08-08): the pre-PR fallback to
// h.service.SearchAndDownload when ingestSvc was unwired was a
// cross-domain silent semantic switch — POST /upload (ingest intent)
// would return a SearchAndDownload response (search intent) with the
// wrong shape. The fallback is RETIRED per godlike/07 NO-FAKE-AVAILABILITY.
// When ingestSvc is nil the handler now fails closed with 503
// ServiceUnavailable and an actionable error message naming both
// escape hatches (wire ingestSvc vs call SearchAndDownload via the
// canonical /api/images/retrieved/search route).
//
// godlike/06 SSOT: ingest.Service is the SOLE canonical owner of
// image-asset URL ingestion on this package. The /upload route does
// NOT delegate to Service.SearchAndDownload under any
// condition (the two services are distinct bounded contexts).
func (h *ImagesHandler) Upload(c *gin.Context) {
	var req UploadRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		apiutil.BadRequest(c, err.Error())
		return
	}

	// Fail-closed at composition seam: without ingestSvc, the request
	// is structurally unable to perform an ingest (vs a search). 503
	// is the canonical typed-error status for unwired dependencies.
	if h.ingestSvc == nil {
		apiutil.Error(c, http.StatusServiceUnavailable,
			"image upload requires the ingest service; /upload cannot fallback to search")
		return
	}

	name := req.Name
	if name == "" {
		name = req.Subject
	}

	slug := strings.ReplaceAll(strings.ToLower(req.Subject), " ", "-")

	res, err := h.ingestSvc.Ingest(c.Request.Context(), &ingest.Request{
		Kind:   string(ingest.KindImage),
		URL:    req.URL,
		Name:   name,
		Group:  slug,
		Tags:   req.Tags,
		Source: "upload",
	})
	if err != nil {
		apiutil.InternalError(c, err)
		return
	}

	apiutil.OK(c, res)
}
