package adapters

// cliprender_plan.go wires the plan-facing adapters for the clip.render
// preparation phase:
//
//   - ClipRenderSubtitleCompiler — deterministic ASS artifact (burn|sidecar)
//     via texttracks.CompileASSContent (the single owner of ASS content).
//   - ClipRenderExecutorAdapter — maps the rustexec.ClipRenderer result onto
//     the capability's RenderOutcome verbatim (media facts come from the Rust
//     metadata, never re-derived).
//
// Every adapter is fail-closed: a missing dependency surfaces a typed error
// at call time, never a silent no-op path.

import (
	"context"
	"github.com/Marcuss-ops/PipelineGen/internal/kernel/digest"

	"fmt"
	"math"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/Marcuss-ops/PipelineGen/internal/capabilities/assets/texttracks"
	cliprender "github.com/Marcuss-ops/PipelineGen/internal/capabilities/cliprender"
	"github.com/Marcuss-ops/PipelineGen/internal/platform/media/rustexec"
)

// ── SubtitleCompiler (deterministic ASS) ─────────────────────────────

// ClipRenderSubtitleCompiler implements the capability's SubtitleCompiler
// port with the canonical ASS generator (texttracks.CompileASSContent — the
// single owner of ASS content generation). The artifact is written into the
// run's scratch dir (subtitles.ass) and validated before the plan is sealed.
//
// Determinism: identical cues + style ALWAYS produce identical bytes (the
// generator embeds no timestamps/randoms/paths). Mode burn|sidecar only
// tags the artifact — the ASS bytes are the same, the render pass decides
// whether to rasterize libass (burn) or ship the file (sidecar).
//
// Fail-closed: empty cues, an invalid mode, or an invalid generated ASS is a
// typed error — speech recognition is NEVER regenerated just to build
// subtitles (feature spec §5).
type ClipRenderSubtitleCompiler struct{}

// assContentCache reuses deterministic ASS generation across repeated renders
// of the same transcript/style. It is intentionally a content cache, not a
// claim of GPU glyph rasterization: libass still owns burn-time rasterization.
// The key includes all inputs that affect generated bytes; run-specific paths
// never enter the key.
var assContentCache sync.Map // map[string]string

func (c *ClipRenderSubtitleCompiler) Compile(ctx context.Context, in cliprender.SubtitleCompileInput) (*cliprender.SubtitleArtifact, error) {
	switch in.Mode {
	case cliprender.SubtitlesModeBurn, cliprender.SubtitlesModeSidecar:
	default:
		return nil, fmt.Errorf("%w: invalid subtitle mode %q", cliprender.ErrSubtitleCompileUnavailable, in.Mode)
	}
	if len(in.Cues) == 0 {
		return nil, fmt.Errorf("%w: zero cues for asset %q — subtitles cannot be compiled without transcript timing (speech recognition is never regenerated for subtitles)", cliprender.ErrSubtitleCompileUnavailable, in.AssetID)
	}
	// Canonical clip tracks can contain a final cue from the source timeline
	// that extends past the extracted clip boundary. Keep the canonical text,
	// but clip only its visible interval to the actual media duration; cues
	// wholly after the boundary are not rendered. This preserves fail-closed
	// validation while avoiding an invalid ASS for an otherwise valid clip.
	cues := trimClipRenderCues(in.Cues, in.ClipDurationMS)
	if len(cues) == 0 {
		return nil, fmt.Errorf("%w: no cues remain inside clip duration for asset %q", cliprender.ErrSubtitleCompileUnavailable, in.AssetID)
	}
	canonicalCues := mapClipRenderCues(cues)
	keyMaterial := fmt.Sprintf("%s\x00%s\x00%v", in.Language, in.StyleID, canonicalCues)
	key := digest.SHA256String(keyMaterial)
	var content string
	contentCacheHit := false
	if cached, ok := assContentCache.Load(key); ok {
		content = cached.(string)
		contentCacheHit = true
	} else {
		generated, compileErr := texttracks.CompileASSContent(canonicalCues, in.StyleID)
		if compileErr != nil {
			return nil, fmt.Errorf("%w: compile ASS content: %v", cliprender.ErrSubtitleCompileUnavailable, compileErr)
		}
		content = generated
		assContentCache.Store(key, content)
	}
	if err := os.MkdirAll(in.OutputDir, 0o755); err != nil {
		return nil, fmt.Errorf("create subtitle output dir %q: %w", in.OutputDir, err)
	}
	localPath := filepath.Join(in.OutputDir, "subtitles.ass")
	sum := digest.SHA256String(content)
	sha := sum
	// Reuse an already materialized artifact for the same canonical
	// transcript/style. The run-local file is a hard link to the durable
	// content-addressed cache, so repeated clip jobs do not regenerate or
	// rewrite identical subtitle bytes. The existing file is still validated
	// before it is accepted by the plan.
	artifactCacheHit := false
	if existing, readErr := os.ReadFile(localPath); readErr == nil && string(existing) == content {
		artifactCacheHit = true
		if err := texttracks.ValidateASSFile(localPath, in.ClipDurationMS); err != nil {
			return nil, fmt.Errorf("%w: invalid existing ASS for asset %q: %v", cliprender.ErrSubtitleCompileUnavailable, in.AssetID, err)
		}
		cliprender.RecordSubtitleCacheFacts(localPath, cliprender.SubtitleCacheFacts{
			ContentCacheHit:  contentCacheHit,
			ArtifactCacheHit: artifactCacheHit,
			Measured:         true,
		})
		return &cliprender.SubtitleArtifact{LocalPath: localPath, SHA256: sha, Mode: in.Mode, StyleID: in.StyleID}, nil
	}
	cacheDir := filepath.Join(filepath.Dir(filepath.Dir(in.OutputDir)), "subtitle-cache")
	cachePath := filepath.Join(cacheDir, sha+".ass")
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		return nil, fmt.Errorf("create subtitle cache dir %q: %w", cacheDir, err)
	}
	if _, err := os.Stat(cachePath); err == nil {
		artifactCacheHit = true
	} else if os.IsNotExist(err) {
		if err := os.WriteFile(cachePath, []byte(content), 0o644); err != nil {
			return nil, fmt.Errorf("write cached ASS artifact %q: %w", cachePath, err)
		}
	} else if err != nil {
		return nil, fmt.Errorf("stat cached ASS artifact %q: %w", cachePath, err)
	}
	if err := os.Link(cachePath, localPath); err != nil {
		// Hard links can be unavailable on a different filesystem. Preserve
		// correctness with a copy only in that exceptional case.
		if copyErr := os.WriteFile(localPath, []byte(content), 0o644); copyErr != nil {
			return nil, fmt.Errorf("link/copy ASS artifact %q: link=%v copy=%w", localPath, err, copyErr)
		}
	}
	if err := texttracks.ValidateASSFile(localPath, in.ClipDurationMS); err != nil {
		return nil, fmt.Errorf("%w: invalid generated ASS for asset %q: %v", cliprender.ErrSubtitleCompileUnavailable, in.AssetID, err)
	}
	cliprender.RecordSubtitleCacheFacts(localPath, cliprender.SubtitleCacheFacts{
		ContentCacheHit:  contentCacheHit,
		ArtifactCacheHit: artifactCacheHit,
		Measured:         true,
	})
	return &cliprender.SubtitleArtifact{
		LocalPath: localPath,
		SHA256:    sha,
		Mode:      in.Mode,
		StyleID:   in.StyleID,
	}, nil
}

func trimClipRenderCues(in []cliprender.Cue, durationMS int64) []cliprender.Cue {
	if durationMS <= 0 {
		return append([]cliprender.Cue(nil), in...)
	}
	out := make([]cliprender.Cue, 0, len(in))
	for _, cue := range in {
		if cue.StartMs >= durationMS {
			continue
		}
		if cue.EndMs > durationMS {
			cue.EndMs = durationMS
		}
		if cue.EndMs > cue.StartMs {
			out = append(out, cue)
		}
	}
	return out
}

// ── RenderExecutor (Rust render_clip boundary) ───────────────────────

// ClipRenderExecutor is the narrow seam over the rustexec.ClipRenderer so
// the composition-root adapter stays testable without the Rust process.
// The concrete implementation re-validates the sealed plan, verifies every
// referenced artifact, resolves the encoder policy from the composition-root
// media config, and refuses success without a non-empty output.
type ClipRenderExecutor interface {
	RenderClip(ctx context.Context, plan cliprender.ClipRenderPlanV1, backend cliprender.RenderBackend) (rustexec.ClipRenderResult, error)
}

// ClipRenderExecutorAdapter bridges the rustexec.ClipRenderer to the
// capability's RenderExecutor port. It resolves the render backend through
// the capability's RenderBackendResolver (probed host capabilities, never a
// hardcoded CUDA path) and reports the resolved backend in the outcome.
// Fail-closed: an unwired renderer is a typed error (never a silent no-op
// that reports a rendered clip).
type ClipRenderExecutorAdapter struct {
	renderer ClipRenderExecutor
	chronon  ClipRenderExecutor
	resolver *cliprender.RenderBackendResolver
	probe    cliprender.BackendCapabilityProbe
}

func (a *ClipRenderExecutorAdapter) Render(ctx context.Context, plan cliprender.ClipRenderPlanV1) (*cliprender.RenderOutcome, error) {
	if a == nil || a.renderer == nil {
		return nil, fmt.Errorf("%w: Rust clip renderer not wired", cliprender.ErrRenderPhaseNotImplemented)
	}
	metrics := cliprender.NewRenderMetricsV2()
	renderStart := time.Now()

	// Backend selection lives ONLY in the resolver (probed host capabilities
	// + the plan's requirements). The adapter never tries a backend and falls
	// back on failure; it dispatches execution to the executor that owns the
	// selected backend. The probe/resolve timings below are the real
	// instrumentation for backend_probe_ms / backend_resolve_ms — the same
	// fail-closed semantics as cliprender.ResolveBackend, split so the report
	// can attribute each stage.
	if a.probe == nil {
		return nil, fmt.Errorf("%w: backend capability probe is not wired (DEGRADED — no host capability information)", cliprender.ErrBackendUnavailable)
	}
	if a.resolver == nil {
		return nil, fmt.Errorf("%w: render backend resolver is not wired (NOT READY — cannot select a backend)", cliprender.ErrBackendUnavailable)
	}
	probeStart := time.Now()
	capabilities, err := a.probe.ProbeCapabilities(ctx)
	metrics.BackendProbeMS = cliprender.Metric(time.Since(probeStart).Milliseconds())
	if err != nil {
		return nil, fmt.Errorf("%w: capability probe failed: %w (DEGRADED — host capabilities unknown)", cliprender.ErrBackendUnavailable, err)
	}
	resolveStart := time.Now()
	backend, err := a.resolver.Resolve(ctx, plan, capabilities)
	metrics.BackendResolveMS = cliprender.Metric(time.Since(resolveStart).Milliseconds())
	if err != nil {
		return nil, err
	}
	metrics.BackendSelected = backend
	// Single-authority selection: exactly one backend is attempted, zero
	// fallbacks. Any fallback would be a silent downgrade — the resolver is
	// the only place backend choice happens.
	metrics.BackendAttempts = 1
	metrics.FallbackCount = 0
	// A configured-but-uncertified Chronon binary (ChrononVulkan without
	// ChrononNativeCertified) explains why the resolver did not select
	// chronon_vulkan — the real-probe gate refused it. Surface the reason so
	// operators see the certification gate in the report instead of guessing
	// why the GPU path is not used. Informational only: no fallback happened
	// (single-authority selection), so fallback_count stays 0.
	if capabilities.ChrononVulkan && !capabilities.ChrononNativeCertified {
		metrics.FallbackReason = "chronon_native_not_certified"
	}

	var result rustexec.ClipRenderResult
	if backend == cliprender.BackendChrononVulkan {
		if a.chronon == nil {
			return nil, fmt.Errorf("%w: backend %q selected but no Chronon executor is wired", cliprender.ErrBackendUnavailable, backend)
		}
		result, err = a.chronon.RenderClip(ctx, plan, backend)
	} else {
		// The Rust executor owns the non-Chronon backends: cuda_native (PATH
		// B CUDA hybrid) and ffmpeg_fallback (software baseline).
		result, err = a.renderer.RenderClip(ctx, plan, backend)
	}
	if err != nil {
		return nil, err
	}

	// All backend results are projected into the single canonical V2 report.
	// Until Rust exposes fine-grained phase metadata, its coarse ffmpeg_ms is
	// represented in CompositeMS; unknown phases remain NOT_INSTRUMENTED.
	// FFmpegMS below is only the legacy compatibility projection.
	if result.FilterGraphMS != nil {
		metrics.CompositeMS = cliprender.Metric(*result.FilterGraphMS)
	} else if result.FFmpegMS >= 0 && result.AudioMuxMS == nil {
		// Legacy coarse Rust boundary: retain the measured decode→encode wall
		// as the composite work only when no phase metadata is available.
		metrics.CompositeMS = cliprender.Metric(result.FFmpegMS)
	}
	if result.DecodeMS != nil {
		metrics.DecodeMS = cliprender.Metric(*result.DecodeMS)
	}
	if result.SubtitleRasterMS != nil {
		metrics.SubtitleRasterMS = cliprender.Metric(*result.SubtitleRasterMS)
	}
	if result.WatermarkRasterMS != nil {
		metrics.WatermarkRasterMS = cliprender.Metric(*result.WatermarkRasterMS)
	}
	if result.FrameConversionMS != nil {
		metrics.FrameConversionMS = cliprender.Metric(*result.FrameConversionMS)
	}
	if result.EncodeMS != nil {
		metrics.EncodeMS = cliprender.Metric(*result.EncodeMS)
	}
	if result.AudioMuxMS != nil {
		metrics.AudioMuxMS = cliprender.Metric(*result.AudioMuxMS)
	}
	// The Rust boundary now reports its own phase timings for the benchmark
	// decomposition: renderer_startup_ms is the pre-ffmpeg wall (plan decode
	// + source probe + filter-graph build + process spawn) and publish_ms is
	// the Rust-side output publish, mapped onto renderer_finalize_ms.
	// Both map only when actually reported (nil stays NOT_INSTRUMENTED —
	// never a fake zero). Publication beyond the Rust boundary is owned by
	// the publisher adapter, which reports its own measured walls; the
	// worker projects those into publication_total_ms / artifact_publish_ms /
	// drive_upload_ms and never re-times the Rust finalize.
	if result.StartupMS != nil {
		metrics.RendererStartupMS = cliprender.Metric(*result.StartupMS)
	}
	if result.ProbeMS != nil {
		metrics.ProbeMS = cliprender.Metric(*result.ProbeMS)
	}
	if result.PublishMS != nil {
		metrics.RendererOutputFinalizeMS = cliprender.Metric(*result.PublishMS)
	}
	if result.SubtitleRasterCPU != nil {
		metrics.SubtitleRasterCPU = *result.SubtitleRasterCPU
	}
	if result.GPUCopyBytes != nil {
		metrics.GPUCopyBytes = cliprender.Metric(int64(*result.GPUCopyBytes))
	}
	// Process/resource metrics are reported by the Rust operation owner and
	// projected into the canonical clip report only when actually measured.
	if result.OperationMetrics != nil {
		// These counters are measured by the Rust operation owner. Keep absent
		// fields at NOT_INSTRUMENTED; zero is valid only for explicitly
		// instrumented values.
		if result.OperationMetrics.PeakRSSBytes > 0 {
			metrics.PeakRSSBytes = cliprender.Metric(result.OperationMetrics.PeakRSSBytes)
		}
		if result.OperationMetrics.DiskReadBytes > 0 {
			metrics.DiskReadBytes = cliprender.Metric(result.OperationMetrics.DiskReadBytes)
		}
		if result.OperationMetrics.DiskWriteBytes > 0 {
			metrics.DiskWriteBytes = cliprender.Metric(result.OperationMetrics.DiskWriteBytes)
		}
		if result.OperationMetrics.NetworkRXBytes > 0 {
			metrics.NetworkRXBytes = cliprender.Metric(result.OperationMetrics.NetworkRXBytes)
		}
		if result.OperationMetrics.NetworkTXBytes > 0 {
			metrics.NetworkTXBytes = cliprender.Metric(result.OperationMetrics.NetworkTXBytes)
		}
	}
	// OutputBytes is an encoded output-size fact, not GPU readback traffic. The
	// Rust boundary does not instrument readback here, so keep the canonical
	// field at NOT_INSTRUMENTED rather than projecting an unrelated counter.
	if result.FPSNum > 0 && result.FPSDen > 0 {
		metrics.Frames = int(math.Round(result.DurationSec * float64(result.FPSNum) / float64(result.FPSDen)))
	}
	metrics.TotalMS = cliprender.Metric(time.Since(renderStart).Milliseconds())
	metrics.Compute(result.DurationSec)

	// Keep legacy scalar fields as projections of the canonical report/result
	// for existing consumers; no second metrics authority is introduced.
	return &cliprender.RenderOutcome{
		OutputPath:        result.OutputPath,
		SizeBytes:         result.SizeBytes,
		DurationSec:       result.DurationSec,
		Width:             result.Width,
		Height:            result.Height,
		FPSNum:            result.FPSNum,
		FPSDen:            result.FPSDen,
		Backend:           backend,
		FFmpegMS:          result.FFmpegMS,
		AudioCopyEligible: result.AudioCopyEligible,
		AudioEncodePasses: result.AudioEncodePasses,
		SubtitleRasterCPU: result.SubtitleRasterCPU,
		GPUCopyBytes:      result.GPUCopyBytes,
		Metrics:           metrics,
	}, nil
}
