// Package operations — domain types for the FASE 2 canonical
// `operations` table backing the application-layer
// `GenerationSubmissionService` use case.
//
// godlike/06 SSOT: this package is the SOLE canonical owner of
// the per-request Operation record shape, the Scope + State enums,
// and the typed error sentinels. Repository implementations in
// `internal/platform/sqlite/operations` and the
// application service in
// `internal/capabilities/operations/generation_submission_service.go`
// consume ONLY the types declared here.
//
// godlike/07 NO-FAKE-AVAILABILITY: a bogus Scope or State value
// (one not in the canonical set) is rejected by the repository
// with `ErrInvalidOperationScope` / `ErrInvalidOperationState`,
// not silently accepted. The typed errors are the canonical
// surface for "this is not a real operation" — consumers
// `errors.Is`-probe them, never string-compare.
package operations

import (
	"errors"
	"fmt"
	"time"
)

// Scope identifies the request family that an Operation belongs to.
// Each Scope has its own idempotency-key namespace (the same
// idempotency_key on two different Scopes is a distinct operation).
//
// FASE 2 ships only `ScopeScriptGenerate`; future scopes
// (e.g. `ScopeVoiceoverGenerate`, `ScopeImageGenerate`) reuse the
// same table without schema changes — the typed Scope enum is
// the canonical gate.
type Scope string

const (
	// ScopeScriptGenerate is the canonical scope for all
	// POST /api/script/generate submissions. The pre-FASE-2
	// Idempotency-Key header (255-char opaque) maps 1:1 to the
	// operations.idempotency_key column for this scope.
	ScopeScriptGenerate Scope = "script.generate"
)

// IsValid returns true if s is a known operation scope.
func (s Scope) IsValid() bool {
	switch s {
	case ScopeScriptGenerate:
		return true
	}
	return false
}

// String returns the canonical string representation (mirrors
// the underlying typed string so fmt.Sprintf("%s", s) works).
func (s Scope) String() string { return string(s) }

// State identifies the lifecycle state of a single Operation.
//
//	QUEUED     — job created and outbox event committed in the
//	             same atomic TX; worker has not yet claimed the job.
//	COMPLETED  — job reached a terminal success state
//	             (SUCCEEDED or PARTIALLY_SUCCEEDED). Updated lazily
//	             by the finalizer (NOT by the submission service).
//	FAILED     — job reached a terminal failure state
//	             (FAILED or CANCELLED). Updated lazily by the
//	             finalizer (NOT by the submission service).
//	SUPERSEDED — a newer operation in the same (scope, key) bucket
//	             was created via `force_refresh=true`. The old
//	             operation's job continues to terminal state; the
//	             operation record itself is just marked SUPERSEDED.
type State string

const (
	StateQueued     State = "QUEUED"
	StateCompleted  State = "COMPLETED"
	StateFailed     State = "FAILED"
	StateSuperseded State = "SUPERSEDED"
)

// IsValid returns true if st is a known operation state.
func (st State) IsValid() bool {
	switch st {
	case StateQueued, StateCompleted, StateFailed, StateSuperseded:
		return true
	}
	return false
}

// String returns the canonical string representation.
func (st State) String() string { return string(st) }

// Operation is the canonical domain record for a single
// (scope, idempotency_key, request_hash) submission. It is the
// authoritative source of truth for "did this request already
// produce a job? what is the job? is the operation still the
// active one or has it been superseded by a force_refresh?"
//
// godlike/06 SSOT: this struct shape is the canonical mirror
// of the `operations` SQLite table. Adding a column is a
// 3-surface lockstep change: this struct + the migration +
// the Repository scan helpers.
type Operation struct {
	// OperationID is the canonical primary key (TEXT, NOT NULL).
	// Generated by the submission service (caller-supplied via the
	// `idempotency_key` is NOT reused as operation_id — operation_id
	// is a separate namespace so the same key on different requests
	// can be tracked across multiple operations).
	OperationID string

	// Scope is the request family (see Scope constants).
	Scope Scope

	// IdempotencyKey is the caller-supplied 255-char opaque string
	// from the Idempotency-Key HTTP header. Whitespace-trimmed
	// by the repository on write; preserved verbatim on read.
	IdempotencyKey string

	// RequestHash is the canonical SHA-256 fingerprint of the
	// request body (caller-supplied; the submission service
	// accepts it as a pre-computed string). Same hash + same key
	// → idempotency hit; different hash + same key → 409 conflict
	// (unless force_refresh=true, in which case a new operation
	// is created with supersedes_operation_id set).
	RequestHash string

	// JobID is the canonical broker job.id created in the same
	// atomic TX as the operation row. NOT NULL — every operation
	// has a job; a NULL job_id would mean the TX rolled back
	// and the operation row would not have been committed.
	JobID string

	// State is the operation lifecycle (see State constants).
	State State

	// SupersedesOperationID is the operation_id of the prior
	// operation that this one replaces (set only when the caller
	// requested force_refresh=true AND a prior operation existed
	// in the same (scope, key) bucket). Empty for the common path.
	SupersedesOperationID string

	// CreatedAt is the RFC3339 timestamp at Submit commit.
	CreatedAt time.Time

	// UpdatedAt is the RFC3339 timestamp of the most recent state
	// transition (e.g. QUEUED → COMPLETED by the finalizer).
	// Initial value equals CreatedAt.
	UpdatedAt time.Time
}

// ── Typed error sentinels (godlike/06 SSOT: canonical owner) ──────────

// ErrIdempotencyConflict is returned by Submit when the caller
// submits a (scope, idempotency_key) pair whose most recent prior
// operation has a DIFFERENT request_hash. This is the canonical
// 409 IDEMPOTENCY_CONFLICT signal — the HTTP layer maps it to
// 409 Conflict without leaking internal IDs.
//
// The semantic: "you said `retry` with the same key, but the
// payload is different — we will NOT silently replay the prior
// job and we will NOT silently enqueue a new job. Resolve the
// conflict (or use force_refresh=true) and resubmit."
var ErrIdempotencyConflict = errors.New("operations: idempotency conflict (same key, different request_hash)")

// ErrOperationNotFound is returned by Repository.GetByID when no
// operation with the given operation_id exists. The HTTP layer
// maps it to 404 Not Found.
var ErrOperationNotFound = errors.New("operations: operation not found")

// ErrInvalidOperationScope is returned by the repository when a
// caller writes an out-of-set Scope value. godlike/07 fail-closed:
// a bogus scope is rejected, not silently accepted.
var ErrInvalidOperationScope = errors.New("operations: invalid scope (not in canonical Scope set)")

// ErrInvalidOperationState is returned by the repository when a
// caller writes an out-of-set State value. godlike/07 fail-closed.
var ErrInvalidOperationState = errors.New("operations: invalid state (not in canonical State set)")

// ErrIdempotencyKeyInvalid is returned by the submission service
// when the caller-supplied idempotency_key is empty / too long /
// contains non-printable-ASCII. The HTTP layer maps it to 400.
var ErrIdempotencyKeyInvalid = errors.New("operations: idempotency key is empty, too long (>255 chars), or contains non-printable-ASCII")

// ErrRequestHashInvalid is returned by the submission service when
// the caller-supplied request_hash is empty or not a 64-char
// lowercase hex string. The HTTP layer maps it to 400.
var ErrRequestHashInvalid = errors.New("operations: request_hash is empty or not a 64-char lowercase hex SHA-256")

// ErrSubmitNoPriorOperation is returned by the force_refresh
// path when no prior operation exists in the (scope, key) bucket
// — there is nothing to supersede, so the operation is created
// without supersedes_operation_id. This is NOT an error; callers
// use it to log "first force_refresh for this key".
var ErrSubmitNoPriorOperation = errors.New("operations: no prior operation to supersede (force_refresh is a no-op link-wise)")

// ErrCorruptedOperationRow is returned by scanOperation when a
// stored timestamp value fails to parse back to a valid
// RFC3339 time.Time. This is a DB-corruption signal (the
// operations table's created_at / updated_at columns are
// always canonical — Insert validates non-zero timestamps and
// formats via timeutil.FormatRFC3339), so any parse failure
// indicates a misconfigured driver, a partial commit, or
// manual row tampering. godlike/07 fail-closed: the caller
// surfaces this to the operator dashboard, NOT silently
// returns a zero time.Time (which would be indistinguishable
// from a legitimate value).
var ErrCorruptedOperationRow = errors.New("operations: corrupted row (timestamp parse failure)")

// ErrSelfSupersedeReference is returned by validateForWrite when
// the operation's supersedes_operation_id == operation_id (a
// operation pointing at itself). Defensive: the service layer
// sets supersedes_operation_id AFTER reading a prior operation,
// so a self-reference can only be introduced by a buggy direct
// caller of the repository (e.g. an admin script). Bounded
// check, no perf cost.
var ErrSelfSupersedeReference = errors.New("operations: supersedes_operation_id == operation_id (self-reference rejected)")

// WrapIdempotencyConflict attaches the conflicting (key, expected
// hash, actual hash) triple to ErrIdempotencyConflict for
// operator-audit logging. The returned error wraps the canonical
// sentinel so errors.Is probes still succeed.
func WrapIdempotencyConflict(scope Scope, key, expectedHash, actualHash string) error {
	return fmt.Errorf("%w: scope=%s key=%s expected_hash=%s actual_hash=%s",
		ErrIdempotencyConflict, scope, key, expectedHash, actualHash)
}

// WrapOperationNotFound attaches the missing operation_id to
// ErrOperationNotFound for operator-audit logging.
func WrapOperationNotFound(operationID string) error {
	return fmt.Errorf("%w: operation_id=%s", ErrOperationNotFound, operationID)
}

// ── Validation helpers (godlike/07 fail-closed at the input boundary) ──

// IsValidIdempotencyKey mirrors the existing `Idempotency-Key`
// header validation in internal/platform/httpserver/middleware/idempotency.go:
// printable ASCII only, 1..255 chars.
//
// Whitespace is allowed (matches the canonical middleware
// behaviour: keys are TrimSpace'd before validation in the HTTP
// layer; the repository accepts the trimmed value verbatim).
func IsValidIdempotencyKey(key string) bool {
	if len(key) == 0 || len(key) > 255 {
		return false
	}
	for _, r := range key {
		if r < 0x20 || r > 0x7E {
			return false
		}
	}
	return true
}

// IsValidRequestHash enforces the canonical 64-char lowercase
// hex SHA-256 shape. A non-canonical hash (e.g. uppercase,
// truncated, or non-hex) is rejected at the input boundary.
func IsValidRequestHash(hash string) bool {
	if len(hash) != 64 {
		return false
	}
	for _, r := range hash {
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')) {
			return false
		}
	}
	return true
}
