// Package baseline — archcheck phase 0 baseline loader.
//
// baseline/load.go owns the JSON shape of
// scripts/archcheck/phase0_baseline.json and the read-path that
// decodes it into a typed struct. The baseline is the committed
// monotone-decreasing snapshot the 5 Phase 0 rules compare their
// actuals against (see architecture/current.yaml Wave 19 PR-A for
// the lifecycle). baseline/seed.go writes the file; baseline/compare.go
// diffs actual vs baseline; runner.go orchestrates the 5 rule calls.
//
// Package boundary: this file is `package baseline` (separate from
// the top-level `package main` of the archcheck binary) so the
// baseline/ subdirectory can hold a focused, reusable concern
// without dragging the 5 Phase 0 check functions along. main.go
// and runner.go import this package and use the exported symbols
// (baseline.File, baseline.Baseline, baseline.Load).
package baseline

import (
	"encoding/json"
	"fmt"
	"os"
)

// File is the committed monotone-decreasing baseline for the 5 Phase
// 0 rules. Each rule reads only its own section; the file is
// regenerated by the operator-only `--seed-baseline` flag (see
// main() dispatch in the archcheck binary). The tool does NOT
// auto-write the baseline: missing-file cases are surfaced as a
// hard-error violation in runPhase0Checks().
const File = "scripts/archcheck/phase0_baseline.json"

// Baseline is the JSON shape of scripts/archcheck/phase0_baseline.json.
// Each section is a list of rg-shaped strings (path or
// path:line:text), normalized and sorted. The `_meta` block records
// when the baseline was last regenerated; it is informational only.
type Baseline struct {
	InterfaceBraces     []string `json:"interface_braces"`
	Setters             []string `json:"setters"`
	TypeAliasesCrossPkg []string `json:"type_aliases_cross_pkg"`
	FakeRoutes          []string `json:"fake_routes"`
	HandlersToDB        []string `json:"handlers_to_db"`
	Meta                struct {
		GeneratedAtRFC3339 string `json:"generated_at"`
		Note               string `json:"note,omitempty"`
	} `json:"_meta"`
}

// Load reads scripts/archcheck/phase0_baseline.json and returns the
// decoded struct. The baseline file MUST exist when this helper is
// called (the missing-file case is handled upstream in
// runPhase0Checks() with a hard-error rather than auto-seeding).
//
// Sanity check: any section that decodes as nil (e.g. a partial
// baseline where someone hand-edited the JSON and removed an array)
// is forced to []string{} so the compare helper has a safe
// comparison side.
func Load() (Baseline, error) {
	var b Baseline
	text, err := os.ReadFile(File)
	if err != nil {
		return b, fmt.Errorf("read %s: %w", File, err)
	}
	if err := json.Unmarshal(text, &b); err != nil {
		return b, fmt.Errorf("decode %s: %w", File, err)
	}
	// Force any nil section to []string{} so SubtractSet is safe.
	if b.InterfaceBraces == nil {
		b.InterfaceBraces = []string{}
	}
	if b.Setters == nil {
		b.Setters = []string{}
	}
	if b.TypeAliasesCrossPkg == nil {
		b.TypeAliasesCrossPkg = []string{}
	}
	if b.FakeRoutes == nil {
		b.FakeRoutes = []string{}
	}
	if b.HandlersToDB == nil {
		b.HandlersToDB = []string{}
	}
	return b, nil
}
