-- 113_youtube_discoveries.sql
--
-- PR-D YouTube Channel Monitor cutover, Commit D (June 2026):
-- the per-channel discovery ledger for the monitor's leader-election-by-INSERT
-- dedupe pattern. Each row is a single YouTube video observed during one or
-- more scheduler cycles; the UNIQUE(channel_id, video_id) constraint is the
-- canonical dedupe key — only the goroutine whose INSERT INTO ... ON CONFLICT
-- DO NOTHING RETURNING id yielded a row proceeds to emit a durable
-- youtube_clip.extract job; the rest classify outcome as `already_scheduled`.
--
-- Column semantics (mirrors AGENTS.md Architecture §6 row-by-row ownership):
--   - id              TEXT PK; convention "disc_<channelID>_<videoID>" so the
--                      INSERT can omit it (auto-generated by hashutil.RandomString)
--                      while debugging the cell a single query hits.
--   - channel_id      TEXT NOT NULL; canonical category_channels.id (text FK,
--                      no SQL-level FK constraint per godlike/06 §6 — application
--                      layer enforces the relationship).
--   - video_id        TEXT NOT NULL; YouTube video ID.
--   - discovered_at   TEXT NOT NULL DEFAULT (datetime('now')); RFC3339 UTC. The
--                      cycle-end watermark query reads MAX(discovered_at) for
--                      the channel and persists it as category_channels.last_cursor.
--   - enqueued        INTEGER NOT NULL DEFAULT 0; 1 when a successful EnqueueExtract
--                      emitted a durable job for this video, 0 otherwise. The
--                      post-INSERT UPDATE sets enqueued=1 + enqueued_at on the
--                      `enqueued` outcome path.
--   - enqueued_at     TEXT; RFC3339 UTC, NULL while enqueued=0.
--   - source_url      TEXT; YouTube watch URL — observability + audit.
--   - title           TEXT; YT video title at discovery time — observability.
--   - outcome         TEXT NOT NULL DEFAULT 'pending'; per-cycle outcome
--                      (`enqueued` | `already_scheduled` | `rejected` |
--                      `pending`). Pinning the outcome at the table level lets
--                      downstream analytics distinguish a scheduled discovery
--                      from a rejected one.
--   - rejection_reason TEXT; populated when outcome='rejected' (semantic score
--                      below threshold, MaxVideosPerRun hit, etc.).
--
-- Index strategy:
--   - The PK + UNIQUE(channel_id, video_id) suffices for all single-row lookups
--     (leader-election INSERT, status-check on enqueue).
--   - idx_youtube_discoveries_watermark(channel_id, discovered_at DESC) makes
--     the cycle-end MAX(discovered_at) query a B-tree range scan → O(1) for the
--     single-row common case (one channel, one cycle).
--
-- Watermark semantics: category_channels.last_cursor is REPURPOSED from "last
-- video_id observed" to "RFC3339 timestamp of MAX(discovered_at) for the
-- channel" — see migration 108 (originating column) and migration 109
--(media_assets.discovered_at projection). Existing rows with video_id-shaped
-- cursors remain readable; new writes follow the timestamp contract.
--
-- Backfill: this migration does NOT backfill. Pre-existing monitor state
-- already lives in category_channels + media_assets (migration 109). On
-- the first Commit D cycle, the ledger starts empty and grows organically.

CREATE TABLE IF NOT EXISTS youtube_discoveries (
    id                TEXT PRIMARY KEY,
    channel_id        TEXT NOT NULL,
    video_id          TEXT NOT NULL,
    discovered_at     TEXT NOT NULL DEFAULT (datetime('now')),
    enqueued          INTEGER NOT NULL DEFAULT 0,
    enqueued_at       TEXT,
    source_url        TEXT,
    title             TEXT,
    outcome           TEXT NOT NULL DEFAULT 'pending',
    rejection_reason  TEXT,
    UNIQUE(channel_id, video_id)
);

CREATE INDEX IF NOT EXISTS idx_youtube_discoveries_watermark
    ON youtube_discoveries(channel_id, discovered_at DESC);
