// Command model-registry-gen keeps the Python mirror of the canonical
// model registry (internal/kernel/models) in sync.
//
// The Python sidecar services (embedding_server, reranker_server) cannot
// import Go constants, so their model identity strings are mirrored into
// scripts/services/model_registry_generated.py. This command is the sole
// writer of that mirror:
//
//	Default mode (fail-closed): verify the checked-in mirror matches the
//	Go registry byte-for-byte; exit 1 on drift.
//	--generate: rewrite the mirror from internal/kernel/models.
//
// Wiring: make verify-model-registry (part of verify-architecture) runs
// the default mode, so a registry change without a mirror regeneration
// fails CI. Follow the same pattern as cmd/architecture-registry.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"

	"github.com/Marcuss-ops/PipelineGen/internal/kernel/models"
)

const generatedPath = "scripts/services/model_registry_generated.py"

// rolePrefix maps each canonical role to the Python constant prefix used
// by the sidecar services. Kept stable so consumers don't churn when the
// registry grows.
var rolePrefix = map[models.Role]string{
	models.RoleTextEmbedding:        "TEXT",
	models.RoleVisualEmbedding:      "VISUAL",
	models.RoleAudioEmbedding:       "CLAP",
	models.RoleReranker:             "RERANKER",
	models.RoleTranscription:        "WHISPER",
	models.RoleSegmentUnderstanding: "SEGMENT_UNDERSTANDING",
}

func pythonBool(b bool) string {
	if b {
		return "True"
	}
	return "False"
}

func render() []byte {
	var b bytes.Buffer
	b.WriteString(`# DO NOT EDIT — generated by cmd/model-registry-gen from
# internal/kernel/models (the canonical model registry SSOT).
# Regenerate with: go run ./cmd/model-registry-gen --generate
#
# Model identity facts only. Weights are never committed to Git; they are
# downloaded and cached on the server and verified against the registry
# checksum at fetch time.

MODEL_REGISTRY = {
`)
	for _, m := range models.Canonical() {
		fmt.Fprintf(&b, "    %q: {\n", m.ID)
		fmt.Fprintf(&b, "        \"revision\": %q,\n", m.Revision)
		fmt.Fprintf(&b, "        \"checksum\": %q,\n", m.Checksum)
		fmt.Fprintf(&b, "        \"dimensions\": %d,\n", m.Dimensions)
		fmt.Fprintf(&b, "        \"license\": %q,\n", m.License)
		fmt.Fprintf(&b, "        \"role\": %q,\n", m.Role)
		fmt.Fprintf(&b, "        \"languages\": %d,\n", m.Languages)
		fmt.Fprintf(&b, "        \"enabled\": %s,\n", pythonBool(m.Enabled))
		b.WriteString("    },\n")
	}
	b.WriteString("}\n")
	for _, m := range models.Canonical() {
		prefix := rolePrefix[m.Role]
		if prefix == "" {
			continue
		}
		fmt.Fprintf(&b, "\n%s_MODEL_NAME = %q\n", prefix, m.ID)
		fmt.Fprintf(&b, "%s_MODEL_VERSION = %q\n", prefix, m.Revision)
		if m.Dimensions > 0 {
			fmt.Fprintf(&b, "%s_MODEL_DIMENSIONS = %d\n", prefix, m.Dimensions)
		}
	}
	b.WriteString("\n")
	return b.Bytes()
}

func main() {
	generate := flag.Bool("generate", false, "rewrite the Python mirror from internal/kernel/models")
	flag.Parse()

	content := render()
	if *generate {
		if err := os.WriteFile(generatedPath, content, 0o644); err != nil {
			fatal(2, fmt.Errorf("write %s: %w", generatedPath, err))
		}
		fmt.Printf("model-registry-gen: regenerated %s\n", generatedPath)
		return
	}

	existing, err := os.ReadFile(generatedPath)
	if err != nil {
		fatal(2, err)
	}
	if !bytes.Equal(existing, content) {
		fatal(1, fmt.Errorf("%s drifted from internal/kernel/models — run `go run ./cmd/model-registry-gen --generate`", generatedPath))
	}
	fmt.Printf("model-registry-gen: Python mirror in sync (%s)\n", generatedPath)
}

func fatal(code int, err error) {
	fmt.Fprintf(os.Stderr, "model-registry-gen: %v\n", err)
	os.Exit(code)
}
