# DO NOT EDIT — generated by cmd/model-registry-gen from
# internal/kernel/models (the canonical model registry SSOT).
# Regenerate with: go run ./cmd/model-registry-gen --generate
#
# Model identity facts only. Weights are never committed to Git; they are
# downloaded and cached on the server and verified against the registry
# checksum at fetch time.

MODEL_REGISTRY = {
    "intfloat/multilingual-e5-base": {
        "revision": "2026-06-26-v1",
        "checksum": "",
        "dimensions": 768,
        "license": "MIT",
        "role": "text_embedding",
        "languages": 0,
        "enabled": True,
    },
    "google/siglip-so400m-patch14-384": {
        "revision": "2026-06-16-v1",
        "checksum": "",
        "dimensions": 768,
        "license": "Apache-2.0",
        "role": "visual_embedding",
        "languages": 0,
        "enabled": True,
    },
    "BAAI/bge-reranker-v2-m3": {
        "revision": "",
        "checksum": "",
        "dimensions": 0,
        "license": "Apache-2.0",
        "role": "reranker",
        "languages": 0,
        "enabled": True,
    },
    "gemma3:1b": {
        "revision": "",
        "checksum": "",
        "dimensions": 0,
        "license": "unknown",
        "role": "segment_understanding",
        "languages": 0,
        "enabled": True,
    },
    "laion/clap-htsat-fused": {
        "revision": "2026-06-26-v1",
        "checksum": "",
        "dimensions": 512,
        "license": "Apache-2.0",
        "role": "audio_embedding",
        "languages": 0,
        "enabled": False,
    },
    "openai/whisper-large-v3-turbo": {
        "revision": "",
        "checksum": "",
        "dimensions": 0,
        "license": "MIT",
        "role": "transcription",
        "languages": 99,
        "enabled": False,
    },
}

TEXT_MODEL_NAME = "intfloat/multilingual-e5-base"
TEXT_MODEL_VERSION = "2026-06-26-v1"
TEXT_MODEL_DIMENSIONS = 768

VISUAL_MODEL_NAME = "google/siglip-so400m-patch14-384"
VISUAL_MODEL_VERSION = "2026-06-16-v1"
VISUAL_MODEL_DIMENSIONS = 768

RERANKER_MODEL_NAME = "BAAI/bge-reranker-v2-m3"
RERANKER_MODEL_VERSION = ""

SEGMENT_UNDERSTANDING_MODEL_NAME = "gemma3:1b"
SEGMENT_UNDERSTANDING_MODEL_VERSION = ""

CLAP_MODEL_NAME = "laion/clap-htsat-fused"
CLAP_MODEL_VERSION = "2026-06-26-v1"
CLAP_MODEL_DIMENSIONS = 512

WHISPER_MODEL_NAME = "openai/whisper-large-v3-turbo"
WHISPER_MODEL_VERSION = ""

