package cliprender

// plan.go owns ClipRenderPlanV1 — the fully-resolved, sealed contract handed
// to the RenderingGen/Chronon render boundary (feature spec §2). Every business selection
// (which watermark, which background, which subtitles, which codec, where the
// output lands) is made HERE by PipelineGen before the render worker is
// invoked; RenderingGen/Chronon only execute the plan verbatim.
//
// The plan is deterministic: the same resolved inputs always produce the same
// sealed PlanSHA256. Validation is fail-closed — a drifted hash, a missing
// path, or an unresolved block rejects the plan before any process starts.

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/Marcuss-ops/PipelineGen/internal/kernel/digest"
	scriptpkg "github.com/Marcuss-ops/PipelineGen/internal/kernel/script"
	"strings"
)

// PlanVersion is the canonical version of the clip render plan contract.
const PlanVersion = "clip-render-plan.v1"

var (
	// ErrInvalidClipPlan wraps every structural validation failure.
	ErrInvalidClipPlan = errors.New("invalid clip render plan")
	// ErrClipPlanDrift is returned when PlanSHA256 does not match the plan
	// content (tamper / partial-mutation detection, mirror of
	// render.ErrPlanDrift).
	ErrClipPlanDrift = errors.New("clip render plan hash mismatch")
)

// PlanSource is the fully-resolved source clip. The render worker never
// resolves the source; it reads exactly these bytes at this path.
type PlanSource struct {
	AssetID string `json:"asset_id"`
	Path    string `json:"path"`
	SHA256  string `json:"sha256"`
}

// PlanBackground is the resolved background. Mode is one of none,
// blur_source, asset. Path/SHA256 are populated ONLY for mode=asset — the
// render worker derives the blurred background from the source itself for
// blur_source.
type PlanBackground struct {
	Mode    string `json:"mode"`
	AssetID string `json:"asset_id,omitempty"`
	Path    string `json:"path,omitempty"`
	SHA256  string `json:"sha256,omitempty"`
}

// PlanWatermark is the resolved watermark overlay. Position/opacity/margin
// are business selections resolved here — the render worker applies them
// verbatim.
// Style carries the caller's visual overrides (size, color, shadow,
// transition) using the canonical kernel/script shape.
type PlanWatermark struct {
	Text     string                          `json:"text,omitempty"`
	AssetID  string                          `json:"asset_id"`
	Path     string                          `json:"path"`
	SHA256   string                          `json:"sha256"`
	Position string                          `json:"position"`
	Opacity  float64                         `json:"opacity"`
	MarginPX int                             `json:"margin_px"`
	Style    *scriptpkg.VideoVisualStyleSpec `json:"style,omitempty"`
}

// PlanSubtitles references the already-compiled deterministic ASS artifact.
// Mode is burn | sidecar; burn lowers the cues into GPU text layers inside
// the single Chronon render pass, sidecar ships the ASS alongside the
// output. The ASS content is NEVER regenerated by the render worker.
type PlanSubtitles struct {
	Mode    string `json:"mode"`
	StyleID string `json:"style_id,omitempty"`
	Path    string `json:"path"`
	SHA256  string `json:"sha256"`
	Cues    []Cue  `json:"cues,omitempty"`
	// Style carries the caller's subtitle visual overrides (color, size,
	// shadow, transition) using the canonical kernel/script shape.
	Style *scriptpkg.VideoVisualStyleSpec `json:"style,omitempty"`
}

// PlanOutput is the resolved VeloxEditing output contract. The render worker
// must produce exactly this container/codec/pixel/resolution/fps — no codec
// decisions.
type PlanOutput struct {
	ContractID             string `json:"contract_id"`
	Container              string `json:"container"`
	VideoCodec             string `json:"video_codec"`
	VideoProfile           string `json:"video_profile,omitempty"`
	PixelFormat            string `json:"pixel_format"`
	Width                  int    `json:"width"`
	Height                 int    `json:"height"`
	FPSNum                 int    `json:"fps_num"`
	FPSDen                 int    `json:"fps_den"`
	ForegroundScalePercent int    `json:"foreground_scale_percent,omitempty"`
}

// PlanAudio is the resolved audio policy. Mode copy_if_compatible means the
// render worker copies the source audio stream verbatim when it already
// satisfies the contract; transcode means exactly one certified conversion.
// The contract values pin what "compatible" means.
type PlanAudio struct {
	Mode       string `json:"mode"`
	Codec      string `json:"codec"`
	SampleRate int    `json:"sample_rate"`
	Channels   int    `json:"channels"`
}

// ClipRenderPlanV1 is the canonical sealed render contract. It is the exact
// JSON handed to the RenderingGen/Chronon boundary. Chronon makes NO business
// selections: every field is final.
type ClipRenderPlanV1 struct {
	Version    string          `json:"version"`
	RunID      string          `json:"run_id"`
	DurationMS int64           `json:"duration_ms,omitempty"`
	Source     PlanSource      `json:"source"`
	Background *PlanBackground `json:"background,omitempty"`
	Watermark  *PlanWatermark  `json:"watermark,omitempty"`
	Subtitles  *PlanSubtitles  `json:"subtitles,omitempty"`
	Output     PlanOutput      `json:"output"`
	Audio      PlanAudio       `json:"audio"`
	OutputPath string          `json:"output_path"`
	PlanSHA256 string          `json:"plan_sha256"`
}

// CompileInput is the fully-resolved input set for Compile. Every value comes
// from the parallel preparation phase (+ the compiled ASS artifact); Compile
// never resolves anything itself.
type CompileInput struct {
	RunID          string
	Source         *MaterializedAsset
	DurationMS     int64
	Watermark      *MaterializedAsset // nil when disabled
	WatermarkSpec  *WatermarkSpec     // normalized request watermark block; the SINGLE owner of watermark text/position/opacity/margin/style. A text-only watermark is WatermarkSpec.Text with Watermark == nil.
	Background     *MaterializedAsset // the materialized background asset; non-nil ONLY for mode=asset
	BackgroundMode string             // request-level background mode (none | blur_source | asset); empty falls back to none/asset from Background
	Subtitles      *SubtitleArtifact  // nil when disabled
	// SubtitlesStyle is the caller's subtitle visual override block (canonical
	// kernel/script shape). Nil means the compiled ASS style applies verbatim.
	SubtitlesStyle         *scriptpkg.VideoVisualStyleSpec
	Cues                   []Cue
	Contract               *ResolvedContract
	AudioMode              string
	OutputPath             string
	ForegroundScalePercent int
}

// Compile builds the sealed plan from the resolved inputs. Fail-closed: any
// missing input (nil source, nil contract, empty output path) is a typed
// error — the plan is never partially resolved.
func Compile(in CompileInput) (ClipRenderPlanV1, error) {
	if in.RunID == "" {
		return ClipRenderPlanV1{}, fmt.Errorf("%w: run_id is required", ErrInvalidClipPlan)
	}
	if in.Source == nil || in.Source.LocalPath == "" || !isSHA256Hex(in.Source.SHA256) {
		return ClipRenderPlanV1{}, fmt.Errorf("%w: source path + sha256 are required", ErrInvalidClipPlan)
	}
	if in.Contract == nil {
		return ClipRenderPlanV1{}, fmt.Errorf("%w: output contract is required", ErrInvalidClipPlan)
	}
	if strings.TrimSpace(in.OutputPath) == "" {
		return ClipRenderPlanV1{}, fmt.Errorf("%w: output_path is required", ErrInvalidClipPlan)
	}
	switch in.AudioMode {
	case AudioModeCopyIfCompatible, AudioModeTranscode:
	default:
		return ClipRenderPlanV1{}, fmt.Errorf("%w: audio mode must be copy_if_compatible or transcode (got %q)", ErrInvalidClipPlan, in.AudioMode)
	}

	plan := ClipRenderPlanV1{
		Version:    PlanVersion,
		RunID:      in.RunID,
		DurationMS: in.DurationMS,
		Source: PlanSource{
			AssetID: in.Source.AssetID,
			Path:    in.Source.LocalPath,
			SHA256:  in.Source.SHA256,
		},
		Output: PlanOutput{
			ContractID:             in.Contract.ContractID,
			Container:              in.Contract.Container,
			VideoCodec:             in.Contract.VideoCodec,
			VideoProfile:           in.Contract.VideoProfile,
			PixelFormat:            in.Contract.PixelFormat,
			Width:                  in.Contract.Width,
			Height:                 in.Contract.Height,
			FPSNum:                 in.Contract.FPSNum,
			FPSDen:                 in.Contract.FPSDen,
			ForegroundScalePercent: normalizeForegroundScale(in.ForegroundScalePercent),
		},
		Audio: PlanAudio{
			Mode:       in.AudioMode,
			Codec:      in.Contract.AudioCodec,
			SampleRate: in.Contract.SampleRate,
			Channels:   in.Contract.Channels,
		},
		OutputPath: strings.TrimSpace(in.OutputPath),
	}

	// Background mode is a request-level business selection resolved here;
	// blur_source carries no asset block (the renderer derives the blurred background
	// from the source itself), mode=asset requires the verified materialized
	// asset, and none requires no asset.
	backgroundMode := in.BackgroundMode
	if backgroundMode == "" {
		if in.Background == nil {
			backgroundMode = BackgroundModeNone
		} else {
			backgroundMode = BackgroundModeAsset
		}
	}
	switch backgroundMode {
	case BackgroundModeNone:
		if in.Background != nil {
			return ClipRenderPlanV1{}, fmt.Errorf("%w: background mode=none must not carry an asset", ErrInvalidClipPlan)
		}
		plan.Background = &PlanBackground{Mode: BackgroundModeNone}
	case BackgroundModeBlurSource:
		if in.Background != nil {
			return ClipRenderPlanV1{}, fmt.Errorf("%w: background mode=blur_source must not carry an asset", ErrInvalidClipPlan)
		}
		plan.Background = &PlanBackground{Mode: BackgroundModeBlurSource}
	case BackgroundModeAsset:
		if in.Background == nil || in.Background.LocalPath == "" || !isSHA256Hex(in.Background.SHA256) {
			return ClipRenderPlanV1{}, fmt.Errorf("%w: background mode=asset requires the materialized asset with path + sha256", ErrInvalidClipPlan)
		}
		plan.Background = &PlanBackground{
			Mode:    BackgroundModeAsset,
			AssetID: in.Background.AssetID,
			Path:    in.Background.LocalPath,
			SHA256:  in.Background.SHA256,
		}
	default:
		return ClipRenderPlanV1{}, fmt.Errorf("%w: invalid background mode %q", ErrInvalidClipPlan, backgroundMode)
	}

	if in.Watermark != nil || (in.WatermarkSpec != nil && strings.TrimSpace(in.WatermarkSpec.Text) != "") {
		if in.Watermark != nil && in.Watermark.LocalPath == "" {
			return ClipRenderPlanV1{}, fmt.Errorf("%w: watermark asset requires path + sha256", ErrInvalidClipPlan)
		}
		// WatermarkSpec is the single source for text/position/opacity/margin
		// and style; there is no second text spelling.
		wm := in.WatermarkSpec
		if wm == nil {
			wm = &WatermarkSpec{Position: PositionTopRight, Opacity: 1.0}
		}
		text := strings.TrimSpace(wm.Text)
		if text == "" && (in.Watermark == nil || !isSHA256Hex(in.Watermark.SHA256)) {
			return ClipRenderPlanV1{}, fmt.Errorf("%w: watermark asset requires path + sha256", ErrInvalidClipPlan)
		}
		assetID, path, sha := "", "", ""
		if in.Watermark != nil {
			assetID, path, sha = in.Watermark.AssetID, in.Watermark.LocalPath, in.Watermark.SHA256
		}
		plan.Watermark = &PlanWatermark{
			Text:     text,
			AssetID:  assetID,
			Path:     path,
			SHA256:   sha,
			Position: wm.Position,
			Opacity:  wm.Opacity,
			MarginPX: wm.MarginPX,
			Style:    cloneVisualStyle(wm.Style),
		}
	}

	if in.Subtitles != nil {
		if in.Subtitles.LocalPath == "" || !isSHA256Hex(in.Subtitles.SHA256) {
			return ClipRenderPlanV1{}, fmt.Errorf("%w: subtitle ASS requires path + sha256", ErrInvalidClipPlan)
		}
		plan.Subtitles = &PlanSubtitles{
			Mode:    in.Subtitles.Mode,
			StyleID: in.Subtitles.StyleID,
			Path:    in.Subtitles.LocalPath,
			SHA256:  in.Subtitles.SHA256,
			Cues:    append([]Cue(nil), in.Cues...),
			Style:   cloneVisualStyle(in.SubtitlesStyle),
		}
	}

	if err := plan.Seal(); err != nil {
		return ClipRenderPlanV1{}, err
	}
	if err := plan.Validate(); err != nil {
		return ClipRenderPlanV1{}, err
	}
	return plan, nil
}

func normalizeForegroundScale(value int) int {
	if value == 0 {
		return 100
	}
	return value
}

// cloneVisualStyle copies the canonical visual style block so the sealed
// plan never shares a pointer with the caller's mutable request. A nil input
// stays nil (no empty block on the wire).
func cloneVisualStyle(in *scriptpkg.VideoVisualStyleSpec) *scriptpkg.VideoVisualStyleSpec {
	if in == nil {
		return nil
	}
	out := *in
	if in.Shadow != nil {
		shadow := *in.Shadow
		out.Shadow = &shadow
	}
	if in.TransitionIn != nil {
		transition := *in.TransitionIn
		out.TransitionIn = &transition
	}
	return &out
}

// Seal computes the deterministic PlanSHA256 over the plan content.
func (p *ClipRenderPlanV1) Seal() error {
	if p == nil {
		return fmt.Errorf("%w: nil plan", ErrInvalidClipPlan)
	}
	hash, err := p.Hash()
	if err != nil {
		return err
	}
	p.PlanSHA256 = hash
	return nil
}

// Hash computes the deterministic digest with PlanSHA256 zeroed (so sealing
// is idempotent and drift is detectable).
func (p ClipRenderPlanV1) Hash() (string, error) {
	copyPlan := p
	copyPlan.PlanSHA256 = ""
	b, err := json.Marshal(copyPlan)
	if err != nil {
		return "", fmt.Errorf("hash clip render plan: %w", err)
	}
	sum := digest.SHA256Bytes(b)
	return sum, nil
}

// Validate enforces the plan contract fail-closed: identity, resolved blocks,
// matching hashes, valid enum values, and a PlanSHA256 that matches the
// content (tamper / partial-mutation detection).
func (p ClipRenderPlanV1) Validate() error {
	if p.Version != PlanVersion || p.RunID == "" || p.OutputPath == "" {
		return fmt.Errorf("%w: version, run_id, or output_path missing", ErrInvalidClipPlan)
	}
	if p.Source.AssetID == "" || p.Source.Path == "" || !isSHA256Hex(p.Source.SHA256) {
		return fmt.Errorf("%w: source must carry asset_id, path, and sha256", ErrInvalidClipPlan)
	}
	if p.Output.ContractID == "" || p.Output.Container == "" || p.Output.VideoCodec == "" ||
		p.Output.PixelFormat == "" || p.Output.Width <= 0 || p.Output.Height <= 0 ||
		p.Output.FPSNum <= 0 || p.Output.FPSDen <= 0 {
		return fmt.Errorf("%w: output contract is incomplete", ErrInvalidClipPlan)
	}
	if p.Output.ForegroundScalePercent != 0 && (p.Output.ForegroundScalePercent < 1 || p.Output.ForegroundScalePercent > 100) {
		return fmt.Errorf("%w: foreground_scale_percent must be within [1,100]", ErrInvalidClipPlan)
	}
	switch p.Audio.Mode {
	case AudioModeCopyIfCompatible, AudioModeTranscode:
	default:
		return fmt.Errorf("%w: invalid audio mode %q", ErrInvalidClipPlan, p.Audio.Mode)
	}
	if p.Audio.Codec == "" || p.Audio.SampleRate <= 0 || p.Audio.Channels <= 0 {
		return fmt.Errorf("%w: audio contract is incomplete", ErrInvalidClipPlan)
	}

	if p.Background != nil {
		switch p.Background.Mode {
		case BackgroundModeNone, BackgroundModeBlurSource:
			// No asset required.
		case BackgroundModeAsset:
			if p.Background.AssetID == "" || p.Background.Path == "" || !isSHA256Hex(p.Background.SHA256) {
				return fmt.Errorf("%w: background mode=asset requires asset_id, path, and sha256", ErrInvalidClipPlan)
			}
		default:
			return fmt.Errorf("%w: invalid background mode %q", ErrInvalidClipPlan, p.Background.Mode)
		}
	}

	if p.Watermark != nil {
		if strings.TrimSpace(p.Watermark.Text) == "" && (p.Watermark.AssetID == "" || p.Watermark.Path == "" || !isSHA256Hex(p.Watermark.SHA256)) {
			return fmt.Errorf("%w: watermark requires asset_id, path, and sha256", ErrInvalidClipPlan)
		}
		switch p.Watermark.Position {
		case PositionTopLeft, PositionTopRight, PositionCenter, PositionBottomLeft, PositionBottomRight:
		default:
			return fmt.Errorf("%w: invalid watermark position %q", ErrInvalidClipPlan, p.Watermark.Position)
		}
		if p.Watermark.Opacity < 0 || p.Watermark.Opacity > 1 {
			return fmt.Errorf("%w: watermark opacity must be within [0,1]", ErrInvalidClipPlan)
		}
		if p.Watermark.MarginPX < 0 {
			return fmt.Errorf("%w: watermark margin_px must be >= 0", ErrInvalidClipPlan)
		}
	}

	if p.Subtitles != nil {
		switch p.Subtitles.Mode {
		case SubtitlesModeBurn, SubtitlesModeSidecar:
		default:
			return fmt.Errorf("%w: invalid subtitle mode %q", ErrInvalidClipPlan, p.Subtitles.Mode)
		}
		if p.Subtitles.Path == "" || !isSHA256Hex(p.Subtitles.SHA256) {
			return fmt.Errorf("%w: subtitles require an ASS path + sha256", ErrInvalidClipPlan)
		}
	}

	expected, err := p.Hash()
	if err != nil {
		return err
	}
	if p.PlanSHA256 != expected {
		return fmt.Errorf("%w: got %q want %q", ErrClipPlanDrift, p.PlanSHA256, expected)
	}
	return nil
}

func isSHA256Hex(value string) bool {
	if len(value) != digest.SHA256HexLength {
		return false
	}
	decoded, err := hex.DecodeString(value)
	return err == nil && strings.ToLower(value) == value && len(decoded) == digest.SHA256HexLength/2
}
