#!/usr/bin/env bash
# 00_wave_tracker.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Wave-tracker allowlist consultation (PR-CI-WAVE-ALLOWLIST, July 2026) ──
# Text-based extraction of `id: PR-*` lines from architecture/current.yaml
# whose entry has `status: pending` or `status: in_progress` OR whose entry
# is a `PRE-EXISTING-*-2026-07-04` parent. Per godlike/07 no-fake-availability:
# the wave-tracker file is currently UNPARSEABLE (3+ indent cascade bugs at
# lines ~1582, ~2852, ~2996), so we use a TEXT-BASED FALLBACK rather than
# `yaml.safe_load`. The fallback is the canonical extraction strategy
# (mirrors how the rest of the script uses awk / rg / sed line-by-line).
#
# This is an ADDITIVE informational layer (godlike/07 minimum-blast-radius):
# no existing check's exit-1 semantics change. The baseline log becomes a
# stable pass-rate count instead of an all-violations dump. Future per-check
# integration can opt-in by calling `is_known_acceptable <PR_ID>`.
KNOWN_ACCEPTABLE_IDS=""
extract_known_acceptable_ids_from_yaml() {
    # PR-REMOVE-CI-AWK-SED-FALLBACKS (2026-07-04): replaced the 132-line
    # bash state-machine fallback (which compensated for the broken YAML)
    # with a ~15-line Python heredoc that uses yaml.safe_load. After
    # PR-FIX-YAML-PARSE-LINE-1551 shipped, the YAML is fully parseable,
    # so the text-based fallback is no longer needed.
    #
    # The replacement preserves the canonical external contract:
    #   - sets KNOWN_ACCEPTABLE_IDS to newline-separated ID list
    #   - empty on missing file OR parse error (godlike/07 fail-closed default)
    #   - accepts:
    #     - top-level parents: PRE-EXISTING-* (always) OR status pending/in_progress
    #     - children of PRE-EXISTING-* parents (always)
    #     - children of pending/in_progress parents
    #
    # Per godlike/06 SSOT: the wave-tracker is the SOLE source of truth for
    # PR/issue status. Per godlike/07 minimum-blast-radius: the Python
    # heredoc is ~15 lines (vs 132 lines of bash state-machine); the
    # output format (newline-separated sorted deduped IDs) is byte-identical
    # to the previous implementation, so callers (is_known_acceptable +
    # WAVE_BASELINE_SIZE) need no changes.
    local yaml_path="${REPO_ROOT:-$(pwd)}/architecture/current.yaml"
    KNOWN_ACCEPTABLE_IDS=""
    if [ ! -f "${yaml_path}" ]; then
        return 0
    fi
    KNOWN_ACCEPTABLE_IDS=$(python3 -c '
import sys, yaml
try:
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        docs = yaml.safe_load(f)
    accepted = set()
    for p in (docs if isinstance(docs, list) else []):
        if not isinstance(p, dict):
            continue
        pid, pst = str(p.get("id", "")), p.get("status", "")
        if pid.startswith("PRE-EXISTING-") or pst in ("pending", "in_progress"):
            if pid:
                accepted.add(pid)
            for child in (p.get("linked_issues") or []):
                if isinstance(child, dict) and child.get("id"):
                    accepted.add(str(child["id"]))
    for val in sorted(accepted):
        print(val)
except (yaml.YAMLError, OSError, UnicodeDecodeError):
    pass
' "${yaml_path}" 2>/dev/null || true)
    # godlike/07 no-fake-availability: even if the YAML is unparseable,
    # the silent failure path is preserved (empty KNOWN_ACCEPTABLE_IDS
    # means all violations become "new" until the wave-tracker is
    # re-introduced). The previous bash state-machine had the same
    # silent-fallback contract; this Python replacement preserves it
    # 1:1. NOTE: do NOT `export` — the variable is read in the same
    # shell process (the function-call below + Check 61); child
    # processes don't need it.
}
is_known_acceptable() {
    local pr_id="${1:-}"
    [ -z "${pr_id}" ] && return 1
    [ -z "${KNOWN_ACCEPTABLE_IDS}" ] && return 1
    # Pure bash membership check on the newline-separated allowlist.
    if printf '%s\n' "${KNOWN_ACCEPTABLE_IDS}" | grep -qxF "${pr_id}"; then
        return 0
    fi
    return 1
}
# Populate the global once at script start. Any per-check opt-in can
# call is_known_acceptable <PR_ID> to consult.
extract_known_acceptable_ids_from_yaml
WAVE_BASELINE_SIZE=0
if [ -n "${KNOWN_ACCEPTABLE_IDS}" ]; then
    WAVE_BASELINE_SIZE=$(printf '%s\n' "${KNOWN_ACCEPTABLE_IDS}" | wc -l | awk '{print $1+0}')
fi

# Resolve REPO_ROOT once so the migration-uniqueness lint below works from
# any cwd (CI runners, IDE hook invocations, manual bash). BASH_SOURCE is
# always the script's own absolute path under `bash script.sh` — the only
# case where it's empty / unset is when the script is being read via
# process substitution (`bash <(curl ...)`) or `bash -c "source ..."` from
# a parent shell, which we refuse to silently misroute (a wrong-resolution
# REPO_ROOT would silently scan the wrong dir and emit false-negative
# passes). Fail loud and let the operator fix the invocation.
