#!/usr/bin/env bash
# 01_self_check.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Self-check mode (TODO 16, June 2026) ──────────────────────────────
# When invoked with `--self-check`, the script runs each check's regex
# against its corresponding fixture in tests/fixtures/zero_legacy/ and
# verifies the regex catches the forbidden pattern. Exits 0 only if
# every check's pattern still matches its fixture; exits 1 if any
# fixture is missing or any pattern is broken.
#
# Self-check is a UNIT TEST FOR THE REGEXES — it does NOT scan the
# production tree. The standard mode (no flag) is the production gate.
if [ "${1:-}" = "--self-check" ]; then
    FIXTURE_DIR="${REPO_ROOT}/tests/fixtures/zero_legacy"
    if [ ! -d "${FIXTURE_DIR}" ]; then
        echo "FAIL: fixture dir ${FIXTURE_DIR} does not exist (run from repo root)" >&2
        exit 1
    fi

    # Format: name|pattern|fixture_file. Pattern uses ripgrep -E syntax.
    # The fixture MUST contain the forbidden pattern; rg must match.
    check_defs=(
        "Check 8 (SetOutboxHandler/SetMediasearchHandler after construction)|\\.SetOutboxHandler\\(|check_08_setter.go"
        "Check 8 (SetOutboxHandler/SetMediasearchHandler after construction)|\\.SetMediasearchHandler\\(|check_08_setter.go"
        "Check 9 (nil-dispatcher silent fallback)|dispatcher\\s*==\\s*nil\\s*\\{[^}]*return\\s+nil\\b|check_09_nil_dispatcher.go"
        "Check 10 (asset-repo Upsert outside allowlist)|\\.Upsert\\(ctx,|check_10_upsert.go"
        "Check 11 (event_key constructed with random UUID, inline)|eventKey[^\\n]*uuid\\.NewString|check_11_uuid_event_key.go"
        "Check 11 (event_key constructed with random UUID, multiline reverse)|eventID[^\\n]*=\\s*uuid\\.NewString[^\\n]*\\n(?:[^\\n]*\\n){0,3}[^\\n]*eventKey[^\\n]*=[^\\n]*\\beventID\\b|check_11_uuid_event_key.go"
        "Check 11 (event_key constructed with random UUID, multiline forward)|eventKey[^\\n]*\\n(?:[^\\n]*\\n){0,3}[^\\n]*eventID[^\\n]*=\\s*uuid\\.NewString|check_11_uuid_event_key.go"
        "Check 12 (payload_mapper legacy lifecycle_state fallback)|\"lifecycle_state\":\\s*\\w+\\.Status|check_12_payload_mapper_status.go"
        "Check 13 (ListAssetsForReconcile placeholder)|wired as build-time placeholder|check_13_listassets_placeholder.go"
        "Check 14 (BuildPayload legacy status key)|\"status\":\\s*\\w+\\.|check_14_buildpayload_status_key.go"
        "Check 15 (qdrant.NewClient construction)|qdrant\\.NewClient\\(&qdrant\\.Config\\{|check_15_qdrant_config_apikey.go"
        "Check 50 (forbid void Register* signature)|func \\(\\w+ \\*?\\w+\\) [A-Z][A-Za-z0-9_]*[Rr]egister\\([^)]*\\bjobs\\.?Service[^)]*\\)[[:space:]]*\\{|check_50_void_register.go"
        "Check 57 (forbid ports.ScriptRecord literal outside canonical allowlist)|ports\\.ScriptRecord\\{|check_57_scriptrecord_prod_literal.go"
        "Check 55 (forbid legacy Template writes outside canonical allowlist)|Template:\\s|check_55_template_timeline_literal.go"
        "Check 55 (forbid legacy TimelineJSON writes outside canonical allowlist)|TimelineJSON:\\s|check_55_template_timeline_literal.go"
        "Check 60 (forbid t.Skip without godlike/07 honest-limitation comment)|t\\.Skip[a-zA-Z]*\\(|check_60_t_skip.go"
        "Check 62 (forbid RequireAdminToken inline in feature routes)|RequireAdminToken|check_62_inline_middleware.go"
        "Check 62 (forbid extractHeaderToken inline in feature routes)|extractHeaderToken|check_62_inline_middleware.go"
        "Check 62 (forbid EnableAuth inline in feature routes)|EnableAuth|check_62_inline_middleware.go"
        "Check 62 (forbid AdminTokenProvider inline in feature routes)|AdminTokenProvider|check_62_inline_middleware.go"
    )

    failed=0
    seen_names=""
    for def in "${check_defs[@]}"; do
        IFS='|' read -r name pattern fixture <<< "${def}"
        fixture_path="${FIXTURE_DIR}/${fixture}"
        if [ ! -f "${fixture_path}" ]; then
            echo "FAIL: ${name} — fixture ${fixture} missing" >&2
            failed=1
            continue
        fi
        if rg -qU -- "${pattern}" "${fixture_path}" 2>/dev/null; then
            # De-duplicate per check (Check 8 has 2 patterns for 2 methods).
            if [[ "${seen_names}" != *"${name}"* ]]; then
                echo "PASS: ${name} — caught fixture ${fixture}"
                seen_names="${seen_names}|${name}|"
            fi
        else
            echo "FAIL: ${name} — pattern did NOT catch fixture ${fixture} (regex is broken)" >&2
            failed=1
        fi
    done

    if [ "${failed}" -gt 0 ]; then
        echo "" >&2
        echo "Self-check FAILED: at least one regex does not catch its fixture." >&2
        echo "Fix the regex OR update the fixture so the forbidden pattern is present." >&2
        exit 1
    fi
    # Count unique check names (Check 8 has 2 patterns for 2 methods; Check 11
    # has 3 patterns for 3 shapes; etc.) so the summary is accurate. Use
    # bash parameter expansion (${def%%|*}) instead of awk to avoid breakage
    # if a check name ever contains a `|` character.
    unique_names=()
    for def in "${check_defs[@]}"; do
        name="${def%%|*}"
        if [[ " ${unique_names[*]} " != *" ${name} "* ]]; then
            unique_names+=("$name")
        fi
    done
    unique_count=${#unique_names[@]}
    pattern_count=${#check_defs[@]}
    # Count fixture files dynamically (ls instead of hardcoded "7") so the
    # summary stays accurate when new fixtures are added.
    fixture_count=$(ls -1 "${FIXTURE_DIR}"/*.go 2>/dev/null | wc -l)
    echo "All self-checks passed (${pattern_count} patterns / ${unique_count} unique checks / ${fixture_count} fixtures)."
    exit 0
fi
