#!/usr/bin/env bash
# 10_check_7_asset_mutation_bypass_audit_wave_22_pr_4_june_2026.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 7: Asset-Mutation Bypass Audit (Wave 22 PR-4, June 2026) ──
# Runs the four rg queries from docs/migrations/bypass_audit_<date>.md and
# subtracts the per-file allowlist at docs/migrations/admin-sql-allowlist.txt
# using `comm -13`. Any non-allowlisted production hit fails the gate.
#
# This is the wire-up for the canonical AssetMutationDispatcher SSOT
# (internal/application/assets/mutations/dispatcher.go) — Wave 22 tasks
# 2/3/5 migrate the "production — must use dispatcher" files out from
# under the allowlist, so this gate tightens with each migration PR.
#
# The allowlist is the SINGLE SOURCE OF TRUTH for what bypass-survives.
# Adding/removing a row must ship in the same PR as the corresponding
# code change. See AGENTS.md §"Agenter Workflow" for the 1-PR rule.
# NON-FATAL bypass-audit wrap. The file opens with `set -euo pipefail`;
# without this wrap, a non-zero exit short-circuits every subsequent
# check (Check 8 factory-only, ServiceDeps cap, engine SSOT gates,
# final archcheck). The captured exit is logged below; do NOT remove
# this wrap — every check added since Wave 22 PR-4 has implicitly
# depended on bypass-audit being NON-FATAL.
set +e
bash "${REPO_ROOT}/scripts/ci-bypass-audit.sh"
bypass_audit_rc=$?
set -e
echo "ci-bypass-audit exit code: ${bypass_audit_rc} (NON-FATAL)"

