#!/usr/bin/env bash
# 10_check_7_asset_mutation_bypass_audit_wave_22_pr_4_june_2026.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 7: Asset-Mutation Bypass Audit (Wave 22 PR-4, June 2026) ──
# Runs the four rg queries from docs/migrations/bypass_audit_<date>.md and
# subtracts the per-file allowlist at docs/migrations/admin-sql-allowlist.txt
# using `comm -13`. Any non-allowlisted production hit fails the gate.
#
# This is the wire-up for the canonical AssetMutationDispatcher SSOT
# (internal/application/assets/mutations/dispatcher.go) — Wave 22 tasks
# 2/3/5 migrate the "production — must use dispatcher" files out from
# under the allowlist, so this gate tightens with each migration PR.
#
# The allowlist is the SINGLE SOURCE OF TRUTH for what bypass-survives.
# Adding/removing a row must ship in the same PR as the corresponding
# code change. See AGENTS.md §"Agenter Workflow" for the 1-PR rule.
#
# HARD-FAIL since Azione 5 (2026-08-02): the NON-FATAL wrap was a
# workaround masking a red bypass-audit (Check A flagged 9 non-allowlisted
# .Upsert( callers). Those 9 legitimate non-media_assets repo writes are
# now grandfathered in docs/migrations/admin-sql-allowlist.txt (Bucket 5,
# owner+deadline). With the allowlist closed, any non-allowlisted hit is a
# genuine regression and MUST fail the dispatcher — the wrap is removed so
# a non-zero exit propagates under `set -euo pipefail`.
bash "${REPO_ROOT}/scripts/ci-bypass-audit.sh"
echo "ci-bypass-audit: HARD-FAIL gate green (0 non-allowlisted hits)"

