#!/usr/bin/env bash
# 11_check_8_factory_only_s3e.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 8 (factory-only, S3e, Wave 22): forbid literal map[string]*assets.ClipsRepository ──
# The canonical contract for clip-store access in production paths is the
# typed ClipRepositoryPort / ClipStorePort surface; inline
# `map[string]*assets.ClipsRepository{...}` literals are a regression to
# the pre-port days and block the architecture from migrating to alternate
# clip-store implementations (Qdrant-only, in-memory cache, mock-driven
# tests, etc.).
#
# Canonical factory sites (explicitly allowlisted):
#   - internal/platform/sqlite/assetindex/resolver.go
#   - internal/app/build_bundles_core.go
#
# Both canonical sites are composition-root concerns: they construct the
# bag of repos that the PortAdapters project onto the typed interfaces.
# Production callers (internal/application/**, internal/api/**) MUST
# consume the typed Port interface (clips.ClipRepositoryPort,
# ytports.ClipStorePort, etc.) — not the *assets.ClipsRepository
# concrete.
#
# ARCH-ALLOWLIST opt-in (mirrors Check 5): a transitional backfill or
# production test fixture that legitimately needs the literal at a
# non-production scope MUST prepend the magic marker `// ARCH-ALLOWLIST:
# factory-only` on the line preceding the literal. The marker is
# stripped from the failing-set via an awk pre-pass that drops matches
# whose preceding line carries the magic marker (window: 25 lines —
# tolerates the operator-common pattern of marker + blank line +
# literal). Per AGENTS.md §7 zero-baseline rule, new allowlist entries
# require explicit owner + deadline; the marker is the call-site
# equivalent of an allowlist row.
#
# Pattern anchors:
#   map[string]*assets.ClipsRepository{   — exact literal text
#     (rg -e uses regex escaping; \{\} is the brace literal)
# Tests are excluded via --glob '!**/*_test.go' since they may freely
# construct the literal as fixtures without affecting production
# contracts.
echo "=== Check 8 (factory-only, S3e): forbid literal map[string]*assets.ClipsRepository ==="
all_hits=$(rg -n --type go \
    -e 'map\[string\]\*assets\.ClipsRepository\{' \
    --glob '!**/*_test.go' \
    --glob '!**/platform/sqlite/assetindex/resolver.go' \
    --glob '!**/app/build_bundles_core.go' \
    internal/application internal/api 2>/dev/null \
    || true)
# Drop full-line comments AND lines preceded by the ARCH-ALLOWLIST marker
# (i.e. the preceding line of the SAME FILE carries the magic marker;
# the marker is recognised on a single-line comment OR on the line
# immediately above the literal, with a 25-line scroll-window tolerance).
literal_calls=$(printf '%s\n' "$all_hits" \
    | awk -F: '
        {
            rest = ""
            for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
            if (rest ~ /^[[:space:]]*\/\/.*ARCH-ALLOWLIST:[[:space:]]*factory-only/) {
                # Per-line accumulation: append this marker'\''s line number
                # to the file'\''s comma-separated list so multiple markers
                # in the same file BOTH persist (overwrite-avoidance —
                # mirrors Check 5 admin-only semantics).
                markers[$1] = (markers[$1] == "" ? $2 : markers[$1] "," $2)
                next
            }
            if (rest ~ /^[[:space:]]*\/\//) next
            # Check the hit against EVERY stored marker for this file
            # (any of them may own the active scroll-window).
            n = (markers[$1] == "" ? 0 : split(markers[$1], mlist, ","))
            allowed = 0
            for (mi = 1; mi <= n; mi++) {
              m = mlist[mi] + 0
              if (m > 0 && $2 + 0 >= m + 1 && $2 + 0 <= m + 25) { allowed = 1; break }
            }
            if (allowed) next
            print
        }' \
    || true)
if [ -n "$literal_calls" ]; then
    echo "FAIL: literal map[string]*assets.ClipsRepository{...} detected in production path:"
    echo "$literal_calls"
    echo ""
    echo "Fix: consume the clip-store via the typed ClipRepositoryPort (or any"
    echo "      application-level port that abstracts *assets.ClipsRepository)."
    echo "      Production callers MUST NOT construct the literal bag directly;"
    echo "      the bag lives ONLY on the canonical factory sites"
    echo "      (assetindex/resolver.go + app/build_bundles_core.go)."
    echo ""
    echo "If the literal is genuinely a transitional backfill / offline admin"
    echo "      migration (rare), prepend the magic marker on the line preceding"
    echo "      the literal:"
    echo "    // ARCH-ALLOWLIST: factory-only"
    echo "    repos := map[string]*assets.ClipsRepository{...}"
    exit 1
fi
echo "OK: no literal map[string]*assets.ClipsRepository literals in production paths"

