#!/usr/bin/env bash
# 12_check_8.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 8: forbid inline large-batch clip pagination in production paths (S1b, Wave 22) ──
# Cleanup now ALWAYS routes through the jobs system (`system.cleanup`). Any inline
# `ListClipsPaged(...NNN...)` call where NNN >= 1000 in production paths is a
# regression to the legacy per-source synchronous 10000-record pagination. The
# canonical replacement is `jobs.Enqueue(JobsEnqueueRequest{Type: "system.cleanup"...})`.
#
# Pattern anchors:
#   ListClipsPaged\(\s*<args>\s*,\s*[1-9][0-9]{3,}\b  — 4+ digit limit (1000..N)
#   ListClipsPaged by cap-of-10000 specifically:
#       ListClipsPaged\([^,]+,\s*(10000|5000|1000|100000)\b
# Tests and the canonical callers upstream of the outbox dispatcher
# (internal/platform/sqlite/assets/clips_repository.go) are
# allowlisted because the SQL layer legitimately uses large batches for
# snapshots / bulk maintenance; the lint targets the production-API+App layer
# where the legacy inline fallback lived.
#
# ARCH-ALLOWLIST opt-in: prepend `// ARCH-ALLOWLIST: admin-migration` on the
# line preceding the call site to opt into the allowlist (mirrors Check 5).
echo "=== Check 8: forbid inline ListClipsPaged(>=1000) in production paths (S1b, Wave 22) ==="
all_hits=$(rg -n --type go \
    -e "ListClipsPaged\([^,]+,\s*[1-9][0-9]{3,}\b" \
    --glob '!**/*_test.go' \
    --glob '!**/platform/sqlite/**' \
    internal/application internal/api 2>/dev/null \
    || true)
literal_calls=$(printf '%s\n' "$all_hits" \
    | awk -F: '
        BEGIN { prev = "" }
        {
            rest = ""
            for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
            if (rest ~ /^[[:space:]]*\/\/.*ARCH-ALLOWLIST:[[:space:]]*admin-migration/) {
                # Per-line accumulation: append this marker'\''s line number
                # to the file'\''s comma-separated list so multiple markers
                # in the same file BOTH persist (overwrite-avoidance —
                # mirrors Check 5 admin-only semantics).
                markers[$1] = (markers[$1] == "" ? $2 : markers[$1] "," $2)
                next
            }
            if (rest ~ /^[[:space:]]*\/\//) next
            # Check the hit against EVERY stored marker for this file
            # (any of them may own the active scroll-window).
            n = (markers[$1] == "" ? 0 : split(markers[$1], mlist, ","))
            allowed = 0
            for (mi = 1; mi <= n; mi++) {
              m = mlist[mi] + 0
              if (m > 0 && $2 + 0 >= m + 1 && $2 + 0 <= m + 25) { allowed = 1; break }
            }
            if (allowed) next
            print
        }' \
    || true)
if [ -n "$literal_calls" ]; then
    echo "FAIL: inline ListClipsPaged(>=1000) detected in production path:"
    echo "$literal_calls"
    echo ""
    echo "Fix: route bulk pagination through the jobs system (system.cleanup)"
    echo "or the canonical ClipOpsService.Cleanup entry point. The legacy"
    echo "synchronous 10000-record fallback is removed (S1b, Wave 22 task 5)."
    echo ""
    echo "If the call is genuinely admin migration / backfill, prepend the"
    echo "marker comment on the preceding line:"
    echo "    // ARCH-ALLOWLIST: admin-migration"
    echo "    repo.ListClipsPaged(ctx, src, 10000, offset)"
    exit 1
fi
echo "OK: no inline ListClipsPaged(>=1000) calls in production paths"
