#!/usr/bin/env bash
# 13_check_23.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 23: ServiceDeps / Deps field-count cap (PR-D, Wave 22 §D3) ─────
# The canonical `Deps` struct passed to a service's NewService MUST NOT
# exceed 8 fields. Sub-groups (e.g. artlist.ServicePorts + ServiceDependencies
# embedded into artlist.ServiceDeps) count the embedded Promotion fields
# toward the cap — the cap is the number of fields a maintainer sees on the
# struct, not the leaf-group member count.
#
# The cap is enforced on struct types whose declared name matches
# `ServiceDeps` OR `Deps` (case-sensitive, exported); plain `*Config`
# / `*Options` / `*Args` / `*Params` / `*Inputs` types are NOT
# gated — the cap is specific to ServiceDeps + Deps because those are
# the two names the PR-D spec calls out.
#
# Pattern anchors:
#   ^type ServiceDeps struct { ... }   — captures the post-brace block
#   ^type Deps struct { ... }          — captures the post-brace block
#
# Field count is computed by ignoring blank lines, comment lines starting
# with `//` or `/*`, the closing `}` brace. Embedded-type lines (those
# whose name matches a struct type identifier) count as 1 field — we do
# NOT recurse into the embedded struct's fields because the spec cap is
# the visible top-level field lines, mirroring what a maintainer sees.
#
# Allowlist: docs/migrations/deps-struct-allowlist.txt lists one
# `<package>:<TypeName>` per line for transitional exceptions. Per
# AGENTS.md §8 ARCHITECTURE-CI-GATES zero-baseline rule, every new
# entry requires explicit owner + deadline. Today the file has exactly
# one entry (artlist:ServiceDeps) grandfathered via PR2.6/2.7.
echo "=== Check 23: ServiceDeps / Deps field-count cap (PR-D, Wave 22 §D3) ==="
max_fields=8
# Collect every `(package, TypeName, file, fieldcount)` line into TSV.
decls=$(while IFS= read -r -d '' f; do
  case "$f" in
    *) continue ;;
  esac
  case "$f" in
    *_test.go) continue ;;
  esac
  # extract package name (Check 23, parallel fix to 8fa8a501's Check 5 hardening).
  # Canonical `awk $2` field-extraction; the prior `${pkg_line#package }` shell-strip
  # collapses to empty pkg on non-canonical separators and would surface the same
  # `(count=N in same package)` false-positive shape here too.
  pkg=$(awk '/^package[[:space:]]+/ {print $2; exit}' "$f" 2>/dev/null || true)
  [ -z "$pkg" ] && continue
  awk -v pkg="$pkg" -v file="$f" -v max="$max_fields" '
    function flush_field(    line, lines, n, i, k) {
      if (in_name == "") return
      n = split(fields, lines, "\n")
      k = 0
      for (i = 1; i <= n; i++) {
        line = lines[i]
        if (line == "") continue
        if (line ~ /^[[:space:]]*\/\//) continue
        if (line ~ /^[[:space:]]*\/\*/) continue
        if (line == "}") continue
        k++
      }
      if (k > max) {
        printf("%s\t%s\t%d\t%s\n", pkg, in_name, k, file)
      }
      in_name = ""; fields = ""
    }
    /^type[[:space:]]+(ServiceDeps|Deps)[[:space:]]+struct/ {
      flush_field()
      s = $0
      sub(/^type[[:space:]]+/, "", s)
      if (match(s, /^(ServiceDeps|Deps)/)) {
        in_name = substr(s, RSTART, RLENGTH)
      }
      next
    }
    in_name != "" {
      fields = fields "\n" $0
      if ($0 ~ /^}/) { flush_field() }
    }
  ' "$f" 2>/dev/null
done < <(find internal/application -name '*.go' -not -name '*_test.go' -print0 2>/dev/null || true) || true)

# Apply allowlist (drop package:TypeName pairs listed in the allowlist file).
allowed_keys=""
if [ -f "docs/migrations/deps-struct-allowlist.txt" ]; then
  allowed_keys=$(grep -vE '^[[:space:]]*(#|$)' docs/migrations/deps-struct-allowlist.txt 2>/dev/null \
    | awk '{print $1}' | sort -u | paste -sd'|' - || true)
fi

violations=$(printf '%s\n' "$decls" | awk -v allow="$allowed_keys" -F'\t' '
  BEGIN {
    n = split(allow, a, "|")
    for (i = 1; i <= n; i++) if (a[i] != "") allowed[a[i]] = 1
  }
  NF >= 3 {
    key = $1 ":" $2
    if (key in allowed) next
    printf("  %s.%s  (fields=%d, max=8)\n    file: %s\n", $1, $2, $3, $4)
  }
' || true)

if [ -n "$violations" ]; then
  echo "FAIL: ServiceDeps / Deps struct(s) exceeding the 8 visible field-line cap:"
  echo "$violations"
  echo ""
  echo "Fix: split a Deps struct into sub-deps groups (e.g. StorageDeps,"
  echo "      MediaDeps, ProviderDeps) so each top-level field is itself"
  echo "      a typed bundle. Embedded-type lines (e.g. Storage StorageDeps)"
  echo "      count as 1 visible line — promote via sub-structs to stay under"
  echo "      the cap. See docs/migrations/deps-struct-allowlist.txt for the"
  echo "      interpretation note on embedded-type field promotion."
  echo ""
  echo "If a Deps struct legitimately needs >8 visible fields under a transitional"
  echo "      baseline, add an entry to docs/migrations/deps-struct-allowlist.txt with"
  echo "      '<package>:<TypeName>   # rationale + owner + deadline'. Per AGENTS.md"
  echo "      §8 zero-baseline rule, the entry MUST carry owner + deadline."
  exit 1
fi
echo "Check 23: 0 ServiceDeps/Deps structs exceeding the 8 visible field-line cap"
