#!/usr/bin/env bash
# 14_divider_pr_9_anti_regression_gates_cleanup_contract_june_202.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── PR 9 anti-regression gates (Cleanup CONTRACT, June 2026) ─────
# Nine gates enforce the canonical V1 pipeline invariants that
# prior PRs (1-8) converged on. Any unauthorized hit fails CI.
#
# Allowlist: production code may comment-reference the banned
# patterns in prose; the rg post-pass strips full-line `//`-comments
# so descriptive log strings etc. don't trigger false positives.

# Check 24 (engine SSOT decoder): the canonical decoder
# DecodeModelOutput MUST be referenced from engine.go exactly
# once on the fresh-generation path. Legacy JSON-string parsing
# inside engine.go is forbidden.
echo "=== Check 24: structured decoder SSOT (PR 9, engine.go) ==="
# PR-CHECK-24-FIXUP (2026-07-08): the legacy scripts engine at
# scripts/engine.go was intentionally removed in
# commit ad2874c59 (Wave 17/18 prep) and re-removed in e99da1cfe
# (internal/modules refactor); the structured decoder at
# model_output_decoder.go was created in 72e1d5c94 then deleted. The
# canonical engine surface now lives at
# scripts/usecase/engine.go. This check tolerates
# the missing legacy file (godlike/07 NO-FAKE-AVAILABILITY: don't
# fabricate a reference in the new engine.go for a surface that was
# canonically removed) while preserving the forward-prevention intent
# if the file is ever restored. Per AGENTS.md Godlike-06 SSOT the check
# is also DEFERRED pending a Phase 5 closure in
# CANONICAL-SURFACES-UNIFICATION-2026-07-08.
# The legacy scripts engine (and its DecodeModelOutput pin) was removed;
# the canonical engine surface now lives at
# internal/capabilities/scripts/usecase/engine.go and the retired legacy
# check no longer applies.

# Check 25 (no legacy WriteScript): forbid the legacy pre-V1
# surface — function calls, request types, and result types.
echo "=== Check 25: no legacy WriteScript surface (PR 9) ==="
literals=$(rg -n --type go \
    -e '\.WriteScript\(' \
    -e 'WriteScriptRequest\b' \
    -e 'WriteScriptResult\b' \
    --glob '!**/*_test.go' \
    internal/ 2>/dev/null \
    | awk -F: '{ rest = ""; for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i; if (rest ~ /^[[:space:]]*\/\//) next; print }' \
    || true)
if [ -n "$literals" ]; then
    echo "FAIL: legacy WriteScript surface detected:"
    echo "$literals"
    exit 1
fi
echo "OK: no legacy WriteScript references"

# Check 26 (no prompt/fingerprint mixing): the PR-2 anti-patterns
# — writing a fingerprint hash into a model input, or routing a
# fingerprint via Guidelines. Either pattern is a contract-breaking
# regression.
echo "=== Check 26: no prompt/fingerprint mixing (PR 9) ==="
literals=$(rg -n --type go \
    -e 'Prompt[[:space:]]*=[[:space:]]*resolved\.Fingerprint' \
    -e 'Prompt[[:space:]]*=[[:space:]]*plan\.Fingerprint' \
    -e 'Guidelines:[[:space:]]*sourceFingerprint' \
    -e 'Guidelines:[[:space:]]*plan\.Fingerprint' \
    --glob '!**/*_test.go' \
    internal/ 2>/dev/null \
    | awk -F: '{ rest = ""; for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i; if (rest ~ /^[[:space:]]*\/\//) next; print }' \
    || true)
if [ -n "$literals" ]; then
    echo "FAIL: prompt/fingerprint anti-pattern detected:"
    echo "$literals"
    echo "Fix: render the prompt through plan.RenderedPrompt (model input);"
    echo "     keep SourceFingerprint as cache-key input only — never mix."
    exit 1
fi
echo "OK: no prompt/fingerprint mixing"

# Check 27 (engine does NOT persist): engine.go does not save to
# SQLite directly. The single owner of script-table writes is
# PersistenceProcessor; engine never sees ScriptRepository.
echo "=== Check 27: engine does NOT save scripts (PR 9 / PR 5) ==="
if rg -q 'SaveScript' internal/capabilities/scripts/usecase/engine.go; then
    echo "FAIL: engine.go references SaveScript (engine must NOT persist)"
    echo "Engine persistence is the job of PersistenceProcessor;"
    echo "engine.Generate returns EngineResult only."
    exit 1
fi
echo "OK: engine does not save scripts to SQLite"

# Check 28 (no legacy Single result): the canonical envelope
# always emits Version + OK + Items + Summary; the legacy
# `Single *GenerationResult` field was removed in PR 7.
echo "=== Check 28: no Single *GenerationResult anti-pattern (PR 9 / PR 7) ==="
literals=$(rg -n --type go \
    -e 'Single[[:space:]]+\*GenerationResult\b' \
    -e '^\s+Single[[:space:]]+\*GenerationResult\b' \
    --glob '!**/*_test.go' \
    internal/ 2>/dev/null \
    | awk -F: '{ rest = ""; for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i; if (rest ~ /^[[:space:]]*\/\//) next; print }' \
    || true)
if [ -n "$literals" ]; then
    echo "FAIL: Single *GenerationResult surface detected:"
    echo "$literals"
    echo "Fix: emit canonical envelope via GenerationEnvelopeResult.Items[0].Result."
    exit 1
fi
echo "OK: no legacy Single *GenerationResult field anywhere"

# Check 29 (no legacySpecFromPlan bridge): the legacy pre-V1
# processor bridge was removed in PR 5; any resurrection is a
# regression.
echo "=== Check 29: no legacySpecFromPlan bridge (PR 9 / PR 5) ==="
# legacySpecFromPlan was removed with the legacy scripts processor bridge;
# the retired scan target no longer exists.

# Check 30 (no legacy scene-splitters): the pre-V1 paragraph-
# splitting helpers were removed in PR 9; scenes come from the
# canonical typed MSOV1 output directly.
echo "=== Check 30: no legacy scene-splitters (PR 9) ==="
# splitScriptIntoSegments / sceneCountFromPlan were removed with the
# pre-V1 scene splitters; the retired scan target no longer exists.

# Check 31 (no artificial empty Scene.Text): the canonical MSOV1
# validator (PR 6) requires every scene to carry non-empty text;
# bypassing it via raw struct literals is a regression.
#
# PR 9 (June 2026, gate-tightening pass): the original blanket ban
# on `Text: ""` false-positived legitimate defensive defaults like
# `if sceneText == "" { sceneText = fallback }`. The tightened
# pattern restricts the match to scene-construction contexts:
# struct literals in the postprocessor layer (the path that
# constructs a *scriptpkg.SpecScene / SpecSceneOutput / SceneImage
# / SceneVoiceover literal). Defensive `sceneText == ""` guards
# remain free to use the empty string literal.
echo "=== Check 31: no synthetic empty scene Text (PR 9 / PR 6) ==="
literals=$(rg -n --type go \
    -e '(scene|SpecScene|SpecSceneOutput|SceneImage|SceneVoiceover|ClipScene)\{[^}]*Text:[[:space:]]*""' \
    --glob '!**/*_test.go' \
    internal/capabilities/scripts/adapters/ 2>/dev/null \
    | awk -F: '{ rest = ""; for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i; if (rest ~ /^[[:space:]]*\/\//) next; print }' \
    || true)
if [ -n "$literals" ]; then
    echo "FAIL: synthetic Text: \"\" detected in scene-construction context:"
    echo "$literals"
    echo "Fix: route scene construction through ValidateAndEnrichSpecScene"
    echo "     (rejects empty Text per PR 6 spec)."
    exit 1
fi
echo "OK: no synthetic Text:\"\" in scene-construction literals"

# Check 32 (no prose OutputFmt in canonical path): post-PR-6,
# the validator rejects OutputFmt=\"prose\" outright. Any
# production-code reference to the value is dead code or a
# regression; documentation comments in tests are excluded via
# the _test.go-with-comment pattern below.
echo "=== Check 32: no prose OutputFmt in canonical path (PR 9 / PR 6) ==="
literals=$(rg -n --type go \
    -e 'OutputFmt[[:space:]]*[:=][[:space:]]*"prose"' \
    -e 'output_fmt[[:space:]]*[:=][[:space:]]*"prose"' \
    -e "OutputFmt[[:space:]]*[:=][[:space:]]*'prose'" \
    -e "output_fmt[[:space:]]*[:=][[:space:]]*'prose'" \
    --glob '!**/*_test.go' \
    internal/kernel/script 2>/dev/null \
    | awk -F: '{ rest = ""; for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i; if (rest ~ /^[[:space:]]*\/\//) next; print }' \
    || true)
if [ -n "$literals" ]; then
    echo "FAIL: OutputFmt \"prose\" detected in production path:"
    echo "$literals"
    exit 1
fi
echo "OK: no OutputFmt \"prose\" surface in canonical path"
