#!/usr/bin/env bash
# 17_check_47.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 47: C2-C no-source-switch-outside-catalog (Blocco C2, June 2026) ──
# The canonical Source Catalog dispatch surface lives in the typed registry:
#
#   - internal/capabilities/scripts/adapters/source_registry.go  (SourceRegistry registry)
#
# Every other source-kind switch (case "artlist" / case scriptpkg.SourceCatalog /
# if source == "youtube" / etc.) in production code is a SSOT regression: the
# Source Catalog is the canonical owner of source-kind metadata + dispatch
# (godlike/06 §"data-and-config-ownership"). The AST gate is the complementary
# forward-prevention rule to the SourceCatalog registry pattern.
#
# Pattern anchors (AST walk, see gate_c2_source_catalog_only.go for the
# rigorous BasicLit + Ident + SelectorExpr matching semantics):
#   switch X { case "artlist" | case scriptpkg.SourceCatalog | case SourceCatalog: ... }
#   if X == "youtube" / if X == scriptpkg.SourceArtlist / if X == SourceStock: ...
#
# CLOSED 2026-08-26 (WAVE-22-C2-C): the migration-only roots
# (internal/application + internal/api) were deleted, so the scanned count is
# zero and the allowlist is empty. The gate now enforces the target-zero state
# directly from the code scan (no manual baseline; ceiling derived from HEAD^).
echo "=== Check 47: C2-C no-source-switch-outside-catalog (Blocco C2, June 2026) ==="
    c2c_out=$(go run -tags=c2_source_catalog_only -- ./scripts/archcheck/gates/gate_c2_source_catalog_only_main.go . 2>&1) || c2c_rc=$?
c2c_rc=${c2c_rc:-0}
if [ "$c2c_rc" -ne 0 ]; then
    printf '%s\n' "$c2c_out" | sed 's/^/  /'
    echo ""
    echo "Fix: every source-kind switch/if dispatch"
    echo '      (case "<canonical>" OR case scriptpkg.Source<> OR if == "<canonical>")'
    echo "      MUST live in the Source Catalog canonical registry:"
    echo "        - internal/capabilities/scripts/adapters/source_registry.go  (SourceRegistry)"
    echo "      See capability_inventory.yaml::gates_baseline::C2-C for the canonical surface contract."
    echo ""
    echo "Per godlike/06 (data-and-config-ownership) the Source Catalog is the SSOT for"
    echo "source-kind metadata + dispatch. In-place switch/if chains are SSOT regressions."
    echo ""
    echo "Remediation paths (in priority order):"
    echo "  1. Route the dispatch through SourceCatalog.Resolve(<source>) or"
    echo "     SourceRegistry.Resolve(<source>) so the canonical lookup is the SSOT."
    echo "  2. If the dispatch is structural-validation (SourceType.IsValid-style enum"
    echo "     exhaustiveness), migrate the check next to the enum declaration in"
    echo "     internal/domain/{asset,script}/ so the validation stays co-located"
    echo "     with the canonical type."
    echo "  3. If the file legitimately needs extended canonical ownership, follow"
    echo "     godlike/07 (EXPAND -> BACKFILL -> CUTOVER) and add a co-equal entry"
    echo "     to capability_inventory.yaml::gates_baseline::C2-C. (Don't just widen"
    echo "     the allowlist without a documented owner + deadline + cutover plan.)"
    echo ""
    echo "The ceiling is derived from HEAD^; reduce violations in code."
    echo "Do not edit a duplicated baseline number to make this gate pass."
    exit 1
fi
# Print the AST gate's own success line verbatim so the operator sees it in CI output.
printf '%s\n' "$c2c_out" | grep -E '^C2-C gate:' || true
