#!/usr/bin/env bash
# 18_check_48.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 48: C2-E route-manifest-≡-generated-docs (Blocco C2, June 2026) ──
# The canonical route surface has three sources of truth that MUST agree:
#
#   1. RUNTIME MANIFEST — `architecture/routes.yaml` — generated by
#      `cmd/admin/gen_api_docs.go` from the live Gin router. Each row is
#      a deduplicated (METHOD, PATH) snapshot with runtime-generator
#      provenance; the manifest is not a substitute for handler ownership.
#
#   2. RUNTIME DOCS — `docs/api/ACTIVE_API_GENERATED.md` — generated by
#      the same command from the same `gin.Engine.Routes()` capture,
#      with human-readable descriptions. Per-group MD-table format:
#      `| METHOD | `/path` | ... |`.
#
# The invariant is that both runtime artifacts agree on every
# (METHOD, PATH) row. They are staged together before publication so
# generation failures cannot intentionally create a fresh/stale pair.
# The legacy AST helper remains diagnostic-only and is not an authority.
#
# Missing artifacts fail closed; a fresh pair is produced with:
#   go run ./cmd/admin gen-api-docs
# The gate compares only the committed runtime manifest and docs snapshot.
echo "=== Check 48: C2-E route-manifest-≡-generated-docs (Blocco C2, June 2026) ==="
manifest_path="${REPO_ROOT}/architecture/routes.yaml"
docs_path="${REPO_ROOT}/docs/api/ACTIVE_API_GENERATED.md"

if [ ! -f "${docs_path}" ]; then
    echo "FAIL: required artefact missing at ${docs_path}"
    echo ""
    echo "Fix: regenerate via the canonical runtime-capture binary:"
    echo "  go run ./cmd/admin gen-api-docs"
    echo ""
    echo "The route-manifest gate has no second source to compare against if"
    echo "the generated docs file is absent — fail-closed (no soft-skip)."
    exit 1
fi

if [ ! -f "${manifest_path}" ]; then
    echo "FAIL: required artefact missing at ${manifest_path}"
    echo "Fix: regenerate the paired runtime artifacts:"
    echo "  go run ./cmd/admin gen-api-docs"
    exit 1
fi

c2e_out=$(go run -tags=c2_route_manifest -- ./scripts/archcheck/gates/gate_c2_route_manifest_main.go --baseline=171 --root="${REPO_ROOT}" 2>&1) || c2e_rc=$?
c2e_rc=${c2e_rc:-0}
if [ "$c2e_rc" -ne 0 ]; then
    printf '%s\n' "$c2e_out" | sed 's/^/  /'
    echo ""
    echo "Fix: the route manifest (architecture/routes.yaml) and the runtime-"
    echo "generated docs (docs/api/ACTIVE_API_GENERATED.md) disagree. Run the"
    echo "runtime capture generator to refresh both route artifacts:"
    echo "  go run ./cmd/admin gen-api-docs"
    echo "The command writes architecture/routes.yaml and"
    echo "docs/api/ACTIVE_API_GENERATED.md atomically from the live router."
    echo "Re-run the gate to confirm both sources agree."
    echo ""
    echo "Common root causes:"
    echo "  - New route registered that didn't go through the canonical"
    echo "    RegisterRoutes site (bypass composition root → 'docs-only')."
    echo "  - Generated artifacts were not refreshed from the live router."
    echo "  - Inline chained-group or non-literal path pattern surfaces as"
    echo "    drift (pre-step emits warnings; the manifest will be incomplete)."
    exit 1
fi
printf '%s\n' "$c2e_out" | grep -E '^C2-E gate:' || true
