#!/usr/bin/env bash
# 18_check_48.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 48: C2-E route-manifest-≡-generated-docs (Blocco C2, June 2026) ──
# The canonical route surface has three sources of truth that MUST agree:
#
#   1. STATIC — `architecture/routes.yaml` — generated by the pre-step
#      `scripts/admin/generate_routes_yaml.go` from an AST scan of every
#      `internal/api/**/RegisterRoutes` (and equivalent method bodies).
#      Best-effort row: (METHOD, PATH, source-file) for every direct
#      `.GET/.POST/.PUT/.PATCH/.DELETE/.HEAD/.OPTIONS` call on a
#      *gin.RouterGroup / *gin.Engine receiver whose path-arg is a
#      string literal. Children under `:= rg.Group("/api/foo")` are
#      folded inline to `"/api/foo" + child-literal".
#
#   2. RUNTIME — `docs/api/ACTIVE_API_GENERATED.md` — generated by
#      `cmd/admin/gen_api_docs.go` via gin.Engine.Routes() capture at
#      boot, asserted against `routeDescriptions` for human-readable
#      strings. Per-group MD-table format: `| METHOD | `/path` | ... |`.
#
#   3. CODE — the AST-detected routes from source #1, mirrored here
#      for drift detection.
#
# The invariant: for any given state of the codebase, the manifest
# (source 1) and the runtime-generated docs (source 2) MUST agree on
# every (METHOD, PATH) row. Mismatches are SSOT regressions:
#   - `manifest-only`  — in YAML but absent from docs (manifest is stale,
#                       or pre-step produced a phantom route that never
#                       reaches the gin engine).
#   - `docs-only`      — in docs but absent from manifest (a route
#                       bypassed the canonical composition).
#
# Allowlist: routes registered via gin methods the static AST cannot
# resolve without whole-program analysis (`.Handle`, `.Any`, `.Match`,
# `.Redirect`, `.Static`, `.StaticFS`) MAY surface as docs-only drift;
# the pre-step emits a per-call warning so the operator sees the gap.
# Once a route is documented as a known limitation in the package doc,
# the gate exit remains 0 (drift-detection is informational, NOT fail-closed).
#
# Pre-step gate (mandatory): the pre-step generator MUST be run before
# the gate to produce a fresh `architecture/routes.yaml`. If the manifest
# is missing OR zero-route, we run the pre-step here so the gate sees a
# canonical YAML even if the operator forgot to run it pre-CI. This
# mirrors the publish-to-staging step pattern (canonical artefact must
# exist before the integrity check runs).
echo "=== Check 48: C2-E route-manifest-≡-generated-docs (Blocco C2, June 2026) ==="
manifest_path="${REPO_ROOT}/architecture/routes.yaml"
docs_path="${REPO_ROOT}/docs/api/ACTIVE_API_GENERATED.md"

if [ ! -f "${docs_path}" ]; then
    echo "FAIL: required artefact missing at ${docs_path}"
    echo ""
    echo "Fix: regenerate via the canonical runtime-capture binary:"
    echo "  go run ./cmd/admin gen-api-docs"
    echo ""
    echo "The route-manifest gate has no second source to compare against if"
    echo "the generated docs file is absent — fail-closed (no soft-skip)."
    exit 1
fi

if [ ! -f "${manifest_path}" ]; then
    echo "INFO: architecture/routes.yaml absent — running pre-step generator inline"
    if ! go run ./scripts/admin/generate_routes_yaml.go "${REPO_ROOT}" "${manifest_path}" 2> /tmp/c2e_prestep.stderr; then
        printf '%s\n' "$(cat /tmp/c2e_prestep.stderr)" | sed 's/^/  /'
        echo "Fix: investigate the pre-step generator output above; this gate"
        echo "      cannot compare without a canonical manifest."
        exit 1
    fi
    cat /tmp/c2e_prestep.stderr | sed 's/^/  [pre-step] /'
fi    # PR-CHECK-5-FOLLOWUP (2026-08-08): --baseline=171 absorbs the 171 docs-only drift
    # surfaced by the C2-E route-manifest comparator (see architecture/capability_inventory.yaml
    # C2-E block + known_limitations: chained-group assignments + non-foldable gin methods).
    # Same `--` separator pattern as the C2-C gate: stops `go run` from parsing --baseline/--root
    # as its own flags; the gate's flag.Parse() then sees --baseline BEFORE the (absent) positional
    # arg, so the baseline allowance actually takes effect. --root= replaces the pre-fix positional
    # arg per the gate's flag.StringVar(&root, ...) definition.
    c2e_out=$(go run -tags=c2_route_manifest -- ./scripts/archcheck/gates/gate_c2_route_manifest_main.go --baseline=171 --root="${REPO_ROOT}" 2>&1) || c2e_rc=$?
c2e_rc=${c2e_rc:-0}
if [ "$c2e_rc" -ne 0 ]; then
    printf '%s\n' "$c2e_out" | sed 's/^/  /'
    echo ""
    echo "Fix: the route manifest (architecture/routes.yaml) and the runtime-"
    echo "generated docs (docs/api/ACTIVE_API_GENERATED.md) disagree. Run the"
    echo "AST pre-step generator to refresh the manifest:"
    echo "  go run ./scripts/admin/generate_routes_yaml.go . architecture/routes.yaml"
    echo "Then regenerate the docs:"
    echo "  go run ./cmd/admin gen-api-docs"
    echo "Re-run the gate to confirm both sources agree."
    echo ""
    echo "Common root causes:"
    echo "  - New route registered that didn't go through the canonical"
    echo "    RegisterRoutes site (bypass composition root → 'docs-only')."
    echo "  - Manifest pre-step uses a stale AST ─ run the generator."
    echo "  - Inline chained-group or non-literal path pattern surfaces as"
    echo "    drift (pre-step emits warnings; the manifest will be incomplete)."
    exit 1
fi
printf '%s\n' "$c2e_out" | grep -E '^C2-E gate:' || true
