#!/usr/bin/env bash
# 30_check_11.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 11: forbid event_key construction with random UUID (TODO 16, Wave 19) ────
# Outbox event_keys MUST be deterministic (computed from the aggregate id +
# content hash) so the ON CONFLICT(event_key) DO NOTHING guarantee collapses
# duplicate enqueues. A random UUID in the event_key shape forces every
# enqueue to produce a new row, defeating idempotency. The canonical shapes
# are `delete:<asset_id>` (delete_envelope.go) and the index envelope in
# outboxevents/repository.go; uuid-suffixed keys are an anti-pattern.
#
# ALLOWLIST RATIONALE: the tightened multi-line patterns (June 2026
# follow-up) match uuid.NewString ONLY when the eventKey assignment line
# references the variable that holds the uuid (eventID). This lets the
# gate distinguish:
#
#   ANTI-PATTERN: eventKey assignment line contains `\beventID\b` (the
#     uuid-holding variable), so the uuid IS concatenated into the
#     eventKey value (directly via `+ eventID`, via `fmt.Sprintf` with
#     eventID as an arg, or any other reference).
#
#   LEGITIMATE:   eventKey assignment line does NOT reference eventID
#     at all (e.g. `eventKey := "delete:" + assetID`), so the uuid
#     is for a SEPARATE field (event_id audit) and ON CONFLICT(event_key)
#     DO NOTHING still works correctly.
#
# The allowlist below covers Category B only (reindex is intentionally
# uuid-suffixed per canonical design). Category A (UUID for separate
# event_id field) is NO LONGER allowlisted — the tightened patterns
# correctly accept it without an explicit allowlist entry.
#
# Category B — reindex is intentionally uuid-suffixed per canonical design:
#   - internal/platform/sqlite/outboxevents/envelope.go::
#     BuildReindexEnvelopeV1: the eventKey IS uuid-suffixed by design
#     ("reconcile:reindex:<assetID>:<eventID>"). Idempotency is enforced
#     DOWNSTREAM by the worker's supersede gate on source_version
#     (from media_assets.metadata_json.$.content_hash), not at the
#     outbox-enqueue layer. Every --apply run enqueues a fresh reindex
#     event; redundant fix-up work is collapsed at execution time.
#   - internal/platform/sqlite/outbox/delete_envelope.go::
#     buildDeleteRequestV1: pre-existing canonical pattern.
#
# Pattern shapes (3 tightened patterns):
#   1. INLINE:   `eventKey[^\n]*uuid\.NewString` — uuid.NewString is on
#                the SAME line as the eventKey assignment (direct
#                concatenation, e.g. `eventKey := "..." + uuid.NewString()`).
#   2. FORWARD:  `eventKey[^\n]*\n(?:[^\n]*\n){0,3}[^\n]*eventID[^\n]*=
#                \s*uuid\.NewString` — eventKey is on line N, and an
#                `eventID := uuid.NewString()` assignment is on line
#                N+1..N+3 (uuid-suffixed via a forward intermediate var).
#   3. REVERSE:  `eventID[^\n]*=\s*uuid\.NewString[^\n]*\n(?:[^\n]*\n){0,3}
#                [^\n]*eventKey[^\n]*=[^\n]*\beventID\b` — the canonical
#                production shape: `eventID := uuid.NewString()` on line N,
#                `eventKey := "..." + eventID` on line N+1. The `\beventID\b`
#                on the eventKey line proves the uuid IS being concatenated
#                into the eventKey value (not just adjacent to it).
#
# Loophole: the patterns hardcode the variable name `eventID`. A future
# contributor using a different name (e.g. `uid := uuid.NewString()`) would
# not be caught. ripgrep's default regex engine does not support
# backreferences for dynamic variable matching. The trade-off is
# acceptable because (a) `eventID` is the canonical name across all
# canonical envelope builders (BuildReindexEnvelopeV1, buildDeleteRequestV1)
# and the canonical reconcile adapter, and (b) the escape hatch is to
# promote Check 11 to a Go-side AST pass via
# `scripts/archcheck/check11eventkey/` (mirrors the Wave 19 PR2-1 pattern
# for cross-capability edge graph emission) if the loophole is exercised
# in practice.
#
# Allowlist:
#   - internal/platform/sqlite/outbox/**       : canonical envelope builders
#                                                              (Category B pattern).
#   - internal/platform/sqlite/outboxevents/** : canonical reindex envelope
#                                                              (Category B pattern).
#   - *_test.go                                               : test fixtures may use
#                                                              uuid.NewString for distinct keys.
#   - tests/fixtures/zero_legacy/**                           : self-check fixtures.
echo "=== Check 11: forbid event_key construction with random UUID (TODO 16) ==="
uuidEventKeys=$(rg -nU --type go \
    -e 'eventKey[^\n]*uuid\.NewString' \
    -e 'eventKey[^\n]*\n(?:[^\n]*\n){0,3}[^\n]*eventID[^\n]*=\s*uuid\.NewString' \
    -e 'eventID[^\n]*=\s*uuid\.NewString[^\n]*\n(?:[^\n]*\n){0,3}[^\n]*eventKey[^\n]*=[^\n]*\beventID\b' \
    --glob '!**/internal/platform/sqlite/outbox/**' \
    --glob '!**/internal/platform/sqlite/outboxevents/**' \
    --glob '!**/*_test.go' \
    --glob '!tests/fixtures/zero_legacy/**' \
    . 2>/dev/null \
    | awk -F: '{
        rest = ""
        for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
        if (rest ~ /^[[:space:]]*\/\//) next
        print
    }' \
    || true)
if [ -n "$uuidEventKeys" ]; then
    echo "FAIL: event_key constructed with random UUID outside canonical envelope:"
    echo "$uuidEventKeys"
    echo ""
    echo "Fix: use the canonical envelope builders (delete_envelope.go, index"
    echo "envelope in outboxevents/repository.go) which produce deterministic"
    echo "event_keys from the aggregate id + content hash. uuid.NewString in"
    echo "the event_key shape defeats ON CONFLICT(event_key) DO NOTHING and"
    echo "creates a fresh outbox row on every enqueue."
    exit 1
fi
echo "OK: no event_key construction with random UUID outside canonical envelope"
