#!/usr/bin/env bash
# 32_check_13.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 13: forbid ListAssetsForReconcile placeholder (TODO 16, TODO 2) ────
# SQLiteAssetStore.ListAssetsForReconcile is currently wired as a build-time
# placeholder (returns `wired as build-time placeholder only` error). That
# means any reconcile --apply call silently produces 0 findings, hiding real
# drift. The fix is to implement the SQL scan; this check fails until then.
#
# Pattern: any source code that returns the placeholder error string.
#
# Allowlist:
#   - *_test.go                  : tests may stub the placeholder explicitly.
#   - tests/fixtures/zero_legacy/** : self-check fixtures.
echo "=== Check 13: forbid ListAssetsForReconcile placeholder (TODO 16, TODO 2) ==="
placeholderReconcile=$(rg -n --type go \
    -e 'wired as build-time placeholder' \
    --glob '!**/*_test.go' \
    --glob '!tests/fixtures/zero_legacy/**' \
    . 2>/dev/null \
    | awk -F: '{
        rest = ""
        for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
        if (rest ~ /^[[:space:]]*\/\//) next
        print
    }' \
    || true)
if [ -n "$placeholderReconcile" ]; then
    echo "FAIL: ListAssetsForReconcile placeholder still wired in production:"
    echo "$placeholderReconcile"
    echo ""
    echo "Fix: implement the SQL scan in SQLiteAssetStore.ListAssetsForReconcile."
    echo "The placeholder (return fmt.Errorf(\"wired as build-time placeholder\"))"
    echo "silently produces 0 reconcile findings, hiding real drift. See TODO 2."
    exit 1
fi
echo "OK: no ListAssetsForReconcile placeholder in production"
