#!/usr/bin/env bash
# 34_check_15.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 15: qdrant.NewClient constructions must propagate APIKey (QDRANT-005A) ────
# QDRANT-005A Phase 1 Blocker #1: cfg.Qdrant.APIKey is not propagated to
# qdrant.NewClient at every construction site. An API-key-protected Qdrant
# deployment appears unhealthy (401) because the client omits the X-Api-Key
# header on every request. The canonical pattern is:
#
#   client := qdrant.NewClient(&qdrant.Config{
#       BaseURL: cfg.Qdrant.BaseURL,
#       APIKey:  cfg.Qdrant.APIKey,   // <-- REQUIRED
#       Timeout: cfg.Qdrant.Timeout,
#   }, log)
#
# Implementation: per-file check. Find every Go file that constructs
# qdrant.NewClient(&qdrant.Config{...}), then verify the SAME file
# also contains the literal pattern `APIKey:\s*cfg\.Qdrant\.APIKey`.
# A file that constructs the client but does NOT propagate the APIKey
# is the production anti-pattern.
#
# Why per-file (not per-block): a Go file may legitimately construct
# multiple qdrant.Config{...} literals (e.g. one for the production
# client + one for a test stub). Per-file is the conservative
# scope: any file that touches the client must also touch the
# APIKey propagation. If a file has TWO client constructions and
# ONE omits APIKey, the per-file check still catches it (the
# file-level pattern absence is the signal).
#
# Limit: a test file that constructs a stub client with no auth
# would false-positive. Test files are excluded via --glob
# `!**/*_test.go` per the standard check convention.
#
# Allowlist:
#   - *_test.go                  : test stubs may construct unauthenticated clients.
#   - tests/fixtures/zero_legacy/** : self-check fixtures.
#   - internal/platform/qdrant/** : the Config TYPE lives here;
#                                     test files in this package are
#                                     excluded by the *_test.go rule,
#                                     and production code in this
#                                     package does NOT construct the
#                                     client (it only defines types).
echo "=== Check 15: qdrant.NewClient must propagate APIKey (QDRANT-005A) ==="
clientFiles=$(rg -l 'qdrant\.NewClient\(&qdrant\.Config\{' --type go \
    --glob '!**/*_test.go' \
    --glob '!tests/fixtures/zero_legacy/**' \
    . 2>/dev/null \
    || true)
missingApiKey=""
for f in $clientFiles; do
    if ! rg -q 'APIKey:\s*cfg\.Qdrant\.APIKey' "$f" 2>/dev/null; then
        missingApiKey="$missingApiKey $f"
    fi
done
if [ -n "$missingApiKey" ]; then
    echo "FAIL: file(s) construct qdrant.NewClient but do NOT propagate cfg.Qdrant.APIKey:"
    for f in $missingApiKey; do echo "  $f"; done
    echo ""
    echo "Fix: add 'APIKey: cfg.Qdrant.APIKey,' to the qdrant.Config{...} literal."
    echo "An API-key-protected Qdrant deployment appears unhealthy (401) when"
    echo "the client omits the X-Api-Key header. QDRANT-005A Phase 1 Blocker 1."
    exit 1
fi
echo "OK: all qdrant.NewClient constructions propagate cfg.Qdrant.APIKey"
