#!/usr/bin/env bash
# 37_check_36.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 36: anti-reintro gate for diagnostic / snapshot artefacts (PR-A, June 2026) ──
# Forward-prevention after the Wave 21 PR-G mega-batch that re-landed
# .tmp-diag/ directory + CURRENT_<X>.go + TODO<N>_<X>.go fixtures in the
# working tree (see paste audit). This gate ensures the .gitignore
# patterns appended by PR-A remain effective: any re-introduction of
# the four diagnostic patterns under internal/ cmd/ pkg/ scripts/ tests/
# fails CI with a remediation `git rm -rf` instruction.
#
# Pattern anchors (case-sensitive, basename-only):
#   directory names:  .tmp-diag,  tmp-diag
#   file basenames:   CURRENT_*.go  (literal CURRENT_ prefix)
#                     TODO[0-9]*.go (literal TODO prefix + 1 digit, no underscore required)
#
# Scope: the four top-level source roots only. .git/ hidden by default
# via `find` not descending into .git; tests/fixtures/zero_legacy/ is
# OUT of scope (`tests/` only matches the directory, fixtures of the
# canonical negative-example shape are not flagged).
#
# Implementation: `find` is canonical here (consistent with Check 23
# field-count extraction). rg --glob filters the search space, not the
# file-name; for basenameonly matching, find -name is the precise tool.
#
# Failure mode: emit the offending paths AND a copy-pasteable `git rm`
# one-liner so the operator can clean up in one step. Standard
# fail-fast + literal remediation. Index/PR-bodies stay consistent
# across the diagnostic-artefact family.
echo "=== Check 36: diagnostic-artefact anti-reintro gate (PR-A, June 2026) ==="
diag_files=$(find internal cmd pkg scripts tests -type f \
    \( -name 'CURRENT_*.go' -o -name 'TODO[0-9]*.go' \) \
    -not -path 'tests/fixtures/zero_legacy/*' 2>/dev/null || true)
diag_dirs=$(find internal cmd pkg scripts tests -type d \
    \( -name '.tmp-diag' -o -name 'tmp-diag' \) 2>/dev/null || true)
diag_hits=$(printf '%s\n%s\n' "$diag_files" "$diag_dirs" \
    | grep -v '^$' | sort -u || true)
if [ -n "$diag_hits" ]; then
    echo "FAIL: diagnostic / snapshot artefacts detected in source roots:"
    printf '%s\n' "$diag_hits" | sed 's/^/  /'
    echo ""
    echo "Resolution:"
    echo "  1. If these are intended diagnostic snapshots, MOVE them under"
    echo "     tests/fixtures/zero_legacy/ (the canonical negative-example"
    echo "     surface exempted by this gate)."
    echo "  2. Otherwise the canonical cleanup is to remove them via:"
    printf '%s\n' "$diag_hits" | sed 's/^/     git rm -rf /'
    echo ""
    echo "Per AGENTS.md §8 ARCHITECTURE-CI-GATES zero-baseline rule,"
    echo "re-introduction of these patterns is now blocked; this gate"
    echo "is the forward-prevention half of PR-A."
    exit 1
fi
echo "Check 36: 0 diagnostic-artefact paths in internal/ cmd/ pkg/ scripts/ tests/"
