#!/usr/bin/env bash
# 41_divider_main_gate_part1.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Main gate ──────────────────────────────────────────────────────────
# Run the focused+ratchet archcheck; PR-A's `--future-ratchet` keeps the
# 5 Phase 0 rules in grace-cycle regression-detection mode.
go run ./scripts/archcheck --ratchet --future-ratchet

# PR-I (June 2026): promote cmd/archcheck --strict as a blocking CI gate.
# Reads architecture/policy.yaml; --strict turns warn → exit-1 on any
# violation per cmd/archcheck/main.go:204-205. Ratchets #id-20-21:
# duplicate-types-allowlist (Check 5) + max_files_per_package=65
# (pack-size cap). Transitional baseline:
# docs/migrations/archcheck-strict-baseline.json holds any open
# exceptions; fail-closed semantics deadlined entries become hard
# fail (verdict: PR-I implementation in_progress per ADR-0002 §D5).
go run ./cmd/archcheck --strict
# HC-1 (June 2026) deletes the pre-HC-1 package-level `var jobTimeoutRegistry`
# global in internal/application/jobs/worker.go + the `SetJobTimeout` and
# `jobTimeout(` helper callers. Per-job-type timeouts are now keyed through
# `*jobs.Registry.Compose()[j.Type]` (or the typed `JobTimeout()` method)
# via the Worker.WithRegistry(reg) builder attached at composition time.
#
# Pattern anchors (re-introduction patterns we forbid):
#   var jobTimeoutRegistry[[:space:]]*=
#       — package-level map re-emergence with a MapType-typed name
#       (catches `var jobTimeoutRegistry`, `var ( ... jobTimeoutRegistry ...)`).
#   SetJobTimeout\(
#       — exported helper to mutate the map (the pre-HC-1 surface);
#       only worker.go::SetJobTimeout defined this; the alias was removed.
#   ^func jobTimeout\(  (top-level package function)
#   {{:blank:}}jobTimeout\(  (in-function call to package helper)
#       — the lowercase helper that read from the global; renamed to
#       Worker.jobTimeoutFor(t) post-HC-1.
#
# Scope: internal/ + cmd/ (composition root + production callers).
# The canonical site is internal/application/jobs/registry.go (owns the
# TimeoutMap + TimeoutResolver surface); it does NOT contain the
# forbidden patterns. *Registry.Compose() / JobTimeout() are the
# AND ONLY the supported lookup paths.
#
# Negative examples (the patterns being checked for, when invoked
# legitimately as inline fixtures/tests) live in tests/fixtures/zero_legacy/
# — excluded below to mirror Check 36 / Check 39 gating convention.
echo "=== Check 40: HC-1 anti-reintro gate (var jobTimeoutRegistry re-emergence) ==="
hc1_hits=$(rg -n --type go \
    -e 'var[[:space:]]+jobTimeoutRegistry[[:space:]]*=' \
    -e 'SetJobTimeout\(' \
    -e '^func[[:space:]]+jobTimeout\(' \
    -e '\bjobTimeout\(' \
    --glob '!**/*_test.go' \
    --glob '!tests/fixtures/zero_legacy/*' \
    internal cmd 2>/dev/null \
    | awk -F: '{
        rest = ""
        for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
        if (rest ~ /^[[:space:]]*\/\//) next   # drop full-line comments
        print
    }' \
    || true)
if [ -n "$hc1_hits" ]; then
    echo "FAIL: HC-1 re-introduction detected (jobTimeoutRegistry global / SetJobTimeout / jobTimeout helper):"
    printf '%s\n' "$hc1_hits" | sed 's/^/  /'
    echo ""
    echo "Fix: per-job-type timeouts MUST be keyed through *jobs.Registry via"
    echo "      Worker.WithRegistry(reg) at composition time. The HC-1 surface:"
    echo "    - registry.Compose()  → TimeoutMap (type-keyed snapshot)"
    echo "    - registry.JobTimeout(t) → typed single-shot lookup (the canonical"
    echo "                              TimeoutResolver method)"
    echo "    - worker.WithRegistry(reg)  → builder attached at composition time"
    echo "      (also snapshots reg.Compose() so runJob's lookup is branch-free)."
    echo ""
    echo "There is NO legitimate use of `var jobTimeoutRegistry ... = ...`, no"
    echo "`SetJobTimeout(t, d)` mutation hook, and no top-level `jobTimeout(t)`"
    echo "helper. Adding any of these requires a godlike/07 EXPAND/BACKFILL/"
    echo "CUTOVER/CONTRACT migration sequence (architecture/deprecations.yaml)"
    echo "and a tracking entry in architecture/current.yaml#HC-1 sub_tasks."
    exit 1
fi
echo "Check 40: 0 HC-1 re-introduction patterns (var jobTimeoutRegistry \/ SetJobTimeout \/ jobTimeout)"

# Check 15: 500-LoC per file (transitional allowlist, scadenza 2026-07-15)
bash "$(dirname "$0")/ci/architecture/checks/15_file_size.sh" || { echo "Step 6 check 15 (file size) failed"; exit 1; }

# Check 16: <=39 productive files per package (transitional allowlist qdrant)
bash "$(dirname "$0")/ci/architecture/checks/16_package_size.sh" || { echo "Step 6 check 16 (package size) failed"; exit 1; }
# Check 43: forbid .DB() chain outside infrastructure (P1.6, June 2026)
bash "$(dirname "$0")/ci/architecture/checks/43_db_chain_outside_infra.sh" || { echo "Check 43 (DB chain) failed"; exit 1; }

# Check 45: forbid inline bare map[string]*ClipsRepository{...} literals (Wave 23, action P1-3)
# Companion to Check 8 (S3e) which bans the fully-qualified
# `"map[string]*assets.ClipsRepository{"` shape. Check 45 catches the
# BARE / unqualified variant `"map[string]*ClipsRepository{"` -- a
# likely regression shape if a future contributor imports the canonical
# type without a package alias (or introduces a new unqualified alias).
# Canonical-allowed sites (composition root + canonical registry +
# tests + zero_legacy fixtures) are excluded via rg --glob inside the
# check script.
