#!/usr/bin/env bash
# 42_check_44_p1_2_application_size_cap_types_aliases_go_filename.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 44 (P1-2 application size cap + types_aliases.go filename ban) ──
# Action P1-2 of cleanup plan (June 2026): promoted from `current_state: deferred` to active.
# Slot was reserved in the original Check 45 commit per the now-removed
# `NOTE: Check 44 ... monotone-ratchetable.` comment above (see git history).
# Companion `arch(current):` commit in this PR flips wave_status.P1-2.current_state.
# SSOT (target + transitional_cap + current_state) read live from
# architecture/current.yaml::doc[1].wave_status.P1-2 per AGENTS.md §8 SSOT discipline.
bash "$(dirname "$0")/ci/architecture/checks/46_inline_clips_repository_map_ban.sh" || { echo "Check 46 (inline ClipsRepository map ban) failed"; exit 1; }
