#!/usr/bin/env bash
# 45_divider_transitional_baseline_per_file_allowlist.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Transitional baseline (per-file allowlist) ─────────────────────
# Per AGENTS.md godlike/08 zero-baseline rule (mirrors Check 5 / Check 8 /
# Check 23 / Check 33). Every entry requires explicit owner + deadline +
# rationale documented inline. Migration of any entry to the canonical
# typed-path surface deletes the corresponding line from the allowlist.
declare -a retry_classifier_extras=()
if [ -f "docs/migrations/retry-classifier-substring-allowlist.txt" ]; then
  while IFS= read -r _line; do
    [[ -z "$_line" || "$_line" =~ ^[[:space:]]*# ]] && continue
    # Each entry is <path>\t# <owner> <deadline> <rationale>. Extract just
    # the first whitespace-delimited token (the path). Trailing inline
    # comments are owned by the file's per-entry documentation.
    _path=$(awk '{print $1}' <<< "$_line")
    [[ -z "$_path" || "$_path" =~ ^# ]] && continue
    retry_classifier_extras+=( -not -path "./${_path}" )
  done < docs/migrations/retry-classifier-substring-allowlist.txt
fi

violators=$(find . -name '*.go' -not -name '*_test.go' \
    -not -path '*/pkg/retry/*' \
    -not -path '*/pkg/textutil/*' \
    -not -path '*/pkg/similarity/*' \
    "${retry_classifier_extras[@]}" \
    -print0 2>/dev/null \
    | xargs -0 awk '
    BEGIN { in_classifier = 0 ; func_line = 0 }
    /^func[[:space:]]+(\([^)]*\)[[:space:]]+)?(IsTransient|isTransient|IsRetryable|isRetryable|ShouldRetry|shouldRetry)[A-Za-z0-9_]*[[:space:]]*\(/ && /err/ {
        in_classifier = 1
        func_line = FNR
        next
    }
    in_classifier && /strings\.Contains/ {
        print FILENAME ":" func_line ": " $0
        in_classifier = 0
    }
    /^}/ && in_classifier {
        in_classifier = 0
    }
    ' 2>/dev/null || true)
if [ -n "$violators" ]; then
    echo "FAIL: retry-classifier function uses strings.Contains natively outside pkg/retry:"
    echo "$violators"
    echo ""
    echo "Fix: delegate the substring classifier to pkg/retry.IsTransient (typed"
    echo "      path). Optionally wrap outgoing port errors via pkg/retry.WrapTransient"
    echo "      at the SDK / port exit so errors.As(err, *TransientInfrastructureError)"
    echo "      finds the typed carrier. Allowlist: pkg/retry (canonical home),"
    echo "      pkg/textutil, pkg/similarity, and the per-file transitional list at"
    echo "      docs/migrations/retry-classifier-substring-allowlist.txt."
    exit 1
fi
echo "OK: no retry-classifier substring-matchers outside pkg/retry"

