#!/usr/bin/env bash
# 49_check_56.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 56: FASE 2.1 PR-VOICE-FREEZE — gate banning new imports in legacy script handlers ──
# FASE 2.1 (July 2026) freezes the legacy script-generation adapter surface
# (internal/api/script/handler_legacy_*.go) for retirement on 2026-12-31.
# The FREEZE pattern is the canonical deadline-driven retirement per
# godlike/07 minimum-blast-radius: counters (legacy_clip_generation_total
# + legacy_generate_with_images_total) keep observability alive until
# rate(...[7d]) == 0, at which point the 4 handler_legacy_*.go files
# (plus the 2 typed counter declarations in handler_legacy_deprecation.go)
# are git-rm'd atomically. The CI gate enforces the FREEZE contract at
# the import layer: any new import line in handler_legacy_*.go (outside
# the audit-pin ARCH-ALLOWLIST scope) is a forward-progress violation.
#
# godlike/06 SSOT (one canonical owner per fact): the FREEZE file set IS
# the canonical surface for legacy design-time concerns. Composition-root
# adapters (lifecycle.go, wire_*.go) MUST NOT import handler_legacy_*.go
# via a passthrough — the proper pattern is a new typed port surfaced
# from the canonical typed handler interface per AGENTS.md Pattern 0.
#
# godlike/08 zero-baseline rule (FASE 2.1 wave-level): the import spec
# audit-pin is the SSOT for "what is still active in legacy code today".
# New import lines are NOT accepted unless preceded by the ARCH-ALLOWLIST
# marker `// ARCH-ALLOWLIST: legacy-script-freeze` on the line
# preceding the import (covers both single-line and multi-line `import (`
# block syntax). Per AGENTS.md §7, every marker entry requires explicit
# owner + deadline; the marker is the call-site equivalent of an
# allowlist row in the Check 5 / Check 8 / Check 33 / Check 54 pattern.
#
# Pattern anchors (ripgrep --type go; matches the canonical import
# statement shape — `"github.com/.../pkg/path"` literal inside the
# import block). Comment-only lines are dropped via awk so descriptive
# prose doesn't trigger false positives. Tests are excluded via
# --glob '!*_test.go' so legacy tests may import legitimately for
# fixture construction (handled by godlike/06 SSOT test-side pin
# discipline per Check 54's precedent).
#
# Marker placement (mirrors Check 54 canonical Go syntax):
#   (a) PREFERRED: marker immediately above the `import (` line:
#         N:   // ARCH-ALLOWLIST: legacy-script-freeze
#         N+1: import (
#         N+2:     "github.com/Marcuss-ops/PipelineGen/.../pkg"
#   (b) ACCEPTABLE: marker immediately above single-line import:
#         N:   // ARCH-ALLOWLIST: legacy-script-freeze
#         N+1: _ "github.com/Marcuss-ops/PipelineGen/.../pkg"
# The awk pre-pass accepts offending_line == marker+1 OR marker+2.
#
# Behaviour (per user spec):
#   - FAIL-CLOSED: new `"github.com/...` import line in any
#     internal/api/script/handler_legacy_*.go file outside the
#     ARCH-ALLOWLIST scroll-window. Exit 1.
#   - WARN (non-fatal): comment-only references + ARCH-ALLOWLIST
#     marker sites are logged for audit-pinning per godlike/07
#     no-fake-availability (the operator sees marker accounting every
#     CI run, not silently).
#   - 7-day-zero-retirement: the operator checks Prometheus for
#     rate(legacy_clip_generation_total[7d]) == 0 AND
#     rate(legacy_generate_with_images_total[7d]) == 0. When both
#     counters report zero for 7 consecutive days, the post-2026-12-31
#     deadline can be advanced — git rm the 4 handler_legacy_*.go files
#     + the 2 counter declarations in handler_legacy_deprecation.go
#     in a single atomic commit.
#
# Scope: strictly internal/api/script/handler_legacy_*.go ONLY (the
# canonical FREEZE file set). The audit-pin markers at canonical owner
# sites (e.g. NewService ctor in handler_flow.go) are unaffected —
# those files continue to evolve via the typed-handler pattern per
# AGENTS.md Pattern 0.
echo "=== Check 56: FASE 2.1 PR-VOICE-FREEZE — gate banning new imports in legacy script handlers ==="
all_hits=$(rg -n --type go \
    -e '^[[:space:]]*"github\.com/' \
    --glob '!*_test.go' \
    internal/api/script/handler_legacy_*.go 2>/dev/null \
    || true)
# Stage 1: drop full-line comments + ARCH-ALLOWLIST marker lines + lines
# whose marker site (in the SAME file) is on marker+1 OR marker+2 lines
# upstream of the offending import statement (mirrors Check 54's canonical
# Go-syntax contract).
literal_calls=$(printf '%s\n' "$all_hits" \
    | awk -F: '
        {
            rest = ""
            for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
            if (rest ~ /^[[:space:]]*\/\/.*ARCH-ALLOWLIST:[[:space:]]*legacy-script-freeze/) {
                markers[$1] = (markers[$1] == "" ? $2 : markers[$1] "," $2)
                next
            }
            if (rest ~ /^[[:space:]]*\/\//) next   # drop full-line comments
            n = (markers[$1] == "" ? 0 : split(markers[$1], mlist, ","))
            allowed = 0
            for (mi = 1; mi <= n; mi++) {
              m = mlist[mi] + 0
              if (m > 0 && ($2 + 0 == m + 1 || $2 + 0 == m + 2)) { allowed = 1; break }
            }
            if (allowed) next
            print
        }' \
    || true)
# Stage 2: audit-pin residue accounting (godlike/07 honest-limitation).
comment_count=0
allowlist_count=0
if [ -n "$all_hits" ]; then
    comment_count=$(printf '%s\n' "$all_hits" | awk -F: '{
        rest = ""
        for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
        if (rest ~ /^[[:space:]]*\/\//) print
    }' | wc -l | awk "{print \$1+0}")
    allowlist_count=$(printf '%s\n' "$all_hits" | awk -F: '{
        rest = ""
        for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
        if (rest ~ /^[[:space:]]*\/\/.*ARCH-ALLOWLIST:[[:space:]]*legacy-script-freeze/) print
    }' | wc -l | awk "{print \$1+0}")
fi
# Stage 3: hard-fail on production imports per user spec.
if [ -n "$literal_calls" ]; then
    echo "FAIL: forbidden new external/internal import in internal/api/script/handler_legacy_*.go (FASE 2.1 PR-VOICE-FREEZE):"
    echo "$literal_calls"
    echo ""
    echo "Fix: handler_legacy_*.go is under FASE 2.1 FREEZE until 2026-12-31."
    echo "      No new imports are accepted. If a critical CVE requires an"
    echo "      import (rare; should never happen for a retired-adapter path),"
    echo "      prepend the magic marker on the line preceding the import:"
    echo "    // ARCH-ALLOWLIST: legacy-script-freeze"
    echo "    import ("
    echo "      \"github.com/Marcuss-ops/PipelineGen/.../pkg\""
    echo "    )"
    echo "Per AGENTS.md §7 every marker entry requires explicit owner + deadline."
    exit 1
fi
if [ "$comment_count" -gt 0 ]; then
    echo "WARN (${comment_count} hits): comment-only external/internal import references in handler_legacy_*.go"
    echo "      (descriptive prose; non-fatal per godlike/07 no-fake-availability)"
fi
if [ "$allowlist_count" -gt 0 ]; then
    echo "WARN (${allowlist_count} hits): ARCH-ALLOWLIST: legacy-script-freeze marker sites in handler_legacy_*.go"
    echo "      (audit-pin residue; non-fatal; tracked per godlike/06)"
fi
echo "OK: FASE 2.1 PR-VOICE-FREEZE respected — no new imports in legacy script handlers"
