#!/usr/bin/env bash
# scripts/ci/architecture/checks/lib/50_jobs_lib.sh — shared shell library
# for the 50_jobs_* sub-checks replacing the original monolithic
# scripts/ci/architecture/checks/50_jobs.sh (2144 lines / 115 KB), split
# per the same precedent as commit
# "refactor(ci): split ci-architectural-checks.sh (4618 => 77 + 59 lib)".
#
# Materials exposed:
#   1. SUBCHECKS registry — the ordered source-list the orchestrator
#      scripts/ci/architecture/checks/50_jobs.sh iterates.
#   2. Allowlist filter helpers extracted from the inline AWK pre-passes
#      that lived inside ~12 sections of the original 50_jobs.sh
#      (per godlike/06 SSOT and the user's "estrai helpers e allowlist
#      in lib" directive).
#
# Each sub-check file under scripts/ci/architecture/checks/50_jobs_*.sh
# KEPT the inline awk from the corresponding section of the original
# 50_jobs.sh verbatim (see scripts/ci/architecture/checks/lib/50_jobs_section_map.json
# for the byte-precise line_start/line_end ranges that fed the
# splitter). The extracted helpers below are AVAILABLE for future
# DRY-ification; the verbatim sub-check bodies ensure byte-identical
# stdout vs the original monolithic script (the user's "identici i
# messaggi di errore e i codici di uscita" contract).
#
# Invocation modes supported by the orchestrator:
#   - `bash scripts/ci/architecture/checks/50_jobs.sh` direct invocation
#     from REPO_ROOT cwd (matches the historical wiring of CI).
#   - `source` from scripts/ci/architecture/checks/all_checks.sh, where
#     BASH_SOURCE[0] still resolves to 50_jobs.sh (sourced frames push
#     a new BASH_SOURCE[0]) and SCRIPT_DIR/REPO_ROOT are the standard
#     <architectural-checks>/<repo-root> tuple.
#
# Fail-fast: the orchestrator passes `--exit-on-fail` semantics by
# chaining `bash sub || exit 1`; the lib MUST NOT itself emit `exit`
# (a sourced orchestrator would propagate exit to all_checks.sh's
# `set -e`, and 50_jobs_lib.sh being `.`'d from inside the orchestrator
# could cause the parent shell to abort before the loop starts).
# Helpers defined here are pure: they return via stdout and never
# invoke `exit` themselves.

# ── Sub-check registry ──────────────────────────────────────────────
# 18 sub-checks in canonical execution order. Disambiguated for
# sections where the source 50_jobs.sh has duplicate `# ── Check N: ──`
# headers (Check 50 appears at L1..108 AND L1627..1702; Check 54
# appears at L314..485 AND L1703..1926 — distinct gates sharing the
# canonical numbered label per the source's institutional memory).
# The canonical mapping is asserted in scripts/ci/architecture/checks/lib/50_jobs_section_map.json
# (regenerated by lib/50_jobs_profile.sh; current state has 18
# entries covering L1..2144 with no gap and no overlap).
# Filenames mirror the deterministic slug set the Python extractor
# (/tmp/extract_50_jobs_subchecks.py) emitted from each section's title;
# hand-curated only at the 60-char truncation boundary. The list order
# matches scripts/ci/architecture/checks/lib/50_jobs_section_map.json's
# array order (= the original monolithic 50_jobs.sh's execution order).
SUBCHECKS=(
    "50_jobs_forbid_void_register_methods_that_take_jobsservice.sh"
    "50_jobs_forbid_raw_string_enqueue.sh"
    "50_jobs_forbid_direct_artifactuploader_wire_calls_outside_canonical_.sh"
    "50_jobs_forbid_direct_atomic_complete_wire_calls_outside_canonical_s.sh"
    "50_jobs_fase_37_commit_3_gate_banning_infra_imports_in_monitor.sh"
    "50_jobs_forbid_legacy_script_columns.sh"
    "50_jobs_go_vet_internal_drift_gate.sh"
    "50_jobs_forbid_infrastructure_imports_in_api_layer.sh"
    "50_jobs_contextbackground_contextwithoutcancel_exemption_tracking.sh"
    "50_jobs_anti_reintro_gate_for_diagnostic_snapshot_artefacts.sh"
    "50_jobs_forbid_recreation_of_internalapicommon.sh"
    "50_jobs_forbid_databasesql_import_in_applicationapi_production_paths.sh"
    "50_jobs_section.sh"
    "50_jobs_channel_monitor_e2e_dedup_contract_test_coverage.sh"
    "50_jobs_forbid_retry_classifier_substring_matcher_outside_pkgretry.sh"
    "50_jobs_forbid_legacy_stock_pipeline_keywords.sh"
    "50_jobs_forbid_portsscriptrecord_literal_outside_canonical_allowlist.sh"
    "50_jobs_forbid_direct_vlm_http_calls.sh"
)

# ── Allowlist filter (extracted; available for future DRY-ification) ──
# Mirrors the inline `awk -F: '...'` pre-pass that lived in ~12
# sections of the original 50_jobs.sh. Drops:
#   (a) full-line `//` comments (descriptive prose),
#   (b) ARCH-ALLOWLIST marker items (the `// ARCH-ALLOWLIST: <kind>`
#       line itself),
#   (c) lines within <window> lines downstream of an ARCH-ALLOWLIST
#       marker site in the SAME file (default window=25 matches
#       Checks 5/10b/11 semantics; Check 54 uses <self> mode and is
#       kept verbatim — see the comments around its extraction).
# Byte-equivalence: the awk regex, field-extraction loop, and marker
# marker-mechanics are mirrored 1:1 (subject to fish-regex-token
# ordering; verified against the original inline pattern).
#
# Usage:
#   arch_filter_with_allowlist "$rg_out" <kind> [<window>=25]
#
# Note: sub-check bodies intentionally do NOT consume this helper
# (kept inline for byte-parity). Reference it from new sub-checks
# going forward (post-50_jobs-split teardown).
arch_filter_with_allowlist() {
    local input="${1:-}"
    local kind="${2:-}"
    local window="${3:-25}"
    printf '%s\n' "${input}" | awk -F: -v kind="${kind}" -v window="${window}" '
        BEGIN { prev_marker = 0 }
        {
            rest = ""
            for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
            pat = "^[[:space:]]*\\/\\/.*ARCH-ALLOWLIST:[[:space:]]*" kind "[[:space:]]*"
            if (rest ~ pat) {
                markers[$1] = (markers[$1] == "" ? $2 : markers[$1] "," $2)
                next
            }
            if (rest ~ /^[[:space:]]*\\/\\//) next
            n = (markers[$1] == "" ? 0 : split(markers[$1], mlist, ","))
            allowed = 0
            for (mi = 1; mi <= n; mi++) {
                m = mlist[mi] + 0
                if (m > 0 && $2 + 0 >= m + 1 && $2 + 0 <= m + window) { allowed = 1; break }
            }
            if (allowed) next
            print
        }'
}

# ── Comment-only filter (extracted; available for future DRY-ification) ──
# Used by sections whose awk pre-pass has no ARCH-ALLOWLIST marker
# filter (Checks 51/52/53/55/36/42/...). Mirrors the inline awk's
# `(rest ~ /^\/\//) next` drop-pattern.
#
# Usage:
#   printf '%s\n' "$rg_out" | arch_filter_drop_comments
#   rg -n ... | arch_filter_drop_comments
arch_filter_drop_comments() {
    awk -F: '
        {
            rest = ""
            for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i
            if (rest ~ /^[[:space:]]*\\/\\//) next
            print
        }'
}
