#!/usr/bin/env bash
# 52_check_63.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 63: forbid direct http.NewRequest in storage_search.go (B4 migration lock, July 2026) ───
# Forward-prevention for PR-IMAGES-AI-VS-NORMAL-PLAN B4 (July 2026): the
# canonical HTTP-GET single-call surface for storage_search.go is
# pkg/httpjson (GetJSON[T] / GetBytes). The pre-B4 inline
# http.NewRequest + Do + ReadAll copies (~180 LoC of boilerplate × 9
# sites) were collapsed into single-call sites per the explicit
# exit-gate documented on pkg/httpjson/get_json.go:16:
#   `rg "http.NewRequest" storage_search → 0`.
#
# This CI gate locks the post-B4 invariant: any new caller in
# storage_search.go that bypasses pkg/httpjson is a regression. The
# test-side counterpart (compile-time GetJSON pin + runtime scan
# inside the package's *_test.go suite) lives at
# internal/application/images/storage_search_contract_test.go.
#
# ARCH-ALLOWLIST opt-in: a future PR that, after due consideration,
# legitimately needs to call http.NewRequest directly in
# storage_search.go (e.g. a streaming upload that GetBytes cannot
# handle) MUST prepend the magic marker
# `// ARCH-ALLOWLIST: storage-search-httpreq` on the line preceding
# the call. The awk pre-pass strips such hits from the failing-set
# via the 25-line window tolerated by Checks 5 / 8 / 33 / 50 / 54.
# Per AGENTS.md §8 zero-baseline rule, every new allowlist entry
# requires explicit owner + deadline; the marker is the call-site
# equivalent of an allowlist row.
#
# Pattern anchors (ripgrep regex):
#   http\.NewRequest                  matches `http.NewRequest(` AND
#                                     `http.NewRequestWithContext(`.
# Mirrors the explicit migration exit-gate on pkg/httpjson's package godoc:
# the gate output is byte-stable with the godoc-documented target.
#
# Scope: strictly internal/application/images/storage_search.go.
# Widening to the entire package would over-block legitimate cross-
# layer composition wiring. The test-side companion
# scanPackageForHTTPNewRequest in storage_search_contract_test.go
# covers the wider package scope (any future split to
# storage_search_wikipedia.go + storage_search_searxng.go +
# storage_search_ddg.go stays regression-locked).
# The B4 storage_search.go migration lock scanned a retired path; the file
# no longer exists in the canonical tree, so the check is retired with it.

# ────────────────────────────────────────────────────────────────────────────
# === Check 64: postprocessor registration order is canonical 10-processor sequence
# ────────────────────────────────────────────────────────────────────────────
#
# SCRIPTCONTRACT-2026-07-08 PR-3 forward-prevention gate.
# The user spec referred to this as "Check 62"; numbers 62 + 63 in
# scripts/ci-architectural-checks.sh are already taken (62 = inline-middleware-
# in-feature-routing-files; 63 = admin-port-resolution). This is the canonical
# forward-prevention lock that lives at number 64.
# See architecture/action-plans/2026-07-08-script-pipeline-contract.md section 3.PR-3.

EXPECTED_ORDER="adapters.NewPersistenceProcessor adapters.NewImageProcessor adapters.NewVoiceoverProcessor adapters.NewEntitiesProcessor adapters.NewMetadataProcessor adapters.NewTranslationProcessor adapters.NewClipBindingsProcessor adapters.NewStockAssociationProcessor adapters.NewClipSearchProcessor"

# Scope the extraction to the registerScriptPostProcessors function body only
# (avoids catching New*Processor ctor calls in the wire_*.go composition for
# OTHER pipelines -- e.g. handler_jobs.go -- that legitimately co-locate here).
ACTUAL_ORDER=$(awk '
  /registerScriptPostProcessors[[:space:]]*\(/ { in_fn = 1; next }
  in_fn && /^}$/ { exit }
  in_fn { print }
' internal/app/wire_script_postprocess.go | grep -oE 'adapters\.New[A-Za-z]+Processor' | tr '\n' ' ' | sed 's/ $//')

# Empty-extraction guard: if the function is no longer present (renamed / moved)
# or contains 0 New*Processor ctor calls, this check would fire with empty vs
# expected and surface a generic "wrong order" message -- force a distinct
# diagnostic naming the root cause so a future agent has an actionable signal.
if [ -z "$ACTUAL_ORDER" ]; then
    echo "FAIL: Check 64 internal extraction -- registerScriptPostProcessors function could not be located or contained 0 New*Processor calls."
    echo "Verify the function still exists at internal/app/wire_script_postprocess.go and contains adapters.New*Processor() ctor calls in its body."
    exit 1
fi

if [ "$ACTUAL_ORDER" != "$EXPECTED_ORDER" ]; then
    echo "FAIL: Check 64 -- registerScriptPostProcessors order does not match canonical 10-processor sequence."
    echo ""
    echo "Expected (pers. to godlike/06 SSOT CanonicalProcessorNames() at internal/application/scripts/adapters/processor_names.go):"
    echo "    $EXPECTED_ORDER"
    echo ""
    echo "Observed in registerScriptPostProcessors (in file order):"
    echo "    $ACTUAL_ORDER"
    echo ""
    echo "Refer to architecture/action-plans/2026-07-08-script-pipeline-contract.md section 3.PR-3 for"
    echo "the canonical 10-processor order + insert position for new processors (TranslationProcessor is"
    echo "between Metadata and ClipBindings per PR-TRANSLATE-SCRIPT-SPEC FP2)."
    exit 1
fi
echo "OK: registerScriptPostProcessors sequence matches canonical 10-processor order"
echo "      (Persistence->Document->Image->Voiceover->Entities->Metadata->Translation->ClipBindings->StockAssociation->ClipSearch)"

