#!/usr/bin/env bash
# 58_check_72.sh — sourced by scripts/ci-architectural-checks.sh (dispatcher).
# AUTO-GENERATED by /tmp/split_ci.py from the original monolithic file.
# Do NOT hand-edit: edit scripts/ci-architectural-checks.sh and re-run
# the splitter (or move body content out-of-line manually here with a
# corresponding dispatcher update).

# ── Check 72: SearchAggregator uniqueness (Wave 5, July 2026) ──
# There must be exactly one SearchAggregator in the production
# codebase. Multiple aggregators or ad-hoc backend fan-out bypass
# the canonical ranking/dedup pipeline.
#
# Allowlist:
#   - internal/application/search/aggregator.go : the canonical Aggregator definition.
#   - *_test.go                                : tests may construct aggregators for verification.
#
# Pattern anchors:
#   search\.NewAggregator\(  — canonical constructor
#   NewAggregator\(        — generic constructor name collision

echo "=== Check 72: SearchAggregator uniqueness (Wave 5, July 2026) ==="
aggregator_count=$(rg -n --type go \
    -e 'search\.NewAggregator\(' \
    -e '\bNewAggregator\(' \
    --glob '!**/search/aggregator.go' \
    --glob '!**/*_test.go' \
    internal/ 2>/dev/null \
    | awk -F: '{ rest = ""; for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i; if (rest ~ /^[[:space:]]*\/\//) next; print }' \
    | wc -l | awk '{print $1+0}')
if [ "$aggregator_count" -gt 0 ]; then
    echo "FAIL: extra SearchAggregator constructor found outside canonical aggregator:"
    rg -n --type go \
        -e 'search\.NewAggregator\(' \
        -e '\bNewAggregator\(' \
        --glob '!**/search/aggregator.go' \
        --glob '!**/*_test.go' \
        internal/ 2>/dev/null \
        | awk -F: '{ rest = ""; for (i = 3; i <= NF; i++) rest = rest (i > 3 ? ":" : "") $i; if (rest ~ /^[[:space:]]*\/\//) next; print }'
    echo ""
    echo "Fix: route all search aggregation through the canonical search.Aggregator."
    echo "     Do not introduce additional aggregator implementations."
    exit 1
fi
echo "OK: no extra SearchAggregator constructors outside canonical aggregator"
