// ARCH-ALLOWLIST: im-001-multipart-canonical-surface
// Per IMAGES-T04-MULTIPART (Phase 9 cycle 2, 2026-07-04):
// the canonical multipart-form upload surface for clip assets
// lives in internal/api/assets/clips/ingest.go::UploadVideoClip
// (the IngestHandler POST /upload-video route), NOT in this
// package. This package's /upload handler binds JSON (UploadRequest
// with image_url field), not multipart. The two surfaces are
// distinct concerns:
//   - clips/ingest.go::UploadVideoClip  (multipart) -- clip video files
//     via *upload.UseCase + dispatcher + outbox event pipeline.
//   - images/impl.go::Upload           (JSON, image_url) -- legacy
//     image-asset URL ingestion (kept for back-compat with the
//     image-search surface).
//
// godlike/06 SSOT: one canonical owner per fact -- the clip
// multipart path lives at clips/ingest.go; the image URL path lives
// here. Operators MUST NOT migrate clip uploads to /api/images/upload
// (wrong surface; the dispatcher + outbox pipeline is the
// load-bearing infrastructure for clip indexing).
//
// Package images (api/images) — upload_handler.go holds the legacy
// JSON-based image upload handler. This is the RETRIEVED territory
// (URL ingestion, not AI generation). Per the golden rule:
// retrieved = images found, downloaded, or ingested from normal
// sources (NOT generated by AI).
package images

import (
	"strings"

	"github.com/Marcuss-ops/PipelineGen/internal/application/assets/ingest"
	"github.com/Marcuss-ops/PipelineGen/pkg/apiutil"
	"github.com/gin-gonic/gin"
)

// Upload handles POST /api/images/upload — legacy image-asset URL
// ingestion. Accepts JSON with image_url; delegates to the ingest
// service when available, falling back to SearchAndDownload.
func (h *ImagesHandler) Upload(c *gin.Context) {
	var req UploadRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		apiutil.BadRequest(c, err.Error())
		return
	}

	if req.Name == "" {
		req.Name = req.Subject
	}

	slug := strings.ReplaceAll(strings.ToLower(req.Subject), " ", "-")

	if h.ingestSvc != nil && req.URL != "" {
		res, err := h.ingestSvc.Ingest(c.Request.Context(), &ingest.Request{
			Kind:   string(ingest.KindImage),
			URL:    req.URL,
			Name:   req.Name,
			Group:  slug,
			Tags:   req.Tags,
			Source: "upload",
		})
		if err != nil {
			apiutil.InternalError(c, err)
			return
		}
		apiutil.OK(c, res)
		return
	}

	// Fallback
	asset, err := h.service.SearchAndDownload(c.Request.Context(), slug, req.Name, req.URL, req.Lang, req.Tags)
	if err != nil {
		apiutil.InternalError(c, err)
		return
	}

	apiutil.OK(c, asset)
}
