package clips

// mediaAssetColumns preserves the legacy scan order while sourcing physical
// locations and processing state from the canonical satellite tables.
const mediaAssetColumns = `
	id,
	COALESCE(source, '') AS source,
	COALESCE(name, '') AS name,
	COALESCE(tags, '[]') AS tags,
	COALESCE(tags_norm, '') AS tags_norm,
	COALESCE(embedding_json, '[]') AS embedding_json,
	COALESCE(duration_ms, 0) AS duration_ms,
	COALESCE(url, '') AS url,
	COALESCE(media_type, '') AS media_type,
	COALESCE((SELECT p.status FROM asset_processing p WHERE p.asset_id = media_assets.id ORDER BY p.updated_at DESC, p.id DESC LIMIT 1), '') AS status,
	COALESCE((SELECT l.uri FROM asset_locations l WHERE l.asset_id = media_assets.id AND l.location_kind = 'local' LIMIT 1), '') AS local_path,
	COALESCE((SELECT l.uri FROM asset_locations l WHERE l.asset_id = media_assets.id AND l.location_kind = 'local' LIMIT 1), '') AS relative_path,
	COALESCE((SELECT l.external_id FROM asset_locations l WHERE l.asset_id = media_assets.id AND l.location_kind = 'drive' LIMIT 1), '') AS drive_file_id,
	COALESCE(folder_id, '') AS drive_folder_id,
	COALESCE((SELECT l.web_view_link FROM asset_locations l WHERE l.asset_id = media_assets.id AND l.location_kind = 'drive' LIMIT 1), '') AS drive_link,
	COALESCE((SELECT l.download_url FROM asset_locations l WHERE l.asset_id = media_assets.id AND l.location_kind = 'drive' LIMIT 1), '') AS download_link,
	COALESCE((SELECT l.file_hash FROM asset_locations l WHERE l.asset_id = media_assets.id ORDER BY l.is_primary DESC, l.id ASC LIMIT 1), '') AS file_hash,
	COALESCE(metadata_json, '{}') AS metadata_json,
	COALESCE(visual_embedding, '[]') AS visual_embedding,
	COALESCE(transcript_embedding, '[]') AS transcript_embedding,
	created_at,
	COALESCE(updated_at, '') AS updated_at,
	COALESCE(width, 0) AS width,
	COALESCE(height, 0) AS height,
	COALESCE(lifecycle_state, 'ready') AS lifecycle_state,
	COALESCE(deleted_at, '') AS deleted_at,
	COALESCE(folder_id, '') AS folder_id,
	COALESCE(parent_folder_id, '') AS parent_folder_id,
	COALESCE(folder_path, '') AS folder_path,
	COALESCE(category, '') AS category,
	COALESCE(filename, '') AS filename,
	COALESCE((SELECT p.error_message FROM asset_processing p WHERE p.asset_id = media_assets.id AND p.error_message != '' ORDER BY p.updated_at DESC, p.id DESC LIMIT 1), '') AS error,
	COALESCE(thumb_url, '') AS thumb_url,
	COALESCE(phash, '') AS phash,
	COALESCE(search_text, '') AS search_text,
	COALESCE(scene_type, '') AS scene_type,
	COALESCE(quality_score, 0.0) AS quality_score,
	COALESCE(reuse_count, 0) AS reuse_count,
	COALESCE(last_used_at, '') AS last_used_at`
