package app

// cliprender_plan.go wires the plan-facing adapters for the clip.render
// preparation phase:
//
//   - clipRenderSubtitleCompiler — deterministic ASS artifact (burn|sidecar)
//     via texttracks.CompileASSContent (the single owner of ASS content).
//   - clipRenderExecutorAdapter — maps the rustexec.ClipRenderer result onto
//     the capability's RenderOutcome verbatim (media facts come from the Rust
//     metadata, never re-derived).
//
// Every adapter is fail-closed: a missing dependency surfaces a typed error
// at call time, never a silent no-op path.

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/Marcuss-ops/PipelineGen/internal/application/assets/texttracks"
	cliprender "github.com/Marcuss-ops/PipelineGen/internal/capabilities/cliprender"
	"github.com/Marcuss-ops/PipelineGen/internal/platform/media/rustexec"
)

// ── SubtitleCompiler (deterministic ASS) ─────────────────────────────

// clipRenderSubtitleCompiler implements the capability's SubtitleCompiler
// port with the canonical ASS generator (texttracks.CompileASSContent — the
// single owner of ASS content generation). The artifact is written into the
// run's scratch dir (subtitles.ass) and validated before the plan is sealed.
//
// Determinism: identical cues + style ALWAYS produce identical bytes (the
// generator embeds no timestamps/randoms/paths). Mode burn|sidecar only
// tags the artifact — the ASS bytes are the same, the render pass decides
// whether to rasterize libass (burn) or ship the file (sidecar).
//
// Fail-closed: empty cues, an invalid mode, or an invalid generated ASS is a
// typed error — speech recognition is NEVER regenerated just to build
// subtitles (feature spec §5).
type clipRenderSubtitleCompiler struct{}

// assContentCache reuses deterministic ASS generation across repeated renders
// of the same transcript/style. It is intentionally a content cache, not a
// claim of GPU glyph rasterization: libass still owns burn-time rasterization.
// The key includes all inputs that affect generated bytes; run-specific paths
// never enter the key.
var assContentCache sync.Map // map[string]string

func (c *clipRenderSubtitleCompiler) Compile(ctx context.Context, in cliprender.SubtitleCompileInput) (*cliprender.SubtitleArtifact, error) {
	switch in.Mode {
	case cliprender.SubtitlesModeBurn, cliprender.SubtitlesModeSidecar:
	default:
		return nil, fmt.Errorf("%w: invalid subtitle mode %q", cliprender.ErrSubtitleCompileUnavailable, in.Mode)
	}
	if len(in.Cues) == 0 {
		return nil, fmt.Errorf("%w: zero cues for asset %q — subtitles cannot be compiled without transcript timing (speech recognition is never regenerated for subtitles)", cliprender.ErrSubtitleCompileUnavailable, in.AssetID)
	}
	// Canonical clip tracks can contain a final cue from the source timeline
	// that extends past the extracted clip boundary. Keep the canonical text,
	// but clip only its visible interval to the actual media duration; cues
	// wholly after the boundary are not rendered. This preserves fail-closed
	// validation while avoiding an invalid ASS for an otherwise valid clip.
	cues := trimClipRenderCues(in.Cues, in.ClipDurationMS)
	if len(cues) == 0 {
		return nil, fmt.Errorf("%w: no cues remain inside clip duration for asset %q", cliprender.ErrSubtitleCompileUnavailable, in.AssetID)
	}
	canonicalCues := mapClipRenderCues(cues)
	keyMaterial := fmt.Sprintf("%s\x00%s\x00%v", in.Language, in.StyleID, canonicalCues)
	key := fmt.Sprintf("%x", sha256.Sum256([]byte(keyMaterial)))
	var content string
	if cached, ok := assContentCache.Load(key); ok {
		content = cached.(string)
	} else {
		generated, compileErr := texttracks.CompileASSContent(canonicalCues, in.StyleID)
		if compileErr != nil {
			return nil, fmt.Errorf("%w: compile ASS content: %v", cliprender.ErrSubtitleCompileUnavailable, compileErr)
		}
		content = generated
		assContentCache.Store(key, content)
	}
	if err := os.MkdirAll(in.OutputDir, 0o755); err != nil {
		return nil, fmt.Errorf("create subtitle output dir %q: %w", in.OutputDir, err)
	}
	localPath := filepath.Join(in.OutputDir, "subtitles.ass")
	sum := sha256.Sum256([]byte(content))
	sha := hex.EncodeToString(sum[:])
	// Reuse an already materialized artifact for the same canonical
	// transcript/style. The run-local file is a hard link to the durable
	// content-addressed cache, so repeated clip jobs do not regenerate or
	// rewrite identical subtitle bytes. The existing file is still validated
	// before it is accepted by the plan.
	if existing, readErr := os.ReadFile(localPath); readErr == nil && string(existing) == content {
		if err := texttracks.ValidateASSFile(localPath, in.ClipDurationMS); err != nil {
			return nil, fmt.Errorf("%w: invalid existing ASS for asset %q: %v", cliprender.ErrSubtitleCompileUnavailable, in.AssetID, err)
		}
		return &cliprender.SubtitleArtifact{LocalPath: localPath, SHA256: sha, Mode: in.Mode, StyleID: in.StyleID}, nil
	}
	cacheDir := filepath.Join(filepath.Dir(filepath.Dir(in.OutputDir)), "subtitle-cache")
	cachePath := filepath.Join(cacheDir, sha+".ass")
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		return nil, fmt.Errorf("create subtitle cache dir %q: %w", cacheDir, err)
	}
	if _, err := os.Stat(cachePath); os.IsNotExist(err) {
		if err := os.WriteFile(cachePath, []byte(content), 0o644); err != nil {
			return nil, fmt.Errorf("write cached ASS artifact %q: %w", cachePath, err)
		}
	} else if err != nil {
		return nil, fmt.Errorf("stat cached ASS artifact %q: %w", cachePath, err)
	}
	if err := os.Link(cachePath, localPath); err != nil {
		// Hard links can be unavailable on a different filesystem. Preserve
		// correctness with a copy only in that exceptional case.
		if copyErr := os.WriteFile(localPath, []byte(content), 0o644); copyErr != nil {
			return nil, fmt.Errorf("link/copy ASS artifact %q: link=%v copy=%w", localPath, err, copyErr)
		}
	}
	if err := texttracks.ValidateASSFile(localPath, in.ClipDurationMS); err != nil {
		return nil, fmt.Errorf("%w: invalid generated ASS for asset %q: %v", cliprender.ErrSubtitleCompileUnavailable, in.AssetID, err)
	}
	return &cliprender.SubtitleArtifact{
		LocalPath: localPath,
		SHA256:    sha,
		Mode:      in.Mode,
		StyleID:   in.StyleID,
	}, nil
}

func trimClipRenderCues(in []cliprender.Cue, durationMS int64) []cliprender.Cue {
	if durationMS <= 0 {
		return append([]cliprender.Cue(nil), in...)
	}
	out := make([]cliprender.Cue, 0, len(in))
	for _, cue := range in {
		if cue.StartMs >= durationMS {
			continue
		}
		if cue.EndMs > durationMS {
			cue.EndMs = durationMS
		}
		if cue.EndMs > cue.StartMs {
			out = append(out, cue)
		}
	}
	return out
}

// ── RenderExecutor (Rust render_clip boundary) ───────────────────────

// clipRenderExecutor is the narrow seam over the rustexec.ClipRenderer so
// the composition-root adapter stays testable without the Rust process.
// The concrete implementation re-validates the sealed plan, verifies every
// referenced artifact, resolves the encoder policy from the composition-root
// media config, and refuses success without a non-empty output.
type clipRenderExecutor interface {
	RenderClip(ctx context.Context, plan cliprender.ClipRenderPlanV1, backend cliprender.RenderBackend) (rustexec.ClipRenderResult, error)
}

// clipRenderExecutorAdapter bridges the rustexec.ClipRenderer to the
// capability's RenderExecutor port. It resolves the render backend through
// the capability's RenderBackendResolver (probed host capabilities, never a
// hardcoded CUDA path) and reports the resolved backend in the outcome.
// Fail-closed: an unwired renderer is a typed error (never a silent no-op
// that reports a rendered clip).
type clipRenderExecutorAdapter struct {
	renderer clipRenderExecutor
	chronon  clipRenderExecutor
	resolver *cliprender.RenderBackendResolver
	probe    cliprender.BackendCapabilityProbe
}

func (a *clipRenderExecutorAdapter) Render(ctx context.Context, plan cliprender.ClipRenderPlanV1) (*cliprender.RenderOutcome, error) {
	if a == nil || (a.renderer == nil && a.chronon == nil) {
		return nil, fmt.Errorf("%w: Rust clip renderer not wired", cliprender.ErrRenderPhaseNotImplemented)
	}
	if a.chronon != nil && (plan.Watermark != nil || plan.Subtitles != nil || plan.Background != nil && plan.Background.Mode != cliprender.BackgroundModeNone) {
		result, err := a.chronon.RenderClip(ctx, plan, cliprender.BackendChrononVulkan)
		if err == nil {
			return &cliprender.RenderOutcome{OutputPath: result.OutputPath, SizeBytes: result.SizeBytes, DurationSec: result.DurationSec, Width: result.Width, Height: result.Height, FPSNum: result.FPSNum, FPSDen: result.FPSDen, Backend: cliprender.BackendChrononVulkan, FFmpegMS: result.FFmpegMS, AudioCopyEligible: result.AudioCopyEligible, AudioEncodePasses: result.AudioEncodePasses, SubtitleRasterCPU: result.SubtitleRasterCPU, NativeMedia: result.NativeMedia, GPUCopyBytes: result.GPUCopyBytes}, nil
		}
		// Chronon is preferred for overlays, but a transient CUDA/VRAM failure
		// must not discard an otherwise valid clip. Continue through the
		// canonical software backend below.
	}
	if a.renderer == nil {
		return nil, fmt.Errorf("%w: Rust clip renderer not wired", cliprender.ErrRenderPhaseNotImplemented)
	}
	backend, err := cliprender.ResolveBackend(ctx, a.probe, a.resolver, plan)
	if err != nil {
		return nil, err
	}
	result, err := a.renderer.RenderClip(ctx, plan, backend)
	if err != nil {
		return nil, err
	}
	return &cliprender.RenderOutcome{
		OutputPath:        result.OutputPath,
		SizeBytes:         result.SizeBytes,
		DurationSec:       result.DurationSec,
		Width:             result.Width,
		Height:            result.Height,
		FPSNum:            result.FPSNum,
		FPSDen:            result.FPSDen,
		Backend:           backend,
		FFmpegMS:          result.FFmpegMS,
		AudioCopyEligible: result.AudioCopyEligible,
		AudioEncodePasses: result.AudioEncodePasses,
		SubtitleRasterCPU: result.SubtitleRasterCPU,
		NativeMedia:       result.NativeMedia,
		GPUCopyBytes:      result.GPUCopyBytes,
	}, nil
}
