// Command capability-inventory-aggregate merges the split capability inventory
// into a conventional single YAML document for legacy tools and audits.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"

	"gopkg.in/yaml.v3"
)

type manifest struct {
	Sections []string `yaml:"sections"`
}

func main() {
	manifestPath := flag.String("manifest", "architecture/capability_inventory.yaml", "inventory manifest path")
	outPath := flag.String("out", "architecture/capability_inventory.generated.yaml", "aggregated output path")
	dryRun := flag.Bool("dry-run", false, "compare generated bytes with the committed output")
	flag.Parse()

	generated, err := aggregate(*manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "capability-inventory-aggregate: %v\n", err)
		os.Exit(2)
	}
	if *dryRun {
		committed, err := os.ReadFile(*outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "capability-inventory-aggregate: read %s: %v\n", *outPath, err)
			os.Exit(2)
		}
		if !bytes.Equal(generated, committed) {
			fmt.Fprintf(os.Stderr, "capability-inventory-aggregate: generated output differs from %s\n", *outPath)
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*outPath, generated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "capability-inventory-aggregate: write %s: %v\n", *outPath, err)
		os.Exit(2)
	}
}

func aggregate(manifestPath string) ([]byte, error) {
	manifestData, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}
	var m manifest
	if err := yaml.Unmarshal(manifestData, &m); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}
	if len(m.Sections) == 0 {
		return nil, fmt.Errorf("manifest has no sections")
	}

	merged := make(map[string]any)
	baseDir := filepath.Dir(manifestPath)
	for _, section := range m.Sections {
		path := section
		if !filepath.IsAbs(path) {
			path = filepath.Join(baseDir, path)
		}
		data, err := os.ReadFile(filepath.Clean(path))
		if err != nil {
			return nil, fmt.Errorf("read section %s: %w", section, err)
		}
		var part map[string]any
		if err := yaml.Unmarshal(data, &part); err != nil {
			return nil, fmt.Errorf("parse section %s: %w", section, err)
		}
		if err := mergeTopLevel(merged, part, section); err != nil {
			return nil, err
		}
	}

	out, err := yaml.Marshal(merged)
	if err != nil {
		return nil, fmt.Errorf("marshal aggregate: %w", err)
	}
	return out, nil
}

func mergeTopLevel(dst, src map[string]any, section string) error {
	for key, value := range src {
		existing, exists := dst[key]
		if !exists {
			dst[key] = value
			continue
		}
		existingList, existingOK := existing.([]any)
		valueList, valueOK := value.([]any)
		if existingOK && valueOK {
			dst[key] = append(existingList, valueList...)
			continue
		}
		if reflect.DeepEqual(existing, value) {
			continue
		}
		return fmt.Errorf("section %s conflicts on top-level key %q", section, key)
	}
	return nil
}
