// Package staging — staging.go (FASE 3-A, July 2026).
//
// Canonical typed port for the durable artifact staging store.
//
// godlike/06 SSOT (one canonical owner per fact): this file is
// the SOLE canonical owner of:
//   - the `Stager` Pattern-0 port.
//   - the `StageInput` request envelope.
//   - the `StagedReceipt` response envelope.
//
// godlike/06 SSOT rationale: the staging port is the canonical
// seam between producers (callers that produce a single artifact)
// and the durable FS-layer (workspace path, atomic rename,
// SHA-during-write). FASE 3-B (separate cut) introduces a sibling
// StagesRepository port for the `artifact_stages` SQLite row insert
// + outbox commit. The two ports are MANDATORILY split: keeping
// disk + DB on one interface would force the SQLite dep into
// every test that exercises only the disk discipline.
//
// godlike/07 fail-closed: every error returned from Stager.Stage
// wraps a typed sentinel (errors.Is-compatible). There is NO
// zero-value fallback for any failure mode.
//
// Honest scope-lock (godlike/07): this file does NOT cover the
// Drive upload, the SQLite INSERT, the outbox event commit, the
// per-job atomic publish, or the finalizer. Those belong to
// FASE 3-B/C/D respectively.
package assets

import (
	"context"
	"io"
	"time"
)

// Stager is the canonical Pattern-0 port for durable artifact
// staging. The port is FS-only in FASE 3-A scope. A future
// composition-root-level StageService is expected to wire the
// Stager together with StagesRepository (3-B) to compose
// `Stage(file) → INSERT(artifact_stages, STAGED) → outbox commit`.
//
// Method semantics (Pattern 0):
//   - implementations MUST be concurrency-safe post-construction
//     (no shared mutable state outside of constructor-supplied
//     dependencies).
//   - Stage MUST compute SHA-256 of the inbound byte stream
//     DURING write (NOT post-stat). This is the canonical
//     user-spec lock — post-stat hash is forbidden.
//   - Stage MUST write to a `.partial/<id>.tmp` file, fsync file
//   - parent dir, atomically rename to the canonical `<id>`
//     path, and fsync the workspace dir so the rename is durable.
//   - Stage MUST clean up the `.tmp` file on ANY non-success path
//     via deferred unlink so the next Stage attempt can retry.
//   - RecoverOrphans MUST be safe to call concurrently with Stage
//     (readdir + unlink only — does not touch canonical paths).
type Stager interface {
	// Stage writes the artifact's content to a temp file,
	// computes SHA-256 during the write, fsyncs the file + the
	// directory, atomically renames to the canonical path, and
	// returns the receipt (LocalPath, Hash, Size, MIME,
	// WorkspacePath).
	//
	// Failure modes wrap typed sentinels:
	//   - nil ctx / nil Content → ErrStagerInvalidInput
	//   - empty ArtifactID / invalid MIME / bad ID format → ErrStagerInvalidInput
	//   - inbound size exceeds cfg.MaxArtifactBytes → wrapped ErrQuotaExceeded
	//   - workspace+incoming exceeds cfg.MaxWorkspaceBytes → wrapped ErrQuotaExceeded
	//   - workspace free-space < 2*incoming_size → wrapped ErrDiskSpaceLow
	//   - inbound stream produces 0 bytes → wrapped ErrArtifactStageEmpty
	//   - StageInput.ExpectedSHA256 non-empty AND computed hash differs →
	//     wrapped ErrArtifactStageHashMismatch
	//   - existing canonical file hash differs from new computed hash →
	//     wrapped ErrStagerIDCollision (corruption signal)
	//   - io.Copy from Content fails → wrapped ErrStagerReadFailed
	//   - file.Sync or parent-dir fsync fails → wrapped ErrStagerFsyncFailed
	//   - os.Rename .tmp → canonical fails → wrapped ErrStagerRenameFailed
	Stage(ctx context.Context, in StageInput) (*StagedReceipt, error)

	// RecoverOrphans scans the workspace `.partial/` directory for
	// abandoned `.tmp` files whose mtime is older than maxAge and
	// unlinks them. Called at boot from composition root seam.
	// Synchronous (no goroutine). Safe for concurrent use with
	// Stage because it operates exclusively on `.partial/*.tmp`.
	//
	// Returns the count of removed orphan files. readdir/unlink
	// errors DO NOT abort the loop — the partial-success counter is
	// returned together with a wrapped ErrStagerRecoveryFailed if
	// any failures occurred (operator-visible, not panic).
	RecoverOrphans(ctx context.Context, maxAge time.Duration) (int, error)
}

// StageInput is the FASE 3-A request envelope. Callers populate
// every field explicitly (godlike/07 fail-closed posture: zero
// value is not a valid substitute for production).
type StageInput struct {
	// ArtifactID is the canonical `art_<unix_nano>_<8hex>` string
	// from the operations/repository naming pattern. The ID is
	// generated by the caller (typically the StageService that
	// wires this Stager together with the FASE 3-B
	// StagesRepository). The Stager validates the format via
	// ValidateArtifactIDFormat; malformed IDs surface as
	// ErrStagerInvalidInput BEFORE any FS touch.
	ArtifactID string

	// MIME is the IANA media type (e.g. "audio/mpeg", "image/png",
	// "video/mp4"). Validated against the canonical `type/subtype`
	// shape via ValidateMIMEFormat. Malformed MIME surfaces as
	// ErrStagerInvalidInput before any FS touch.
	MIME string

	// SizeBytes is the optional pre-declared byte count. 0 means
	// "unknown, read the Content to learn". When non-zero, used
	// for the per-artifact Quota check (skipped when SizeBytes==0
	// because the actual size is unknown at pre-flight time).
	SizeBytes int64

	// ExpectedSHA256 is the optional pre-computed hash. Non-empty
	// triggers a post-write mismatch check. Empty = skip the check
	// (the Stager still computes the hash during write — the
	// comparison is the optional integrity layer).
	ExpectedSHA256 string

	// Content is the inbound byte source. The Stager copies bytes
	// through an io.MultiWriter to a sha256.Hash + the .tmp file
	// concurrently so SHA-256 is computed DURING write (per
	// audit FASE 3 (a) "SHA calcolato durante la write"). The
	// Stager does NOT load the entire stream into memory —
	// io.MultiWriter + io.Copy handles arbitrarily-large sources
	// at constant memory cost.
	Content io.Reader
}

// StagedReceipt is the FASE 3-A response envelope. The caller (a
// future StageService that wraps the Stager together with
// StagesRepository) translates the receipt into the
// artifact_stages INSERT projection in FASE 3-B.
//
// godlike/06 SSOT: this struct is local to the staging package
// (FS-only fields). FASE 3-B will introduce a separate envelope
// for the artifact_stages row — the boundary is intentional to
// keep the disk discipline free of SQLite-shape concerns.
type StagedReceipt struct {
	// LocalPath is the canonical absolute path to the staged file
	// (typically `<workspace>/<artifactID>`).
	LocalPath string

	// Hash is the canonical 64-char lowercase hex SHA-256 of the
	// staged file's bytes, computed DURING write via
	// io.MultiWriter(sha256.New, file).
	Hash string

	// Size is the post-write size in bytes. Always > 0 for
	// successful stages (0-byte writes are rejected by the
	// Stager before rename → wrapped ErrArtifactStageEmpty).
	Size int64

	// MIME is the validated MIME — preserved verbatim on the
	// receipt so the FASE 3-B INSERT does not need to re-validate
	// (FormatValidate is FS-only setup-time expensive).
	MIME string

	// WorkspacePath is the canonical workspace directory used for
	// this receipt. Diagnostic-only: not consumed by the FASE 3-B
	// INSERT. Future PRs may derive JobID from this layout
	// (workspace/jobID/artifactID convention matches the existing
	// staging convention in internal/application/scripts/adapters/
	// artifacts_persistence.go).
	WorkspacePath string
}
