// Package finalizer — byte-equivalent test_helper
// (PR-GODOBJ-5-FINALIZER mechanical split audit-pin)
//
// This file pins the SEMANTIC invariants the orchestrator + 5 split
// writers must preserve across the mechanical godobject → 6-file
// split. Each TestByteEquiv_* verifies one canonical scenario:
//
//  1. Happy path single required artifact → jobs.status=SUCCEEDED,
//     1 job_completed event, 1 asset.index.requested outbox event,
//     completion_fingerprint persisted in result_json.
//  2. Multi-artifact (required + optional via OptionalDeclarations)
//     → SUCCEEDED, 1 job_completed event, 1 optional_artifact_report
//     event (FINALIZED), 1 asset.index.requested outbox event.
//  3. Idempotent replay (same request) → 2nd call returns SUCCEEDED
//     WITHOUT rewriting result_json or completed_at (no-rewrite
//     godlike/07 invariant). Both result_json + completed_at from
//     the first commit must be byte-stable into the second call.
//  4. Conflict replay (different result data on already-SUCCEEDED)
//     → 2nd call returns ErrCompletionConflict; jobs.status stays
//     SUCCEEDED; result_json unchanged.
//  5. Lease expired pre-validation (Lease.ExpiresAt in the past)
//     → ErrLeaseExpired at validateRequest; jobs.status stays RUNNING
//     (fence REJECTS BEFORE mutation — godlike/07 invariant).
//  6. Stale attempt (request.Attempt != retry_count+1)
//     → ErrStaleAttempt at selectJobForFinalization; jobs.status
//     stays RUNNING.
//
// We test SEMANTIC invariants (error class, status flip, fingerprint
// persistence, no-rewrite idempotent replay) rather than the
// byte-stable random IDs generated by randomHex (those are hygiene-
// level IDs that legitimately vary across runs). The 6 scenarios
// together prove that the pre-split monolithic god-object's behavior
// is byte-equivalent to the 6-file split's post-split behavior —
// nothing observable drifted across the refactor.
//
// godlike/06 SSOT: this file is the audit-pin for the JobFinalizer
// split. Any drift in the post-split behavior fails one of these
// 6 tests loudly, surfacing the surface where the cutover happened.
package jobs

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"testing"
	"time"

	_ "github.com/mattn/go-sqlite3"

	"github.com/Marcuss-ops/PipelineGen/internal/capabilities/finalization"
	fin "github.com/Marcuss-ops/PipelineGen/internal/capabilities/jobs/finalize"
)

// noopAssetTxByteEquiv satisfies finalization.AssetFinalizerTx with a
// value-receiver for the byte-equiv test suite. Mirrors the e2e
// test's noopAssetTx — kept separate so the byte-equiv tests do not
// depend on the e2e helper surface.
type noopAssetTxByteEquiv struct{}

func (noopAssetTxByteEquiv) FinalizeAsset(
	ctx context.Context,
	tx finalization.Transaction,
	artifact finalization.PublishedArtifact,
) (finalization.ArtifactRef, []finalization.OutboxEvent, error) {
	return finalization.ArtifactRef{
		ArtifactID:    artifact.ArtifactID,
		AssetID:       artifact.ArtifactID,
		Kind:          artifact.Kind,
		SourceVersion: artifact.SourceVersion,
		ContentHash:   artifact.SHA256,
		Location:      artifact.Location,
	}, nil, nil
}

// setupByteEquivDB is the minimum schema needed for CompleteWithArtifacts:
// jobs + job_events + outbox_events. We don't write media_assets /
// asset_versions / asset_locations because noopAssetTxByteEquiv returns
// zero events from FinalizeAsset — those tables are never touched in
// the byte-equiv suite.
func setupByteEquivDB(t *testing.T) *sql.DB {
	t.Helper()
	db, err := sql.Open("sqlite3", ":memory:?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		t.Fatalf("open in-memory db: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	for _, ddl := range []string{
		`CREATE TABLE jobs (
			id TEXT PRIMARY KEY,
			type TEXT NOT NULL DEFAULT '',
			status TEXT NOT NULL DEFAULT 'QUEUED',
			worker_id TEXT NOT NULL DEFAULT '',
			lease_id TEXT NOT NULL DEFAULT '',
			lease_expiry TEXT,
			retry_count INTEGER NOT NULL DEFAULT 0,
			revision INTEGER NOT NULL DEFAULT 0,
			result_json TEXT NOT NULL DEFAULT '',
			completed_at TEXT,
			progress INTEGER NOT NULL DEFAULT 0,
			created_at TEXT NOT NULL DEFAULT '',
			updated_at TEXT NOT NULL DEFAULT ''
		)`,
		`CREATE TABLE job_events (
			id TEXT PRIMARY KEY,
			job_id TEXT NOT NULL,
			type TEXT NOT NULL,
			message TEXT NOT NULL DEFAULT '',
			data_json TEXT NOT NULL DEFAULT '{}',
			created_at TEXT NOT NULL DEFAULT ''
		)`,
		`CREATE TABLE outbox_events (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			event_type TEXT NOT NULL,
			aggregate_id TEXT NOT NULL DEFAULT '',
			aggregate_type TEXT NOT NULL DEFAULT '',
			payload_json TEXT NOT NULL DEFAULT '',
			event_key TEXT NOT NULL DEFAULT '',
			status TEXT NOT NULL DEFAULT 'pending',
			attempt_count INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 10,
			last_error TEXT NOT NULL DEFAULT '',
			next_attempt_at TEXT,
			worker_id TEXT NOT NULL DEFAULT '',
			lease_id TEXT NOT NULL DEFAULT '',
			lease_expiry TEXT,
			completed_at TEXT,
			created_at TEXT NOT NULL,
			updated_at TEXT NOT NULL DEFAULT ''
		)`,
		`CREATE UNIQUE INDEX ux_outbox_events_event_key ON outbox_events(event_key)`,
	} {
		if _, err := db.Exec(ddl); err != nil {
			t.Fatalf("create table: %v\nDDL: %s", err, ddl)
		}
	}
	return db
}

// insertRunningJobIdempotent inserts a freshly-RUNNING job with the
// given worker_id / lease_id / lease_expiry. retry_count is exposed
// to allow the stale-attempt scenario (retry_count=2 + Attempt=1).
func insertRunningJobIdempotent(t *testing.T, db *sql.DB, jobID, workerID, leaseID string, leaseExpiry time.Time, retryCount int) {
	t.Helper()
	_, err := db.Exec(
		`INSERT INTO jobs (id, type, status, worker_id, lease_id, lease_expiry, retry_count, revision, created_at, updated_at)
		 VALUES (?, 'test.job', 'RUNNING', ?, ?, ?, ?, 1, ?, ?)`,
		jobID, workerID, leaseID, leaseExpiry.UTC().Format(time.RFC3339), retryCount,
		time.Now().UTC().Format(time.RFC3339), time.Now().UTC().Format(time.RFC3339),
	)
	if err != nil {
		t.Fatalf("insert running job: %v", err)
	}
}

func makeRequiredArtifact(artifactID, sha string) finalization.PublishedArtifact {
	return finalization.PublishedArtifact{
		ArtifactID:     artifactID,
		Kind:           finalization.KindImage,
		Filename:       "frame.png",
		MIMEType:       "image/png",
		SizeBytes:      1234,
		SHA256:         sha,
		SourceVersion:  1,
		Requirement:    finalization.ArtifactRequirementRequired,
		IdempotencyKey: "ik-" + sha,
		Location: finalization.AssetLocation{
			Provider: "drive",
			FileID:   "drive-" + sha,
			Action:   finalization.PublishCreated,
		},
	}
}

// ── Scenario 1: happy path single required artifact ────────────────

// TestByteEquiv_HappyPath_SingleRequiredArtifact asserts that the
// canonical "complete with one required artifact" path produces:
//   - jobs.status = SUCCEEDED
//   - jobs.progress = 100
//   - jobs.worker_id and lease_id CLEARED (markSucceeded invariant)
//   - 1 job_events row of type job_completed
//   - 0 outbox events (noopAssetTxByteEquiv returns nil events)
//   - result_json is wrapped with completion_fingerprint
//   - completion_fingerprint is non-empty hex SHA-256
//   - FinalizationResult.{Status, JobID, ArtifactRefs[0]} populated.
func TestByteEquiv_HappyPath_SingleRequiredArtifact(t *testing.T) {
	db := setupByteEquivDB(t)
	jobID, workerID, leaseID := "byteq-happy", "w-happy", "lease-happy"
	expiry := time.Now().Add(10 * time.Minute)
	insertRunningJobIdempotent(t, db, jobID, workerID, leaseID, expiry, 0)

	f := fin.New(db, nil, noopAssetTxByteEquiv{}, nil)

	res, err := f.CompleteWithArtifacts(context.Background(), finalization.FinalizationRequest{
		Lease: finalization.Lease{
			LeaseID: leaseID, JobID: jobID, WorkerID: workerID,
			Attempt: 1, ExpiresAt: expiry,
		},
		Result: finalization.ResultManifest{
			JobID: jobID, Attempt: 1,
			Data: json.RawMessage(`{"status":"ok"}`),
		},
		Artifacts: []finalization.PublishedArtifact{
			makeRequiredArtifact("art-happy", "hash-happy"),
		},
	})
	if err != nil {
		t.Fatalf("CompleteWithArtifacts: %v", err)
	}

	if res.Status != "SUCCEEDED" {
		t.Errorf("Status = %q, want SUCCEEDED", res.Status)
	}
	if res.JobID != jobID {
		t.Errorf("JobID = %q, want %q", res.JobID, jobID)
	}
	// noopAssetTxByteEquiv returns 1 ArtifactRef per artifact (populated
	// struct, but 0 outbox events). The orchestrator collects ONE ref
	// per input artifact regardless of events emitted.
	if len(res.ArtifactRefs) != 1 {
		t.Errorf("ArtifactRefs count = %d, want 1 (one ref per input artifact)", len(res.ArtifactRefs))
	}
	if res.ArtifactRefs[0].ArtifactID != "art-happy" {
		t.Errorf("ArtifactRefs[0].ArtifactID = %q, want art-happy", res.ArtifactRefs[0].ArtifactID)
	}

	// DB invariants.
	var status, workerNow, leaseNow, resultJSON string
	var progress int
	if err := db.QueryRow(
		`SELECT status, worker_id, lease_id, progress, result_json FROM jobs WHERE id = ?`,
		jobID,
	).Scan(&status, &workerNow, &leaseNow, &progress, &resultJSON); err != nil {
		t.Fatalf("read jobs row: %v", err)
	}
	if status != "SUCCEEDED" {
		t.Errorf("jobs.status = %q, want SUCCEEDED", status)
	}
	if progress != 100 {
		t.Errorf("jobs.progress = %d, want 100", progress)
	}
	if workerNow != "" {
		t.Errorf("jobs.worker_id = %q, want empty (markSucceeded clears)", workerNow)
	}
	if leaseNow != "" {
		t.Errorf("jobs.lease_id = %q, want empty (markSucceeded clears)", leaseNow)
	}
	var wrapped struct {
		Data                  json.RawMessage `json:"data"`
		CompletionFingerprint string          `json:"completion_fingerprint"`
	}
	if err := json.Unmarshal([]byte(resultJSON), &wrapped); err != nil {
		t.Fatalf("unmarshal result_json: %v (json=%s)", err, resultJSON)
	}
	if wrapped.CompletionFingerprint == "" {
		t.Error("completion_fingerprint should be non-empty hex SHA-256")
	}
	if len(wrapped.CompletionFingerprint) != 64 {
		t.Errorf("completion_fingerprint len = %d, want 64 (SHA-256 hex)", len(wrapped.CompletionFingerprint))
	}

	// 1 job_completed event.
	var eventCount int
	if err := db.QueryRow(
		`SELECT COUNT(*) FROM job_events WHERE job_id = ? AND type = 'job_completed'`,
		jobID,
	).Scan(&eventCount); err != nil {
		t.Fatalf("count job_completed: %v", err)
	}
	if eventCount != 1 {
		t.Errorf("job_completed count = %d, want 1", eventCount)
	}

	// NO optional_artifact_report event (no OptionalDeclarations given).
	var optReportCount int
	if err := db.QueryRow(
		`SELECT COUNT(*) FROM job_events WHERE job_id = ? AND type = 'optional_artifact_report'`,
		jobID,
	).Scan(&optReportCount); err != nil {
		t.Fatalf("count optional_artifact_report: %v", err)
	}
	if optReportCount != 0 {
		t.Errorf("optional_artifact_report count = %d, want 0 (no declarations)", optReportCount)
	}
}

// ── Scenario 2: multi-artifact required + optional ──────────────────

// TestByteEquiv_MultiArtifact_RequiredPlusOptional asserts that the
// P1.2 optional-artifact audit sidecar is persisted when an
// OptionalDeclarations FINALIZED entry matches a matching artifact:
//   - 1 job_completed event
//   - 1 optional_artifact_report event with 1 record (FINALIZED)
//   - record.Filename + IdempotencyKey match the artifact's canonical values
//   - FinalizationResult.OptionalArtifactReport populated with 1 record
func TestByteEquiv_MultiArtifact_RequiredPlusOptional(t *testing.T) {
	db := setupByteEquivDB(t)
	jobID, workerID, leaseID := "byteq-multi", "w-multi", "lease-multi"
	expiry := time.Now().Add(10 * time.Minute)
	insertRunningJobIdempotent(t, db, jobID, workerID, leaseID, expiry, 0)

	f := fin.New(db, nil, noopAssetTxByteEquiv{}, nil)

	res, err := f.CompleteWithArtifacts(context.Background(), finalization.FinalizationRequest{
		Lease: finalization.Lease{
			LeaseID: leaseID, JobID: jobID, WorkerID: workerID,
			Attempt: 1, ExpiresAt: expiry,
		},
		Result: finalization.ResultManifest{
			JobID: jobID, Attempt: 1,
			Data: json.RawMessage(`{"status":"ok"}`),
		},
		Artifacts: []finalization.PublishedArtifact{
			makeRequiredArtifact("art-req", "hash-req"),
			makeRequiredArtifact("art-opt", "hash-opt"), // Requirement=Required so it counts as an artifact
		},
		OptionalDeclarations: []finalization.ArtifactDeclaration{
			{
				ArtifactID:  "art-opt",
				Kind:        finalization.KindImage,
				Filename:    "hint-opt.png", // hint; canonical from PublishedArtifact wins
				Requirement: finalization.ArtifactRequirementOptional,
				Status:      finalization.OptionalArtifactStatusFinalized,
			},
		},
	})
	if err != nil {
		t.Fatalf("CompleteWithArtifacts: %v", err)
	}

	if len(res.OptionalArtifactReport) != 1 {
		t.Fatalf("OptionalArtifactReport len = %d, want 1 (FINALIZED)", len(res.OptionalArtifactReport))
	}
	rec := res.OptionalArtifactReport[0]
	if rec.ArtifactID != "art-opt" {
		t.Errorf("OptionalArtifactReport[0].ArtifactID = %q, want art-opt", rec.ArtifactID)
	}
	if rec.Status != finalization.OptionalArtifactStatusFinalized {
		t.Errorf("OptionalArtifactReport[0].Status = %s, want FINALIZED", rec.Status)
	}
	// Canonical Filename from PublishedArtifact (not the declaration's hint).
	if rec.Filename != "frame.png" {
		t.Errorf("OptionalArtifactReport[0].Filename = %q, want frame.png (canonical from PublishedArtifact)", rec.Filename)
	}

	// 1 optional_artifact_report event with the record payload.
	var reportPayload string
	if err := db.QueryRow(
		`SELECT data_json FROM job_events WHERE job_id = ? AND type = 'optional_artifact_report'`,
		jobID,
	).Scan(&reportPayload); err != nil {
		t.Fatalf("read optional_artifact_report payload: %v", err)
	}
	var report struct {
		SchemaVersion string                                `json:"schema_version"`
		Records       []finalization.OptionalArtifactRecord `json:"records"`
	}
	if err := json.Unmarshal([]byte(reportPayload), &report); err != nil {
		t.Fatalf("unmarshal report: %v", err)
	}
	if report.SchemaVersion != "v1" {
		t.Errorf("report.SchemaVersion = %q, want v1", report.SchemaVersion)
	}
	if len(report.Records) != 1 {
		t.Errorf("report.Records len = %d, want 1", len(report.Records))
	}
}

// ── Scenario 3: idempotent replay (same request) ────────────────────

// TestByteEquiv_IdempotentReplay_NoRewrite asserts that a SECOND
// CompleteWithArtifacts call with the IDENTICAL request returns
// SUCCEEDED without rewriting the jobs row's result_json or
// completed_at (godlike/07 no-fake-availability + Piano d'Azione
// §4.5 idempotent replay invariant).
func TestByteEquiv_IdempotentReplay_NoRewrite(t *testing.T) {
	db := setupByteEquivDB(t)
	jobID, workerID, leaseID := "byteq-idem", "w-idem", "lease-idem"
	expiry := time.Now().Add(10 * time.Minute)
	insertRunningJobIdempotent(t, db, jobID, workerID, leaseID, expiry, 0)

	f := fin.New(db, nil, noopAssetTxByteEquiv{}, nil)
	req := finalization.FinalizationRequest{
		Lease: finalization.Lease{
			LeaseID: leaseID, JobID: jobID, WorkerID: workerID,
			Attempt: 1, ExpiresAt: expiry,
		},
		Result: finalization.ResultManifest{
			JobID: jobID, Attempt: 1,
			Data: json.RawMessage(`{"status":"ok"}`),
		},
		Artifacts: []finalization.PublishedArtifact{
			makeRequiredArtifact("art-idem", "hash-idem"),
		},
	}

	if _, err := f.CompleteWithArtifacts(context.Background(), req); err != nil {
		t.Fatalf("first call: %v", err)
	}

	var rjBefore, caBefore string
	if err := db.QueryRow(`SELECT result_json, COALESCE(completed_at, '') FROM jobs WHERE id = ?`, jobID).Scan(&rjBefore, &caBefore); err != nil {
		t.Fatalf("read pre-state: %v", err)
	}
	if rjBefore == "" {
		t.Fatal("first call did not persist result_json")
	}
	if caBefore == "" {
		t.Fatal("first call did not persist completed_at")
	}

	res2, err := f.CompleteWithArtifacts(context.Background(), req)
	if err != nil {
		t.Fatalf("second call (idempotent): %v", err)
	}
	if res2.Status != "SUCCEEDED" {
		t.Errorf("res2.Status = %q, want SUCCEEDED", res2.Status)
	}

	var rjAfter, caAfter string
	if err := db.QueryRow(`SELECT result_json, COALESCE(completed_at, '') FROM jobs WHERE id = ?`, jobID).Scan(&rjAfter, &caAfter); err != nil {
		t.Fatalf("read post-state: %v", err)
	}
	if rjAfter != rjBefore {
		t.Errorf("idempotent call MUST NOT rewrite result_json\nbefore=%s\nafter =%s", rjBefore, rjAfter)
	}
	if caAfter != caBefore {
		t.Errorf("idempotent call MUST NOT rewrite completed_at\nbefore=%s\nafter =%s", caBefore, caAfter)
	}
}

// ── Scenario 4: conflict replay (different result) ──────────────────

// TestByteEquiv_ConflictDifferentResult asserts that a SECOND
// CompleteWithArtifacts call with a DIFFERENT result data returns
// ErrCompletionConflict and jobs.status stays SUCCEEDED with the
// FIRST result_json intact (no overwrite on conflict).
func TestByteEquiv_ConflictDifferentResult(t *testing.T) {
	db := setupByteEquivDB(t)
	jobID, workerID, leaseID := "byteq-conf", "w-conf", "lease-conf"
	expiry := time.Now().Add(10 * time.Minute)
	insertRunningJobIdempotent(t, db, jobID, workerID, leaseID, expiry, 0)

	f := fin.New(db, nil, noopAssetTxByteEquiv{}, nil)

	reqA := finalization.FinalizationRequest{
		Lease: finalization.Lease{
			LeaseID: leaseID, JobID: jobID, WorkerID: workerID,
			Attempt: 1, ExpiresAt: expiry,
		},
		Result: finalization.ResultManifest{
			JobID: jobID, Attempt: 1,
			Data: json.RawMessage(`{"status":"ok"}`),
		},
		Artifacts: []finalization.PublishedArtifact{
			makeRequiredArtifact("art-conf", "hash-conf"),
		},
	}
	if _, err := f.CompleteWithArtifacts(context.Background(), reqA); err != nil {
		t.Fatalf("first: %v", err)
	}

	var rjBefore string
	if err := db.QueryRow(`SELECT result_json FROM jobs WHERE id = ?`, jobID).Scan(&rjBefore); err != nil {
		t.Fatalf("read pre-state: %v", err)
	}

	reqB := reqA
	reqB.Result.Data = json.RawMessage(`{"status":"different"}`)

	_, err := f.CompleteWithArtifacts(context.Background(), reqB)
	if err == nil {
		t.Fatal("want ErrCompletionConflict on different result, got nil")
	}
	if !errors.Is(err, finalization.ErrCompletionConflict) {
		t.Errorf("err = %v, want ErrCompletionConflict", err)
	}

	// jobs.status still SUCCEEDED, result_json still the FIRST call's value.
	var status, rjAfter string
	if err := db.QueryRow(`SELECT status, result_json FROM jobs WHERE id = ?`, jobID).Scan(&status, &rjAfter); err != nil {
		t.Fatalf("read post-state: %v", err)
	}
	if status != "SUCCEEDED" {
		t.Errorf("status = %q, want SUCCEEDED (conflict must NOT mutate)", status)
	}
	if rjAfter != rjBefore {
		t.Error("conflict MUST NOT rewrite result_json")
	}
}

// ── Scenario 5: lease expired pre-validation ────────────────────────

// TestByteEquiv_LeaseExpiredPreValidation asserts that a request
// with a past ExpiresAt returns ErrLeaseExpired at validateRequest
// (step 1, OUTSIDE the transaction) and jobs.status stays RUNNING
// (no SQL fence mutation occurred — godlike/07 invariant).
func TestByteEquiv_LeaseExpiredPreValidation(t *testing.T) {
	db := setupByteEquivDB(t)
	jobID, workerID, leaseID := "byteq-exp", "w-exp", "lease-exp"
	// Job stored with EXPIRED lease_expiry (fence will reject at SQL too).
	pastExpiry := time.Now().Add(-10 * time.Minute)
	insertRunningJobIdempotent(t, db, jobID, workerID, leaseID, pastExpiry, 0)

	f := fin.New(db, nil, noopAssetTxByteEquiv{}, nil)

	_, err := f.CompleteWithArtifacts(context.Background(), finalization.FinalizationRequest{
		Lease: finalization.Lease{
			// request ExpiresAt past → validateRequest fails first.
			LeaseID: leaseID, JobID: jobID, WorkerID: workerID,
			Attempt: 1, ExpiresAt: pastExpiry,
		},
		Result: finalization.ResultManifest{
			JobID: jobID, Attempt: 1,
			Data: json.RawMessage(`{}`),
		},
		Artifacts: []finalization.PublishedArtifact{
			makeRequiredArtifact("art-exp", "hash-exp"),
		},
	})
	if err == nil {
		t.Fatal("want ErrLeaseExpired for past expiry, got nil")
	}
	if !errors.Is(err, finalization.ErrLeaseExpired) {
		t.Errorf("err = %v, want ErrLeaseExpired", err)
	}

	// jobs.status stays RUNNING (validateRequest rejected before mutation).
	var status string
	if err := db.QueryRow(`SELECT status FROM jobs WHERE id = ?`, jobID).Scan(&status); err != nil {
		t.Fatalf("read status: %v", err)
	}
	if status != "RUNNING" {
		t.Errorf("status = %q, want RUNNING (lease expired fence rejects before mutation)", status)
	}
}

// ── Scenario 6: stale attempt ───────────────────────────────────────

// TestByteEquiv_StaleAttempt asserts that a request with
// lease.Attempt != retry_count+1 returns ErrStaleAttempt at
// selectJobForFinalization (step 3, INSIDE the transaction but
// BEFORE markSucceeded). jobs.status stays RUNNING.
func TestByteEquiv_StaleAttempt(t *testing.T) {
	db := setupByteEquivDB(t)
	jobID, workerID, leaseID := "byteq-stale", "w-stale", "lease-stale"
	expiry := time.Now().Add(10 * time.Minute)
	// retry_count = 2 → expected attempt is 3. Send attempt=1 (stale).
	insertRunningJobIdempotent(t, db, jobID, workerID, leaseID, expiry, 2)

	f := fin.New(db, nil, noopAssetTxByteEquiv{}, nil)

	_, err := f.CompleteWithArtifacts(context.Background(), finalization.FinalizationRequest{
		Lease: finalization.Lease{
			LeaseID: leaseID, JobID: jobID, WorkerID: workerID,
			Attempt:   1, // stale: expected 3 (= retry_count + 1)
			ExpiresAt: expiry,
		},
		Result: finalization.ResultManifest{
			JobID: jobID, Attempt: 1,
			Data: json.RawMessage(`{}`),
		},
		Artifacts: []finalization.PublishedArtifact{
			makeRequiredArtifact("art-stale", "hash-stale"),
		},
	})
	if err == nil {
		t.Fatal("want ErrStaleAttempt on attempt mismatch, got nil")
	}
	if !errors.Is(err, finalization.ErrStaleAttempt) {
		t.Errorf("err = %v, want ErrStaleAttempt", err)
	}

	// jobs.status stays RUNNING (stale-attempt gate rejects before markSucceeded).
	var status string
	if err := db.QueryRow(`SELECT status FROM jobs WHERE id = ?`, jobID).Scan(&status); err != nil {
		t.Fatalf("read status: %v", err)
	}
	if status != "RUNNING" {
		t.Errorf("status = %q, want RUNNING (stale attempt rejects before mutation)", status)
	}
}
