package config

import "strings"

// DriveConfig holds Google Drive configuration.
// MediaRootFolder is the single root for ALL media on Drive.
type DriveConfig struct {
	// MediaRootFolder is the single Drive root folder for all PipelineGen media.
	// Example: "1ABCdef..." points to "PipelineGen Media" at Drive root.
	MediaRootFolder string `yaml:"media_root_folder" env:"VELOX_DRIVE_MEDIA_ROOT" default:""`

	// Stock footage root folder
	StockRootFolder string `yaml:"stock_root_folder" env:"VELOX_DRIVE_STOCK_ROOT" default:""`

	// AIClipsRootFolder is the canonical Drive folder for generated stock
	// clips. It is intentionally separate from StockRootFolder so AI stock
	// can use the common stock pipeline without mixing storage roots.
	AIClipsRootFolder string `yaml:"ai_clips_root_folder" env:"VELOX_DRIVE_AI_CLIPS_ROOT" default:""`

	// NormalClipsSourceFolder is the Drive source folder scanned by the
	// recursive normal-clip indexing job. It is distinct from publish roots.
	NormalClipsSourceFolder string `yaml:"normal_clips_source_folder" env:"VELOX_DRIVE_NORMAL_CLIPS_SOURCE" default:""`

	// Clips (YouTube/Artlist) root folder
	ClipsRootFolder string `yaml:"clips_root_folder" env:"VELOX_DRIVE_CLIPS_ROOT" default:""`
	// YouTubeSubtitlesRootFolder is the dedicated root for subtitle sidecars.
	// Each source video gets a child folder below this root.
	YouTubeSubtitlesRootFolder string `yaml:"youtube_subtitles_root_folder" env:"VELOX_DRIVE_YOUTUBE_SUBTITLES_ROOT" default:""`
	// Voiceover root folder
	VoiceoverRootFolder string `yaml:"voiceover_root_folder" env:"VELOX_DRIVE_VOICEOVER_ROOT" default:""`
	// Artlist assets root folder
	ArtlistRootFolder string `yaml:"artlist_root_folder" env:"VELOX_DRIVE_ARTLIST_ROOT" default:""`
	// Books (summarized/rewritten) root folder
	BooksRootFolder string `yaml:"books_root_folder" env:"VELOX_DRIVE_BOOKS_ROOT" default:""`
	// Scripts/docs generation root folder
	ScriptsRootFolder string `yaml:"scripts_root_folder" env:"VELOX_DRIVE_SCRIPTS_ROOT" default:""`
	// ScriptsGenerateFolder is the subfolder for docs generated by the sync script-docs flow.
	ScriptsGenerateFolder string `yaml:"scripts_generate_folder" env:"VELOX_DRIVE_SCRIPTS_GENERATE" default:""`
	// Images root folder
	ImagesRootFolder string `yaml:"images_root_folder" env:"VELOX_DRIVE_IMAGES_ROOT" default:""`
	// Copertine/thumbnails root folder
	CopertineRootFolder string `yaml:"copertine_root_folder" env:"VELOX_DRIVE_COPERTINE_ROOT" default:""`
	// Sound effects root folder
	SoundEffectsRootFolder string `yaml:"sound_effects_root_folder" env:"VELOX_DRIVE_SOUND_EFFECTS_ROOT" default:""`
	// Outro root folder
	OutroRootFolder string `yaml:"outro_root_folder" env:"VELOX_DRIVE_OUTRO_ROOT" default:""`
	// Avatar AI generated content root folder
	AvatarAIRootFolder string `yaml:"avatar_ai_root_folder" env:"VELOX_DRIVE_AVATAR_AI_ROOT" default:""`
	// SharedWithEmail is the Google account email to automatically share generated docs with.
	SharedWithEmail string `yaml:"shared_with_email" env:"VELOX_DRIVE_SHARED_WITH_EMAIL" default:""`

	// StrictStartupValidation, when true (default), makes the
	// delivery.StartupDriveRootsValidator abort the process at boot
	// if ANY configured RootFolderID is unreachable on Drive.
	//
	// When false, the validator still runs but the composition root
	// logs the per-destination failures and continues boot; the
	// affected destinations then fail-fast at first Publish call
	// (the legacy "discover at first upload" behaviour). Operators
	// SHOULD leave this at true — soft-mode is a transitional escape
	// hatch for staging / DR runs where one root is intentionally
	// absent. (P1.3, July 2026.)
	StrictStartupValidation bool `yaml:"strict_startup_validation" env:"VELOX_DRIVE_STRICT_STARTUP_VALIDATION" default:"true"`
}

// RootFolder returns the MediaRootFolder.
func (d DriveConfig) RootFolder() string {
	return d.MediaRootFolder
}

// ResolveFolder returns the effective folder ID for a given specific root.
// Priority: specific root folder > MediaRootFolder (unified root) > "".
func (d DriveConfig) ResolveFolder(specificRoot string) string {
	if specific := strings.TrimSpace(specificRoot); specific != "" {
		return specific
	}
	return strings.TrimSpace(d.MediaRootFolder)
}

func (d DriveConfig) resolveSubfolder(parentFolder, specificFolder string) string {
	if specific := strings.TrimSpace(specificFolder); specific != "" {
		return specific
	}
	return d.ResolveFolder(parentFolder)
}

// IsUsingMediaRoot reports whether a destination whose nominal root is
// specificRoot is effectively using the global MediaRootFolder (i.e. the
// destination has no dedicated root folder configured and falls back to
// the unified root). Callers use this to decide whether to prepend the
// destination's namespace (e.g. "clips", "stock") so the unified root
// stays organized with canonical subdirectories.
//
// Example: cfg.Drive.IsUsingMediaRoot(cfg.Drive.ClipsRootFolder) returns
// true when MediaRootFolder is "ABC" and ClipsRootFolder is "". The
// publisher should then build the path as "clips/{group}/{video_id}"
// under the unified root, rather than "{group}/{video_id}" directly.
func (d DriveConfig) IsUsingMediaRoot(specificRoot string) bool {
	return strings.TrimSpace(d.MediaRootFolder) != "" && strings.TrimSpace(specificRoot) == ""
}

// Convenience resolvers — each returns MediaRootFolder if set, else its own root.
func (d DriveConfig) StockFolder() string   { return d.ResolveFolder(d.StockRootFolder) }
func (d DriveConfig) AIClipsFolder() string { return d.ResolveFolder(d.AIClipsRootFolder) }
func (d DriveConfig) ClipsFolder() string   { return d.ResolveFolder(d.ClipsRootFolder) }
func (d DriveConfig) YouTubeSubtitlesFolder() string {
	return d.ResolveFolder(d.YouTubeSubtitlesRootFolder)
}
func (d DriveConfig) VoiceoverFolder() string { return d.ResolveFolder(d.VoiceoverRootFolder) }
func (d DriveConfig) ArtlistFolder() string   { return d.ResolveFolder(d.ArtlistRootFolder) }
func (d DriveConfig) BooksFolder() string     { return d.ResolveFolder(d.BooksRootFolder) }
func (d DriveConfig) ScriptsFolder() string   { return d.ResolveFolder(d.ScriptsRootFolder) }
func (d DriveConfig) ScriptsGenFolder() string {
	return d.resolveSubfolder(d.ScriptsRootFolder, d.ScriptsGenerateFolder)
}
func (d DriveConfig) ImagesFolder() string { return d.ResolveFolder(d.ImagesRootFolder) }

func (d DriveConfig) CopertineFolder() string    { return d.ResolveFolder(d.CopertineRootFolder) }
func (d DriveConfig) SoundEffectsFolder() string { return d.ResolveFolder(d.SoundEffectsRootFolder) }
func (d DriveConfig) DocumentsFolder() string    { return d.ResolveFolder(d.ScriptsRootFolder) } // Documents share the scripts root
func (d DriveConfig) OutroFolder() string        { return d.ResolveFolder(d.OutroRootFolder) }
