package soundeffects

func soundEffectsImpactCatalog() []additionalSoundEffect {
	return []additionalSoundEffect{
		{"sfx_cinematic_boom_heavy_impact_03.wav", "sfx_explosion_heavy_blast_01.wav", "explosion", "Heavy cinematic explosion blast with deep sub-bass rumble", []string{"explosion", "blast", "heavy", "detonation", "cinematic", "boom"}},
		{"sfx_cartoon_splat_squish.wav", "sfx_cartoon_splat_squish_05.wav", "impact", "Classic comedic cartoon splat sound effect with a wet squishy texture", []string{"cartoon", "splat", "squish", "comedy", "impact", "wet"}},
		{"03 Evolve_Boom Brass D.wav", "sfx_cinematic_boom_brass_d_01.wav", "boom", "Cinematic brass boom impact with evolving resonance", []string{"boom", "brass", "impact", "cinematic", "resonance"}},
		{"05 Evolve_Boom Shot.wav", "sfx_cinematic_boom_shot_01.wav", "boom", "Short cinematic boom shot impact", []string{"boom", "shot", "impact", "cinematic", "hit"}},
		{"14 Incoming Crash.wav", "sfx_impact_incoming_crash_01.wav", "impact", "Violent and sudden physical crash impact", []string{"crash", "impact", "incoming", "hit", "collision"}},
		{"04 Grand Hit B.wav.wav", "sfx_cinematic_grand_hit_01.wav", "impact", "Large cinematic hit for dramatic reveals, titles and powerful scene accents", []string{"grand", "hit", "impact", "cinematic", "dramatic", "reveal"}},
		{"06 Drum Roll.wav", "sfx_percussion_drum_roll_01.wav", "percussion", "Suspenseful drum roll leading into an announcement, reveal or punchline", []string{"drum", "roll", "percussion", "suspense", "announcement", "reveal"}},
		{"boom sound effect.mp3", "sfx_impact_boom_heavy_01.mp3", "impact", "Short heavy boom for strong emphasis, shocks and dramatic punch moments", []string{"boom", "impact", "heavy", "bass", "shock", "dramatic"}},
		{"sfx_explosion_heavy_blast_01.wav", "sfx_cinematic_grand_hit_01.wav", "impact", "Large cinematic hit for dramatic reveals, titles and powerful scene accents", []string{"grand", "hit", "impact", "cinematic", "dramatic", "reveal"}},
		{"sfx_sub_bass_riser_deep_rumble_02.wav", "sfx_percussion_drum_roll_01.wav", "percussion", "Suspenseful drum roll leading into an announcement, reveal or punchline", []string{"drum", "roll", "percussion", "suspense", "announcement", "reveal"}},
		{"sfx_cinematic_boom_brass_d_01.wav", "sfx_cinematic_brass_boom_01.wav", "impact", "Massive cinematic brass boom with a long low tail for dramatic reveals and powerful emphasis", []string{"brass", "boom", "impact", "cinematic", "dramatic", "reveal"}},
		{"sfx_cinematic_boom_shot_01.wav", "sfx_cinematic_boom_shot_01.wav", "impact", "Heavy cinematic boom shot with a resonant bass tail for shocks, titles and dramatic punch moments", []string{"boom", "shot", "impact", "bass", "cinematic", "shock"}},
		{"sfx_subsonic_low_rumble_01.wav", "sfx_impact_subsonic_rumble_01.wav", "impact", "Extremely deep sub-bass rumble for ominous tension, dramatic emphasis and cinematic low-end pressure", []string{"subsonic", "sub-bass", "rumble", "ominous", "cinematic", "tension"}},
		{"sfx_subsonic_low_rumble_02.wav", "sfx_impact_subsonic_rumble_02.wav", "impact", "Deep subsonic bass pulse and low cinematic rumble for suspense, emphasis and ominous transitions", []string{"subsonic", "bass", "rumble", "low-frequency", "cinematic", "tension"}},
		{"shot light energy.mp3", "sfx_energy_light_shot_01.mp3", "impact", "Light energy shot sound effect", []string{"energy", "shot", "impact", "light", "sci-fi"}},
		{"sfx_suspense_sudden_01.mp3", "sfx_impact_suspense_orchestral_01.mp3", "impact", "Sharp dramatic orchestral string hit for sudden jump scares and suspense", []string{"suspense", "hit", "orchestral", "horror", "scare", "impact"}},
		{"01 Boom.wav", "sfx_cinematic_boom_01.wav", "impact", "Cinematic boom impact sound", []string{"boom", "impact", "cinematic", "bass"}},
		{"02 Deep.wav", "sfx_sub_deep_rumble_01.wav", "impact", "Deep low-frequency cinematic rumble", []string{"deep", "sub", "rumble", "bass", "cinematic"}},
		{"02 Evolve_Brassy Drop.2.wav", "sfx_cinematic_brassy_drop_01.wav", "impact", "Evolving brassy cinematic drop impact", []string{"brass", "drop", "impact", "cinematic", "evolve"}},
		{"03 Grand Hit A.wav", "sfx_cinematic_grand_hit_a_01.wav", "impact", "Large cinematic grand hit for dramatic emphasis", []string{"grand", "hit", "impact", "cinematic", "dramatic"}},
		{"11 Universe Boom A.wav", "sfx_cinematic_universe_boom_a_01.wav", "impact", "Deep atmospheric explosion simulating a massive cosmic boom event", []string{"boom", "explosion", "universe", "cosmic", "impact", "sub"}},
		{"mixkit-cinematic-glass-hit-suspense-677.wav", "sfx_impact_cinematic_glass_shatter_01.wav", "impact", "Cinematic glass shattering impact embedded within a deep bass suspense sub-drop", []string{"glass", "hit", "shatter", "impact", "suspense", "sub"}},
		{"mixkit-space-impact-774.wav", "sfx_impact_space_sub_bass_01.wav", "impact", "Deep space sub-bass hit with a synthetic, low-frequency resonance tail", []string{"impact", "space", "sub", "bass", "scifi", "resonance"}},
		{"sfx_impact_cinematic_glass_shatter_01.wav", "sfx_impact_cinematic_glass_shatter_01.wav", "impact", "Cinematic glass shattering impact embedded within a deep bass suspense sub-drop", []string{"glass", "hit", "shatter", "impact", "suspense", "sub"}},
		{"06 Evolve_Boom Hint of Metal.wav", "sfx_cinematic_metallic_boom_01.wav", "impact", "Deep electronic sub-bass explosion layered with a distinct sharp metallic ring", []string{"boom", "impact", "sub", "metallic", "bass", "cinematic"}},
		{"09 Struck Down.wav", "sfx_impact_watery_sub_drop_01.wav", "impact", "Heavy transition drop combining a deep sub slam with a fluid watery texture tail", []string{"drop", "impact", "sub", "bass", "transition", "water"}},
		{"13 Metal Slam.wav", "sfx_impact_warehouse_metal_slam_01.wav", "impact", "Massive warehouse-style iron sheet metal slam with a wide acoustic reverb decay", []string{"slam", "metal", "hit", "impact", "cinematic", "reverb"}},
		{"sfx_impact_cinematic_glass_shatter_01.wav", "sfx_impact_cinematic_glass_shatter_01.wav", "impact", "Cinematic glass shattering impact embedded within a deep bass suspense sub-drop", []string{"glass", "hit", "shatter", "impact", "suspense", "sub"}},
		{"10 Dark Drop.wav", "sfx_impact_dark_drop_01.wav", "impact", "Heavy sub-bass transition impact paired with organic water movement cues", []string{"drop", "dark", "sub", "impact", "bass", "transition"}},
		{"12 Universe Boom B.wav", "sfx_cinematic_universe_boom_b_01.wav", "impact", "Massive cosmic sub-bass impact explosion with heavy low-frequency acoustic rumble", []string{"boom", "explosion", "impact", "cosmic", "sub", "low-end"}},
		{"sfx_cinematic_boom_01.wav", "sfx_cinematic_explosive_boom_01.wav", "impact", "Deep explosive cinematic boom impact with low-end rumble tail", []string{"boom", "explosion", "impact", "sub", "cinematic", "low-end"}},
		{"sfx_cinematic_grand_hit_a_01.wav", "sfx_cinematic_grand_hit_a_01.wav", "impact", "Massive cinematic orchestral hit with a wide, long reverberation tail", []string{"hit", "impact", "orchestral", "grand", "cinematic", "reverb"}},
		{"sfx_impact_incoming_crash_01.wav", "sfx_impact_incoming_crash_01.wav", "impact", "Violent and sudden physical crash impact", []string{"crash", "impact", "incoming", "hit", "collision"}},
		{"mixkit-big-cinematic-impact-788.mp3", "sfx_impact_big_cinematic_sub_01.mp3", "impact", "Massive, low-end sub-bass explosion with a long, dark cinematic tail decaying into silence", []string{"impact", "cinematic", "boom", "sub", "bass", "explosion"}},
	}
}
