package soundeffects

func soundEffectsFoleyCatalog() []additionalSoundEffect {
	return []additionalSoundEffect{
		{"bottle cork.mp3", "sfx_foley_bottle_cork_pop.mp3", "foley", "Short bottle cork pop and release sound", []string{"foley", "bottle", "cork", "pop", "release"}},
		{"Clock Ticking Sound Effect(MP3_160K).mp3", "sfx_clock_ticking_time_pass_04_160k.mp3", "foley", "Mechanical clock ticking suggesting passing time", []string{"clock", "ticking", "time", "foley", "rhythmic"}},
		{"futuristic metal keyboard .wav", "sfx_foley_futuristic_metal_keyboard_01.wav", "foley", "Futuristic metallic keyboard typing and key presses", []string{"keyboard", "metal", "futuristic", "typing", "foley"}},
		{"keyboard press.mp3", "sfx_foley_keyboard_press_01.mp3", "foley", "Single keyboard key press", []string{"keyboard", "press", "key", "click", "foley"}},
		{"Paper Ripping.mp3", "sfx_foley_paper_ripping_01.mp3", "foley", "Paper ripping and tearing sound", []string{"foley", "paper", "ripping", "tear"}},
		{"Racks.wav", "sfx_foley_racks_01.wav", "foley", "Rack and mechanical movement sound", []string{"foley", "rack", "mechanical", "movement"}},
		{"sfx_foley_bottle_cork_pop.mp3", "sfx_foley_bottle_cork_pop_03.mp3", "foley", "Short and clean organic sound of a wine bottle cork popping out", []string{"foley", "bottle", "cork", "pop", "open", "organic"}},
		{"Wine Glass Shatter.mp3", "sfx_foley_wine_glass_shatter_01.mp3", "foley", "Wine glass shattering into fragments", []string{"foley", "glass", "wine", "shatter", "break"}},
		{"sfx_foley_keyboard_press_01.mp3", "sfx_office_keyboard_typing_fast.mp3", "foley", "Fast desktop keyboard typing with standard plastic key clicks", []string{"keyboard", "typing", "office", "foley", "clicks", "pc"}},
		{"sfx_clock_ticking_time_pass_04_160k.mp3", "sfx_clock_ticking_fast_loop.mp3", "foley", "Fast rhythmic mechanical clock ticking suggesting passing time", []string{"clock", "ticking", "time", "watch", "rhythm", "foley"}},
		{"sfx_foley_paper_ripping_01.mp3", "sfx_foley_paper_ripping_01.mp3", "foley", "Realistic foley sound of paper tearing", []string{"paper", "rip", "tear", "foley", "texture", "document"}},
		{"camera shot flash 2.wav", "sfx_foley_camera_flash_shot_02.wav", "foley", "Photography camera shot with mechanical flash trigger", []string{"camera", "flash", "shot", "photography", "foley", "click"}},
		{"camera shot flash 4.wav", "sfx_foley_camera_flash_shot_04.wav", "foley", "Photography camera shot with mechanical flash trigger variant", []string{"camera", "flash", "shot", "photography", "foley", "click"}},
		{"camera shutter 2.mp3", "sfx_foley_camera_shutter_02.mp3", "foley", "Dry and isolated mechanical photo camera shutter snap", []string{"camera", "shutter", "photo", "mechanical", "foley", "snap"}},
		{"bottle cork.mp3", "sfx_foley_bottle_cork_pop_01.mp3", "foley", "Bottle cork popping sound for openings, celebrations and playful reveals", []string{"bottle", "cork", "pop", "opening", "foley", "celebration"}},
		{"sfx_foley_bottle_cork_pop_03.mp3", "sfx_foley_bottle_cork_pop_01.mp3", "foley", "Bottle cork popping sound for openings, celebrations and playful reveals", []string{"bottle", "cork", "pop", "opening", "foley", "celebration"}},
		{"sfx_foley_wine_glass_shatter_01.mp3", "sfx_foley_wine_glass_shatter_01.mp3", "foley", "Realistic wine glass breaking and scattering for accidents, shocks and destructive moments", []string{"wine-glass", "glass", "shatter", "break", "foley", "destruction"}},
		{"Pop sound effect.mp3", "sfx_foley_pop_01.mp3", "foley", "Short pop sound effect", []string{"pop", "foley", "short", "impact"}},
		{"Pop.mp3", "sfx_foley_pop_02.mp3", "foley", "Short pop sound effect variant", []string{"pop", "foley", "short", "impact"}},
		{"Writing on keyboard Sound Effect.mp3", "sfx_foley_keyboard_writing_01.mp3", "foley", "Keyboard writing and typing sound effect", []string{"keyboard", "writing", "typing", "foley", "computer"}},
		{"crowd shocked.mp3", "sfx_foley_crowd_shocked_gasp_01.mp3", "foley", "Collective gasping vocal sound from an audience expressing shock or sudden surprise", []string{"crowd", "shocked", "gasp", "audience", "vocal", "foley"}},
		{"projector-spinning-1444.wav", "sfx_foley_projector_spinning_01.wav", "foley", "Continuous mechanical whirring and clicking of an old vintage film projector spinning", []string{"projector", "spinning", "mechanical", "foley", "vintage", "clicking"}},
		{"awww.mp3", "sfx_foley_crowd_disappointed_sigh_01.mp3", "foley", "Disappointed collective vocal sigh from a live studio audience layer", []string{"aww", "crowd", "audience", "sigh", "vocal", "foley"}},
		{"Clock Ticking Sound Effect.mp3", "sfx_foley_clock_ticking_01.mp3", "foley", "Clean, rhythmic mechanical ticking of an analog clock or stopwatch, ideal for suspense or time-passing scenes", []string{"clock", "ticking", "time", "mechanical", "foley", "suspense"}},
		{"crumpled paper sound fx.mp3", "sfx_foley_crumpled_paper_01.mp3", "foley", "Crisp, textured sound of a sheet of paper being aggressively crushed and crumpled", []string{"paper", "crumple", "crush", "texture", "foley", "handling"}},
		{"Applause.wav", "sfx_foley_crowd_applause_01.wav", "foley", "Dense and continuous dynamic crowd applause and standing ovation clapping layer", []string{"applause", "crowd", "clapping", "foley", "audience"}},
		{"Applause.wav", "sfx_foley_crowd_applause_01.wav", "foley", "Dense and continuous dynamic crowd applause and standing ovation clapping layer", []string{"applause", "crowd", "clapping", "foley", "audience"}},
		{"sfx_foley_keyboard_writing_01.mp3", "sfx_foley_keyboard_typing_sequence_01.mp3", "foley", "Continuous mechanical computer keyboard typing sequence", []string{"keyboard", "typing", "writing", "foley", "mechanical", "office"}},
		{"kids yeyy.mp3", "sfx_foley_kids_cheering_01.mp3", "foley", "Joyful and enthusiastic group of children cheering and celebrating", []string{"kids", "cheer", "yey", "celebration", "crowd", "foley"}},
		{"mixkit-bone-breaking-with-echo-2937.wav", "sfx_foley_bone_break_crunch_01.wav", "foley", "Gory, wet crunching sound designed to simulate a bone snapping or wood cracking, with artificial reverb", []string{"bone", "break", "crunch", "gory", "echo", "foley", "impact"}},
		{"mixkit-cartoon-toy-whistle-616.wav", "sfx_foley_cartoon_toy_whistle_01.wav", "foley", "Classic high-pitched slide toy whistle sound, widely used in cartoons for comedic falls or actions", []string{"cartoon", "whistle", "toy", "slide", "comedy", "foley", "retro"}},
	}
}
