package soundeffects

func soundEffectsWhooshCatalog() []additionalSoundEffect {
	return []additionalSoundEffect{
		{"sfx_cinematic_whoosh_passby_fast_04.wav", "sfx_cinematic_whoosh_passby_02.wav", "whoosh", "Fast cinematic air whoosh simulating a rapid object passby", []string{"whoosh", "transition", "fast", "passby", "air", "cinematic"}},
		{"08 Rewinding.wav", "sfx_tape_rewind_cinematic_01.wav", "transition", "Fast tape rewinding sound effect", []string{"rewind", "tape", "reverse", "transition", "cinematic"}},
		{"29 Swing A.wav", "sfx_whoosh_swing_fast_01.wav", "whoosh", "Fast air movement simulating a physical swing or swish", []string{"swing", "whoosh", "movement", "swish", "air", "transition"}},
		{"11 Low Quick.wav", "sfx_whoosh_low_quick_01.wav", "whoosh", "Short low-frequency whoosh for fast transitions and dramatic movement", []string{"low", "quick", "whoosh", "bass", "movement", "transition"}},
		{"sfx_cinematic_whoosh_passby_02.wav", "sfx_whoosh_low_quick_01.wav", "whoosh", "Short low-frequency whoosh for fast transitions and dramatic movement", []string{"low", "quick", "whoosh", "bass", "movement", "transition"}},
		{"audio_sound_1.mp3", "sfx_electronic_sweep_layered_01.mp3", "whoosh", "Layered electronic sweep with two-part movement for scene changes, reveals and motion transitions", []string{"transition", "sweep", "whoosh", "electronic", "movement", "reveal"}},
		{"audio_sound_9.mp3", "sfx_whoosh_broadband_fast_01.mp3", "whoosh", "Short broadband air and noise sweep for fast cuts, wipes and energetic visual transitions", []string{"transition", "whoosh", "sweep", "air", "fast", "wipe"}},
		{"sfx_tape_rewind_cinematic_01.wav", "sfx_transition_rewind_01.wav", "transition", "Fast reverse and rewind effect for flashbacks, time reversal and backward scene transitions", []string{"rewind", "reverse", "backward", "flashback", "time", "transition"}},
		{"rm whoosh.wav", "sfx_whoosh_rm_01.wav", "whoosh", "Fast movement whoosh transition", []string{"whoosh", "movement", "transition", "air"}},
		{"Short Whoosh.mp3", "sfx_whoosh_short_01.mp3", "whoosh", "Short air whoosh for quick transitions", []string{"whoosh", "short", "transition", "air"}},
		{"SOUND 6.mp3", "sfx_whoosh_synth_pitch_01.mp3", "whoosh", "Aggressive analog synthesizer pitch whoosh for cinematic energy and transitions", []string{"synth", "whoosh", "pitch", "electronic", "transition", "sci-fi"}},
		{"sfx_whoosh_rm_01.wav", "sfx_whoosh_atmospheric_low_01.wav", "whoosh", "Deep atmospheric low-frequency air movement whoosh transition", []string{"whoosh", "sub", "air", "transition", "cinematic", "movement"}},
		{"sfx_whoosh_short_01.mp3", "sfx_whoosh_swish_fast_01.mp3", "whoosh", "Classic fast air swish movement for graphic whip pans and fast editing cuts", []string{"whoosh", "swish", "fast", "transition", "movement"}},
		{"Spooky Wind.wav", "sfx_whoosh_spooky_wind_01.wav", "whoosh", "Spooky atmospheric wind movement", []string{"wind", "spooky", "whoosh", "atmosphere", "horror"}},
		{"swipes.mp3", "sfx_whoosh_swipes_01.mp3", "whoosh", "Fast swipe movement transition sound", []string{"swipe", "whoosh", "movement", "transition"}},
		{"Swoosh.mp3", "sfx_whoosh_swoosh_01.mp3", "whoosh", "Clean swoosh movement transition", []string{"swoosh", "whoosh", "air", "transition"}},
		{"WHOOSH FIRE TRANSITION.mp3", "sfx_whoosh_fire_transition_01.mp3", "whoosh", "Blazing fireball whoosh effect designed for dynamic visual transitions", []string{"fire", "whoosh", "transition", "flame", "burn", "cinematic"}},
		{"audio_sound_5.mp3", "sfx_whoosh_suction_fast_01.mp3", "whoosh", "Clean, swift vacuum-like air suction pass-by transition", []string{"whoosh", "suction", "air", "fast", "transition", "swipe"}},
		{"SOUND 6_2.mp3", "sfx_whoosh_digital_minimal_01.mp3", "whoosh", "Slick low-profile digital sweep whoosh for subtle interface navigation", []string{"whoosh", "sweep", "digital", "ui", "transition", "minimal"}},
		{"audio_sound_10.mp3", "sfx_whoosh_sub_stereo_01.mp3", "whoosh", "Deep panoramic sub-bass whoosh with a widening stereo image", []string{"whoosh", "sub", "bass", "stereo", "cinematic", "transition"}},
		{"sfx_whoosh_swipes_01.mp3", "sfx_whoosh_swipes_01.mp3", "whoosh", "Sequence of short, organic whip-swipes ideal for rapid UI elements or cuts", []string{"swipe", "whoosh", "whip", "fast", "organic", "ui"}},
		{"sfx_whoosh_swoosh_01.mp3", "sfx_whoosh_swoosh_01.mp3", "whoosh", "Classic clean mid-range air movement swoosh for motion graphics", []string{"swoosh", "whoosh", "air", "motion", "transition"}},
		{"whoosh-6316.mp3", "sfx_whoosh_6316_01.mp3", "whoosh", "Whoosh movement transition sound", []string{"whoosh", "air", "movement", "transition"}},
		{"06 Fire Whoosh.wav", "sfx_whoosh_fire_ignite_01.wav", "whoosh", "Combustive heavy flame ignite and fast pass-by transition", []string{"whoosh", "fire", "flame", "ignite", "transition"}},
		{"09 Short Whoosh.wav", "sfx_whoosh_short_lowmid_01.wav", "whoosh", "Snappy organic low-mid air swish for quick movement", []string{"whoosh", "swish", "short", "fast", "movement"}},
		{"Rake Swing Whoosh Close.mp3", "sfx_whoosh_rake_swing_close_01.mp3", "whoosh", "Organic, multi-layered air swish close to the microphone, simulating a fast swing pass-by", []string{"whoosh", "swing", "swish", "organic", "movement", "fast"}},
		{"Short Transition _2 Sound .mp3", "sfx_whoosh_electronic_swoop_01.mp3", "whoosh", "Slick electronic swoop whoosh engineered for quick visual whip cuts or slide-ins", []string{"whoosh", "transition", "electronic", "swoop", "fast", "cut"}},
		{"ES_Riser Suction 5 - SFX Producer.mp3", "sfx_transition_riser_suction_01.mp3", "transition", "Cinematic atmospheric riser with a distinct reverse suction effect building up tension", []string{"riser", "suction", "transition", "cinematic", "tension", "swell"}},
		{"ES_Jump Swish - SFX Producer.mp3", "sfx_transition_jump_swish_01.mp3", "transition", "Dynamic, fast swoosh or swish sound effect, perfect for quick camera pans, jumps, or UI transitions", []string{"jump", "swish", "swoosh", "transition", "whoosh", "motion"}},
		{"15 Fast Forward.wav", "sfx_whoosh_fast_forward_01.wav", "whoosh", "High-velocity linear tape scrubbing fast-forward telemetry sound effect", []string{"fast-forward", "scrub", "whoosh", "transition", "tape", "speed"}},
		{"arrow sounds.mp3", "sfx_whoosh_arrow_whistle_01.mp3", "whoosh", "High-frequency rapid mechanical whistling loops simulating arrows slicing through air", []string{"arrow", "whoosh", "whistle", "projectile", "fast", "loop"}},
		{"Fast Forward Sound Effect(MP3_160K).mp3", "sfx_whoosh_fast_forward_01.mp3", "whoosh", "High-velocity linear tape scrubbing fast-forward telemetry sound effect", []string{"fast-forward", "scrub", "whoosh", "transition", "tape", "speed"}},
		{"arrow sounds.mp3", "sfx_whoosh_arrow_whistle_01.mp3", "whoosh", "High-frequency rapid mechanical whistling loops simulating arrows slicing through air", []string{"arrow", "whoosh", "whistle", "projectile", "fast", "loop"}},
		{"sfx_whoosh_fire_transition_01.mp3", "sfx_whoosh_fire_transition_01.mp3", "whoosh", "Blazing fireball whoosh effect designed for dynamic visual transitions", []string{"fire", "whoosh", "transition", "flame", "burn", "cinematic"}},
		{"sfx_whoosh_6316_01.mp3", "sfx_whoosh_synthetic_swipe_01.mp3", "whoosh", "Short, low-profile synthetic swipe whoosh for digital transitions", []string{"whoosh", "swipe", "fast", "transition", "synthetic"}},
		{"sfx_whoosh_swing_fast_01.wav", "sfx_whoosh_swing_fast_01.wav", "whoosh", "Fast air movement simulating a physical swing or swish", []string{"swing", "whoosh", "movement", "swish", "air", "transition"}},
		{"mixkit-cinematic-transition-wind-swoosh-1468.wav", "sfx_whoosh_cinematic_wind_01.wav", "transition", "Sharp cinematic wind swoosh transition, ideal for fast camera cuts or movement", []string{"swoosh", "transition", "wind", "cinematic", "whoosh"}},
		{"Lens flare transition sound effect.mp3", "sfx_transition_lens_flare_sweep_01.mp3", "transition", "Smooth synth riser layered with a subtle sweeping whoosh, simulating a visual light leak or lens flare", []string{"transition", "lens-flare", "whoosh", "synth", "sweep"}},
		{"Long whoosh sound effect.mp3", "sfx_whoosh_long_cinematic_01.mp3", "transition", "Deep and prolonged cinematic whoosh effect building up with a heavy air rushing texture", []string{"whoosh", "long", "transition", "cinematic", "flyby", "sub"}},
		{"mixkit-arrow-whoosh-1491.wav", "sfx_whoosh_arrow_fast_01.wav", "transition", "Fast, high-frequency whip swish, mimicking the sound of an arrow tearing through the air", []string{"arrow", "whoosh", "swish", "whip", "fast", "transition"}},
		{"ES_Jump Swish - SFX Producer.mp3", "sfx_transition_jump_swish_01.mp3", "transition", "Dynamic, fast swoosh or swish sound effect, perfect for quick camera pans, jumps, or UI transitions", []string{"jump", "swish", "swoosh", "transition", "whoosh", "motion"}},
	}
}
