package soundeffects

func soundEffectsMiscCatalog() []additionalSoundEffect {
	return []additionalSoundEffect{
		{"Cartoon Splat.wav", "sfx_cartoon_splat_squish.wav", "cartoon", "Cartoon splat and squish impact effect", []string{"cartoon", "splat", "squish", "impact", "funny"}},
		{"GEARS_TURNING_SOUND_EFFECT_FREE_FWOSt38lbFE_137.mp4", "sfx_mechanical_gears_turning_01.mp4", "mechanical", "Mechanical gears turning and rotating", []string{"gears", "mechanical", "turning", "machine", "rotation"}},
		{"Goofy 1 ,2 and 3 .mp3", "sfx_cartoon_goofy_sequence_01.mp3", "cartoon", "Goofy cartoon sequence of comic sound effects", []string{"cartoon", "goofy", "comedy", "sequence", "funny"}},
		{"mixkit-21-445.mp3", "audio_mixkit_21_445_01.mp3", "audio", "Mixkit audio asset 21-445", []string{"mixkit", "audio", "library"}},
		{"mixkit-zay-zay-309.mp3", "audio_mixkit_zay_zay_01.mp3", "audio", "Mixkit Zay Zay audio asset", []string{"mixkit", "audio", "library"}},
		{"SOUND 1.mp3", "audio_sound_1.mp3", "audio", "Unclassified audio asset SOUND 1", []string{"audio", "unclassified", "library"}},
		{"SOUND 9.mp3", "audio_sound_9.mp3", "audio", "Unclassified audio asset SOUND 9", []string{"audio", "unclassified", "library"}},
		{"sfx_cartoon_goofy_sequence_01.mp3", "sfx_cartoon_goofy_boing_spring.mp3", "cartoon", "Goofy cartoon boing with spring vibrations", []string{"cartoon", "goofy", "boing", "spring", "jump", "funny"}},
		{"sfx_mechanical_gears_turning_01.mp4", "sfx_mechanical_gears_turning_loop.mp4", "industrial", "Heavy mechanical gears turning and grinding with metallic friction", []string{"gears", "mechanical", "industrial", "turning", "clockwork", "metallic"}},
		{"010.wav", "audio_010.wav", "audio", "Unclassified audio asset 010", []string{"audio", "unclassified", "library"}},
		{"14 Disc Read.wav", "sfx_mechanical_disc_read_01.wav", "industrial", "Mechanical disc drive reading and seeking", []string{"disc", "read", "drive", "mechanical", "computer", "industrial"}},
		{"Bloop Cartoon Sound Effect (MP3_160K) (1).mp3", "sfx_cartoon_bloop_bubble_01.mp3", "cartoon", "Comedic round bubble bloop sound for playful UI", []string{"bloop", "cartoon", "bubble", "pop", "comic", "funny"}},
		{"Cartoon Splat.wav", "sfx_cartoon_splat_01.wav", "cartoon", "Comedic wet splat impact for funny accidents and exaggerated visual gags", []string{"cartoon", "splat", "comic", "wet", "impact", "funny"}},
		{"sfx_cartoon_splat_squish_05.wav", "sfx_cartoon_splat_01.wav", "cartoon", "Comedic wet splat impact for funny accidents and exaggerated visual gags", []string{"cartoon", "splat", "comic", "wet", "impact", "funny"}},
		{"sfx_foley_racks_01.wav", "sfx_mechanical_racks_01.wav", "mechanical", "Repeated metallic rack movement and light mechanical rattling for industrial or equipment scenes", []string{"racks", "metal", "mechanical", "rattling", "movement", "industrial"}},
		{"sfx_mechanical_gears_turning_loop.mp4", "sfx_mechanical_gears_turning_loop.mp4", "mechanical", "Continuous turning gears and machinery movement for industrial mechanisms and mechanical processes", []string{"gears", "machinery", "mechanism", "turning", "industrial", "mechanical"}},
		{"sfx_cartoon_goofy_boing_spring.mp3", "sfx_cartoon_goofy_boing_spring.mp3", "cartoon", "Three separated goofy spring-bounce sounds for comedy, reactions and exaggerated movement", []string{"goofy", "spring", "bounce", "boing", "cartoon", "comedy"}},
		{"SOUND 4.mp3", "audio_sound_4.mp3", "audio", "Unclassified audio asset SOUND 4", []string{"audio", "unclassified", "library"}},
		{"sfx_energy_light_shot_01.mp3", "sfx_scifi_energy_beam_shot_01.mp3", "sci-fi", "Sci-fi energy beam charging up and firing with a resonant harmonic laser tail", []string{"laser", "energy", "sci-fi", "charge", "beam", "weapon"}},
		{"SOUND 5.mp3", "audio_sound_5.mp3", "audio", "Unclassified audio asset SOUND 5", []string{"audio", "unclassified", "library"}},
		{"SOUND 10.mp3", "audio_sound_10.mp3", "audio", "Unclassified audio asset SOUND 10", []string{"audio", "unclassified", "library"}},
		{"08 Heavy Pulsing Beat.wav", "sfx_industrial_pulsing_beat_01.wav", "industrial", "Steady four-on-the-floor distorted electronic clockwork loop", []string{"pulse", "beat", "industrial", "rhythmic", "loop", "distorted"}},
		{"Hacking Sound Effect .MP3 (MOST VIEWED VIDEO).mp3", "sfx_scifi_hacking_telemetry_01.mp3", "sci-fi", "Looping cybernetic telemetry interface sequences with digital processing chirps", []string{"hacking", "telemetry", "sci-fi", "cyber", "interface", "processing"}},
		{"Mario Coin Sound - Sound Effect (HD).mp3", "sfx_gaming_mario_coin_collect_01.mp3", "gaming", "Classic 8-bit resonant metallic chime indicating item collection or score updates", []string{"mario", "coin", "gaming", "retro", "chime", "collect"}},
		{"mixkit-cartoon-strong-fart-3050.wav", "sfx_cartoon_strong_fart_01.wav", "cartoon", "Comedic, brassy flatulence sound effect for playful and humorous context layouts", []string{"fart", "cartoon", "funny", "comic", "humor", "brassy"}},
		{"10 Evolve_Riser Robo Drums.wav", "sfx_industrial_robo_drum_riser_01.wav", "industrial", "Accelerating acoustic-synthetic percussion loop acting as a tension riser", []string{"riser", "drums", "percussion", "industrial", "rhythmic", "loop"}},
		{"Animal Crossing Menu.mp3", "sfx_gaming_animal_crossing_menu_01.mp3", "gaming", "Sequence of playful, high-pitched geometric bubble pop alerts for arcade UI selection", []string{"gaming", "menu", "pop", "ui", "retro", "bubble"}},
		{"sfx_heartbeat_beating_01.wav", "sfx_industrial_metal_beating_01.wav", "industrial", "Fast, rhythmic industrial metallic beating or mechanical hammering sequence", []string{"beating", "rhythmic", "industrial", "metallic", "hammering", "loop"}},
		{"sfx_cartoon_bloop_bubble_01.mp3", "sfx_cartoon_bloop_bubble_01.mp3", "cartoon", "Comedic round bubble bloop sound for playful UI", []string{"bloop", "cartoon", "bubble", "pop", "comic", "funny"}},
	}
}
