package soundeffects

func soundEffectsUICatalog() []additionalSoundEffect {
	return []additionalSoundEffect{
		{"sfx_foley_futuristic_metal_keyboard_01.wav", "sfx_futuristic_metallic_keyboard_press.wav", "ui", "Futuristic keyboard press with sharp metallic sci-fi texture", []string{"keyboard", "metallic", "futuristic", "sci-fi", "ui", "glitch"}},
		{"05 Reboot Failure.wav", "sfx_ui_reboot_failure_01.wav", "ui", "System reboot failure alert and error sound", []string{"ui", "reboot", "failure", "error", "system", "alert"}},
		{"10 Access Denied.wav", "sfx_ui_access_denied_01.wav", "ui", "Computer access denied alert", []string{"ui", "access", "denied", "error", "alert", "computer"}},
		{"16 Network Connect.wav", "sfx_ui_network_connect_01.wav", "ui", "Digital interface positive feedback for network connection", []string{"network", "connect", "ui", "scifi", "interface", "success"}},
		{"Apple Notification.wav", "sfx_ui_apple_notification_01.wav", "ui", "Standard clean Apple notification tone for digital alerts", []string{"apple", "notification", "alert", "ui", "ping", "message"}},
		{"19 Download.wav", "sfx_ui_download_transfer_01.wav", "ui", "Digital interface sound for downloads, data transfers and completed actions", []string{"download", "data", "transfer", "digital", "ui", "interface"}},
		{"sfx_cinematic_impact_debris_scratch_01.wav", "sfx_ui_download_transfer_01.wav", "ui", "Digital interface sound for downloads, data transfers and completed actions", []string{"download", "data", "transfer", "digital", "ui", "interface"}},
		{"sfx_futuristic_metallic_keyboard_press.wav", "sfx_ui_futuristic_metal_keyboard_01.wav", "ui", "Short futuristic metallic keyboard sequence for sci-fi interfaces and digital input", []string{"futuristic", "metal", "keyboard", "typing", "ui", "interface"}},
		{"sfx_office_keyboard_typing_fast.mp3", "sfx_ui_keyboard_press_01.mp3", "ui", "Very short keyboard key press for typing, computer actions and interface feedback", []string{"keyboard", "key", "press", "typing", "computer", "ui"}},
		{"sfx_glitch_dialup_digital_error_01.wav", "sfx_ui_dialup_modem_01.wav", "ui", "Retro dial-up modem connection sequence for old internet, computer and technology scenes", []string{"dial-up", "modem", "connection", "retro", "internet", "technology"}},
		{"Mouse click 2.mp3", "sfx_ui_mouse_click_02.mp3", "ui", "Standard tactile computer mouse click sound for interface interactions", []string{"click", "mouse", "ui", "button", "interface", "select"}},
		{"Mouse Click Sound Effect.mp3", "sfx_ui_mouse_click_03.mp3", "ui", "Computer mouse click interface sound", []string{"click", "mouse", "ui", "button", "interface"}},
		{"mouse-click-153941.mp3", "sfx_ui_mouse_click_04.mp3", "ui", "Computer mouse click interface sound variant", []string{"click", "mouse", "ui", "button", "interface"}},
		{"quick-win.mp3", "sfx_ui_quick_win_01.mp3", "ui", "Quick win and success confirmation sound", []string{"quick-win", "success", "ui", "game", "positive"}},
		{"sfx_ui_mouse_click_03.mp3", "sfx_ui_mouse_click_03.mp3", "ui", "Standard isolated digital computer mouse click", []string{"click", "mouse", "ui", "interface", "button"}},
		{"sfx_ui_mouse_click_04.mp3", "sfx_ui_mouse_click_04.mp3", "ui", "Sharp plastic mechanical mouse button press and release sequence", []string{"mouse", "click", "mechanical", "ui", "hardware"}},
		{"sfx_foley_pop_01.mp3", "sfx_ui_pop_bubble_01.mp3", "ui", "Clean organic mouth pop or bubble burst sound effect for micro-interactions", []string{"pop", "bubble", "ui", "cartoon", "organic", "alert"}},
		{"sfx_foley_pop_02.mp3", "sfx_ui_pop_hollow_01.mp3", "ui", "Short, snappy hollow pop sound ideal for casual mobile app UI states", []string{"pop", "ui", "hollow", "app", "interface", "click"}},
		{"sfx_ui_quick_win_01.mp3", "sfx_ui_quick_win_01.mp3", "ui", "Bright chiptune synthesizer arpeggio signaling success, game victory, or validation", []string{"win", "success", "chiptune", "synth", "retro", "gaming", "ui"}},
		{"03 RF Switcher.wav", "sfx_ui_rf_switcher_01.wav", "ui", "Radio-frequency switcher interface sound", []string{"rf", "switcher", "ui", "interface", "technology"}},
		{"01 Processing.wav", "sfx_ui_processing_01.wav", "ui", "Digital processing and loading interface sound", []string{"processing", "loading", "ui", "digital", "interface"}},
		{"Discord_Join.mp3", "sfx_ui_discord_join_01.mp3", "ui", "Electronic system notification chime signifying a user joining a voice channel", []string{"discord", "join", "ui", "chime", "notification", "alert"}},
		{"Display Digits 1.wav", "sfx_ui_display_digits_counter_01.wav", "ui", "Ultra-fast digital counter scrolling sound for tracking numerical updates on an interface", []string{"display", "digits", "counter", "scrolling", "ui", "data"}},
		{"Game Menu Select Sound Effect.mp3", "sfx_gaming_menu_select_blip_01.mp3", "ui", "High-pitched arcade synthesizer blip for menu selections and button highlights", []string{"gaming", "menu", "select", "blip", "ui", "arcade"}},
		{"Iphone Send.wav", "sfx_ui_iphone_send_01.wav", "ui", "Standard modern smartphone swoosh chime indicating an outgoing text message", []string{"iphone", "send", "swoosh", "ui", "notification", "message"}},
		{"SOUND 3.mp3", "sfx_ui_metallic_select_click_01.mp3", "ui", "Short metallic impact click designed for industrial UI button selections", []string{"click", "metallic", "ui", "button", "interface"}},
		{"rm click (1).wav", "sfx_ui_click_rm_01.wav", "ui", "Minimalist geometric digital click for software menu navigation states", []string{"click", "ui", "minimal", "interface", "navigation"}},
		{"rm click (2).wav", "sfx_ui_click_rm_02.wav", "ui", "Soft analog-style click accent, slightly lower pitch for secondary interface feedback", []string{"click", "ui", "analog", "interface", "soft"}},
		{"rm click (3).wav", "sfx_ui_click_rm_03.wav", "ui", "Snappy, clean transient click sound effect for micro-interactions and checkboxes", []string{"click", "ui", "snappy", "transient", "interface"}},
		{"Ascending sound effect.mp3", "sfx_ui_ascending_success_scale_01.mp3", "ui", "Playful geometric arcade synth scale climbing upwards to indicate success", []string{"ascending", "synth", "scale", "success", "gaming", "ui"}},
		{"correct sfx.mp3", "sfx_ui_correct_chime_01.mp3", "ui", "Bright, high-pitched acoustic bell chime indicating a correct answer, success, or positive notification", []string{"correct", "chime", "bell", "success", "ui", "notification"}},
		{"Discord_Leave.mp3", "sfx_ui_discord_leave_01.mp3", "ui", "The official Discord user interface sound effect played when disconnecting from a voice channel", []string{"discord", "leave", "disconnect", "ui", "notification", "gaming"}},
		{"Display Digits 2.wav", "sfx_ui_display_digits_buzz_01.wav", "ui", "High-frequency electronic buzz indicator, simulating real-time digit rendering or text generation on a screen", []string{"display", "digits", "electronic", "buzz", "ui", "cyber"}},
		{"Display Digits 3.wav", "sfx_ui_display_digits_clicking_01.wav", "ui", "Continuous rapid digital micro-clicking feedback, used for on-screen numeric updates or interface processing", []string{"display", "digits", "clicking", "data", "ui", "feedback"}},
		{"Display Digits 4.wav", "sfx_ui_display_digits_stutter_01.wav", "ui", "Aggressive mechanical-digital stutter signal, mimicking an ongoing numeric readout or screen data refresh", []string{"display", "digits", "stutter", "readout", "ui", "glitch"}},
		{"11 Access Granted.wav", "sfx_ui_access_granted_01.wav", "ui", "Positive interface audio sequence confirmation for successful authorization log", []string{"access", "granted", "ui", "success", "interface", "confirm"}},
		{"click sound by 90 Creators.mp3", "sfx_ui_select_click_90_01.mp3", "ui", "Crisp electronic select click designed for digital buttons and menu interfaces", []string{"click", "ui", "select", "button", "interface"}},
		{"Cash Register.mp3", "sfx_ui_cash_register_success_01.mp3", "ui", "Classic mechanical cash register checkout ding for transaction success states", []string{"cash", "register", "ding", "success", "ui", "money", "sale"}},
		{"Cash Register.mp3", "sfx_ui_cash_register_success_01.mp3", "ui", "Classic mechanical cash register checkout ding for transaction success states", []string{"cash", "register", "ding", "success", "ui", "money", "sale"}},
		{"sfx_ui_apple_notification_01.wav", "sfx_ui_apple_notification_01.wav", "ui", "Standard clean apple notification tone for digital alerts", []string{"apple", "notification", "alert", "ui", "ping", "message"}},
		{"sfx_ui_access_denied_01.wav", "sfx_ui_access_denied_01.wav", "ui", "Negative digital interface feedback for rejected access, security warnings and authorization failures", []string{"access", "denied", "security", "error", "warning", "ui"}},
		{"sfx_mechanical_disc_read_01.wav", "sfx_ui_disc_read_scan_01.wav", "ui", "Futuristic disc-reading and data-scanning sequence for computers, storage and system interfaces", []string{"disc", "read", "data", "scanning", "computer", "interface"}},
		{"sfx_ui_network_connect_01.wav", "sfx_ui_network_connect_01.wav", "ui", "Digital interface positive feedback for network connection", []string{"network", "connect", "ui", "scifi", "interface", "success"}},
		{"Message sound.mp3", "sfx_ui_message_double_pop_01.mp3", "ui", "Clean, modern electronic double-pop chime indicating an incoming message or digital notification", []string{"message", "notification", "ui", "chime", "pop", "digital"}},
		{"Microsoft Windows XP Error - Sound Effect (HD)-0lhhrUuw2N8-128k-1655433026313.mp3", "sfx_ui_windows_xp_error_01.mp3", "ui", "The iconic retro Microsoft Windows XP operating system error alert sound dialog box chord", []string{"windows", "error", "retro", "os", "alert", "ui", "nostalgia"}},
	}
}
