package scripts

// ScriptRecord represents a script record in the database
type ScriptRecord struct {
	ID             int64
	Topic          string
	Title          string
	Duration       int
	Language       string
	Template       string
	Mode           string
	Tone           string
	TargetWords    int
	FinalWordCount int
	Status         string
	NarrativeText  string
	TimelineJSON   string
	EntitiesJSON   string
	MetadataJSON   string
	FullDocument   string
	ModelUsed      string
	OllamaBaseURL  string
	CreatedAt      string
	UpdatedAt      string
	Version        int
	ParentScriptID *int64
	IsDeleted      bool
}

// ScriptSectionRecord represents a section of a script
type ScriptSectionRecord struct {
	ID           int64
	ScriptID     int64
	SectionType  string
	SectionTitle string
	Content      string
	SortOrder    int
	WordCount    int
	Status       string
}

// ScriptStockMatchRecord represents a stock match for a script segment
type ScriptStockMatchRecord struct {
	ID           int64
	ScriptID     int64
	SegmentIndex int
	StockPath    string
	StockSource  string
	Score        float64
	MatchedTerms string
}

// ScriptResearchSource represents a web/youtube/transcript source used during script generation.
type ScriptResearchSource struct {
	ID             int64
	ScriptID       int64
	Query          string
	URL            string
	Title          string
	Snippet        string
	SourceType     string // "web", "youtube", "transcript", "inline"
	UsedInSections string // JSON array of section indices
	RelevanceScore float64
	CreatedAt      string
}

// ScriptGenerationLog records a single phase of script generation for debugging.
type ScriptGenerationLog struct {
	ID          int64
	ScriptID    int64
	Phase       string
	PromptHash  string
	Model       string
	InputWords  int
	OutputWords int
	DurationMs  int64
	RetryCount  int
	CacheStatus string
	Error       string
	CreatedAt   string
}

// ScriptOutlineSectionRecord represents an outline section as an intermediate step.
// The Purpose, KeyPointsJSON, and EmotionalRole fields are now populated
// from the real ScriptPlan generated by the batch outline phase (see
// batch_outline.go), not empty defaults. The schema was extended in
// migration 030 with the emotional_role column.
type ScriptOutlineSectionRecord struct {
	ID            int64
	ScriptID      int64
	SectionIndex  int
	Title         string
	Purpose       string
	TargetWords   int
	KeyPointsJSON string
	EmotionalRole string
	CreatedAt     string
}

// ScriptVersionRecord represents an explicit version of a script output.
type ScriptVersionRecord struct {
	ID           int64
	ScriptID     int64
	Version      int
	FinalText    string
	MetadataJSON string
	CreatedAt    string
}
