// Package asset — image origin & provider taxonomy (Step 1, July 2026).
//
// This file introduces the canonical ImageOrigin enum that separates images
// by how they came into existence (retrieved from the web, generated by AI,
// uploaded manually) and ImageProvider that names the specific source.
//
// Together they replace the legacy source='image' catch-all so the system
// can route search, generation, and filtering through explicit territories.

package asset

// ImageOrigin classifies the provenance of an image asset.
//
// Three territories per the image-restructuring plan (July 2026):
//   - Retrieved: scraped from Wikipedia, DuckDuckGo, SearXNG, Drive, stock.
//   - Generated: produced by an AI model (Google Slides, Flux, NVIDIA, etc.).
//   - Uploaded:  manually supplied by a user.
type ImageOrigin string

const (
	// ImageOriginRetrieved identifies an image fetched from a web or archive source.
	ImageOriginRetrieved ImageOrigin = "retrieved"

	// ImageOriginGenerated identifies an AI-generated image.
	ImageOriginGenerated ImageOrigin = "generated"

	// ImageOriginUploaded identifies a manually-uploaded image.
	ImageOriginUploaded ImageOrigin = "uploaded"
)

// IsValid reports whether the origin matches a known constant.
func (o ImageOrigin) IsValid() bool {
	switch o {
	case ImageOriginRetrieved, ImageOriginGenerated, ImageOriginUploaded:
		return true
	}
	return false
}

// ImageProvider identifies the specific source or generator of an image.
//
// Retrieved providers:
//   - wikipedia, duckduckgo, searxng, drive
//
// Generated providers:
//   - google-slides, flux, nvidia
//
// Generic:
//   - upload (manual), unknown (fallback)
type ImageProvider string

const (
	// --- Retrieved territory ---
	ProviderWikipedia  ImageProvider = "wikipedia"
	ProviderDuckDuckGo ImageProvider = "duckduckgo"
	ProviderSearXNG    ImageProvider = "searxng"
	ProviderDrive      ImageProvider = "drive"

	// --- Generated territory ---
	ProviderGoogleSlides ImageProvider = "google-slides"
	ProviderFlux         ImageProvider = "flux"
	ProviderNvidia       ImageProvider = "nvidia"

	// --- Generic ---
	ProviderUpload  ImageProvider = "upload"
	ProviderUnknown ImageProvider = "unknown"
)

// IsValid reports whether the provider matches a known constant.
func (p ImageProvider) IsValid() bool {
	switch p {
	case ProviderWikipedia, ProviderDuckDuckGo, ProviderSearXNG, ProviderDrive,
		ProviderGoogleSlides, ProviderFlux, ProviderNvidia,
		ProviderUpload, ProviderUnknown:
		return true
	}
	return false
}

// IsGenerated reports whether this provider belongs to the AI-generation territory.
func (p ImageProvider) IsGenerated() bool {
	switch p {
	case ProviderGoogleSlides, ProviderFlux, ProviderNvidia:
		return true
	}
	return false
}

// IsRetrieved reports whether this provider belongs to the web-retrieval territory.
func (p ImageProvider) IsRetrieved() bool {
	switch p {
	case ProviderWikipedia, ProviderDuckDuckGo, ProviderSearXNG, ProviderDrive:
		return true
	}
	return false
}
