import fs from 'node:fs';

// Legacy path retained for callers that explicitly opt in to cookie import.
// The scraper no longer uses this path implicitly: anonymous Chrome is the
// default and ARTLIST_COOKIE_FILE must be set explicitly to enable cookies.
export const DEFAULT_COOKIE_FILE_PATH = '/tmp/artlist_cookies.txt';

/**
 * Imports cookies from a file into the current Puppeteer page.
 * Supports two formats:
 *   - JSON: array of puppeteer-style cookie objects (name, value, domain, path, ...)
 *   - Netscape: tab-delimited cookie file (# comments + header)
 *
 * Callers pass the explicit ARTLIST_COOKIE_FILE value when cookie import is
 * enabled. An empty path is a no-op, which keeps anonymous Chrome as the
 * default and avoids stale session files affecting Artlist search.
 *
 * @param {object} page - Puppeteer page
 * @param {string} filePath - Path to the cookie file
 */
export async function importCookies(page, filePath) {
  if (!filePath) {
    return 0;
  }

  let stats = null;
  try {
    stats = fs.statSync(filePath);
  } catch {
    return 0;
  }
  if (!stats || !stats.isFile()) {
    console.log(`[artlist] cookie file not found: ${filePath}`);
    return 0;
  }

  const content = fs.readFileSync(filePath, 'utf8').trim();
  if (!content) {
    return 0;
  }

  let cookies = [];

  // Try JSON first.
  if (content.startsWith('[') || content.startsWith('{')) {
    try {
      const parsed = JSON.parse(content);
      cookies = Array.isArray(parsed) ? parsed : [parsed];
    } catch (err) {
      console.error(`[artlist] cookie file ${filePath} looks like JSON but failed to parse:`, err.message);
      return 0;
    }
  } else {
    // Netscape format.
    cookies = parseNetscapeCookies(content);
  }

  if (cookies.length === 0) {
    return 0;
  }

  // Normalize cookies to the shape page.setCookie expects.
  // Drop `sameSite` when unknown so Puppeteer uses its default.
  const validCookies = cookies
    .map((c) => {
      const normalized = {
        name: c.name,
        value: c.value,
        domain: c.domain,
        path: c.path || '/',
        expires: c.expires && Number.isFinite(c.expires) && c.expires > 0 ? c.expires : undefined,
        httpOnly: !!c.httpOnly,
        secure: !!c.secure,
      };
      // Puppeteer only accepts Strict/Lax/None for sameSite.
      if (c.sameSite === 'Strict' || c.sameSite === 'Lax' || c.sameSite === 'None') {
        normalized.sameSite = c.sameSite;
      }
      return normalized;
    })
    .filter((c) => c.name && c.value != null && c.domain);

  if (validCookies.length === 0) {
    console.warn(`[artlist] cookie file ${filePath} contained no valid cookies`);
    return 0;
  }

  // Puppeteer's page.setCookie accepts variadic args, not an array.
  try {
    await page.setCookie(...validCookies);
  } catch (err) {
    console.error(`[artlist] failed to set cookies from ${filePath}:`, err.message);
    return 0;
  }
  console.error(`[artlist] imported ${validCookies.length} cookies from ${filePath}`);
  return validCookies.length;
}

function parseNetscapeCookies(content) {
  const lines = content.split(/\r?\n/);
  const cookies = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    // Netscape format is tab-delimited with exactly 7 fields:
    // domain\tflag\tpath\tsecure\texpires\tname\tvalue
    // We split on literal tabs (not runs of tabs) so that empty or
    // value-containing-tab edge cases are handled as safely as possible.
    const parts = trimmed.split('\t');
    if (parts.length < 7) continue;
    const [domain, flag, path, secure, expires, name, ...valueParts] = parts;
    const value = valueParts.join('\t');
    if (!domain || !name) continue;
    cookies.push({
      name,
      value,
      domain,
      path: path || '/',
      secure: secure === 'TRUE',
      httpOnly: false,
      expires: Number.isFinite(Number(expires)) && Number(expires) > 0 ? Number(expires) : undefined,
    });
  }
  return cookies;
}

/**
 * Exports browser cookies to Netscape format for yt-dlp/ffmpeg.
 * @param {object} page - Puppeteer page
 * @param {string} outputPath - Path to save cookies file
 */
export async function exportCookiesForYtDlp(page, outputPath) {
  const cookies = await page.cookies();

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by PipelineGen Artlist scraper',
  ];

  for (const c of cookies) {
    const domain = c.domain || '';
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
    const name = c.name;
    const value = c.value;

    lines.push([domain, includeSubdomains, path, secure, expires, name, value].join('\t'));
  }

  fs.writeFileSync(outputPath, lines.join('\n') + '\n', 'utf8');
  console.error(`[artlist] exported ${cookies.length} cookies to ${outputPath}`);
}
